
CREATE VIEW [dbo].[LOGISTICSPOSTALADDRESSVIEW] AS SELECT T1.COUNTY AS COUNTY,T1.DISTRICT AS DISTRICT,T1.POSTBOX AS POSTBOX,T1.ADDRESS AS ADDRESS,
T1.BUILDINGCOMPLIMENT AS BUILDINGCOMPLIMENT,T1.CITY AS CITY,T1.COUNTRYREGIONID AS COUNTRYREGIONID,T1.LATITUDE AS LATITUDE,T1.STATE AS STATE,T1.STREET
 AS STREET,T1.STREETNUMBER AS STREETNUMBER,T1.TIMEZONE AS TIMEZONE,T1.LONGITUDE AS LONGITUDE,T1.ZIPCODE AS ZIPCODE,T1.LOCATION AS LOCATION,T1.VALIDFROM 
 AS VALIDFROM,T1.VALIDTO AS VALIDTO,T1.RECID AS POSTALADDRESSRECID,T1.RECID AS POSTALADDRESS,T1.DISTRICTNAME AS DISTRICTNAME,T1.FLATID_RU AS FLATID_RU,
 T1.HOUSEID_RU AS HOUSEID_RU,T1.STREETID_RU AS STREETID_RU,T1.BUILDING_RU AS BUILDING_RU,T1.APARTMENT_RU AS APARTMENT_RU,T1.ISPRIVATE AS ISPRIVATE,T1.PRIVATEFORPARTY
  AS PRIVATEFORPARTY,T1.RECID AS XRECID_LOGISTICSPOSTALADDRESS,T1.RECVERSION AS XRECVERSION_LOGISTICSPOSTALADDRESS,T1.CITYRECID AS CITYRECID,T1.PARTITION AS 
  PARTITION,T1.RECID AS RECID,T2.PARTITION AS PARTITION#2,T2.CURRENCYCODE AS COUNTRYCURRENCYCODE,T2.ISOCODE AS ISOCODE,T3.PARTITION AS PARTITION#3,T3.DESCRIPTION
   AS LOCATIONNAME
   
   
    FROM LOGISTICSPOSTALADDRESS T1 CROSS JOIN LOGISTICSADDRESSCOUNTRYREGION T2 CROSS JOIN LOGISTICSLOCATION T3
	 WHERE (T1.COUNTRYREGIONID=T2.COUNTRYREGIONID AND (T1.PARTITION = T2.PARTITION)) AND (T1.LOCATION=T3.RECID AND (T1.PARTITION = T3.PARTITION))