CREATE TABLE [dbo].[BANKACCOUNTTABLE] (
    [ACCOUNTID]                           NVARCHAR (10)    NOT NULL,
    [BANKGROUPID]                         NVARCHAR (10)    NOT NULL,
    [CURRENCYCODE]                        NVARCHAR (3)     NOT NULL,
    [NAME]                                NVARCHAR (60)    NOT NULL,
    [ACCOUNTNUM]                          NVARCHAR (35)    NOT NULL,
    [BANKDESTINATIONNAME]                 NVARCHAR (23)    NOT NULL,
    [BANKCOMPANYSTATEMENTNAME]            NVARCHAR (16)    NOT NULL,
    [BANKCIN]                             NVARCHAR (1)     NOT NULL,
    [BANKINTERBANKCLEARINGCODE_BE]        INT              NOT NULL,
    [NSFLEDGERJOURNALNAME]                NVARCHAR (10)    NOT NULL,
    [REGISTRATIONNUM]                     NVARCHAR (12)    NOT NULL,
    [PHONE]                               NVARCHAR (20)    NOT NULL,
    [TELEFAX]                             NVARCHAR (20)    NOT NULL,
    [DIVISIONPAYMID]                      NVARCHAR (35)    NOT NULL,
    [EMAIL]                               NVARCHAR (80)    NOT NULL,
    [URL]                                 NVARCHAR (255)   NOT NULL,
    [TELEX]                               NVARCHAR (20)    NOT NULL,
    [CELLULARPHONE]                       NVARCHAR (20)    NOT NULL,
    [PHONELOCAL]                          NVARCHAR (10)    NOT NULL,
    [BANKMULTICURRENCY]                   INT              NOT NULL,
    [BANKSORTCODE]                        NVARCHAR (10)    NOT NULL,
    [DISCCREDITMAXMST]                    NUMERIC (32, 16) NOT NULL,
    [BANKCLEARINGCODE]                    NVARCHAR (10)    NOT NULL,
    [BANKCONTRACTACCOUNT]                 NVARCHAR (11)    NOT NULL,
    [GIROCONTRACT]                        NVARCHAR (10)    NOT NULL,
    [GIROCONTRACTACCOUNT]                 NVARCHAR (11)    NOT NULL,
    [FEECONTRACTACCOUNT]                  NVARCHAR (11)    NOT NULL,
    [COMPANYPAYMID]                       NVARCHAR (35)    NOT NULL,
    [CUSTPAYMFEEPOST]                     INT              NOT NULL,
    [CONTACTPERSON]                       NVARCHAR (60)    NOT NULL,
    [DEBITDIRECTID]                       NVARCHAR (35)    NOT NULL,
    [SWIFTNO]                             NVARCHAR (20)    NOT NULL,
    [DISCDELAYNOTICEDAYS]                 INT              NOT NULL,
    [BANKSUFFIX]                          NVARCHAR (3)     NOT NULL,
    [BANKTRANSFERCODE]                    NVARCHAR (15)    NOT NULL,
    [PAYMMANKEEPIFREMOVEDFROMBATCH]       INT              NOT NULL,
    [PAGER]                               NVARCHAR (20)    NOT NULL,
    [SMS]                                 NVARCHAR (80)    NOT NULL,
    [NSFFEEMARKUPGROUPMODULE]             INT              NOT NULL,
    [BANKCODETYPE]                        INT              NOT NULL,
    [IBAN]                                NVARCHAR (35)    NOT NULL,
    [LEDGERJOURNALNAMEID]                 NVARCHAR (10)    NOT NULL,
    [REMITCOLLECTIONAMOUNT]               NUMERIC (32, 16) NOT NULL,
    [REMITDISCOUNTAMOUNT]                 NUMERIC (32, 16) NOT NULL,
    [INVOICEREMITAMOUNT]                  NUMERIC (32, 16) NOT NULL,
    [NSFFEEMARKUPGROUPID]                 NVARCHAR (10)    NOT NULL,
    [INCLUDEBANKBARCODE_FI]               INT              NOT NULL,
    [ISBANKPRENOTE]                       INT              NOT NULL,
    [PRINTGIRO_FI]                        INT              NOT NULL,
    [PRENOTERESPONSEDAYS]                 INT              NOT NULL,
    [LOCATION]                            BIGINT           NOT NULL,
    [CUSTOMERPAYMENTFEELEDGERDIMENSION]   BIGINT           NOT NULL,
    [INVOICEREMITTANCELEDGERDIMENSION]    BIGINT           NOT NULL,
    [LEDGERDIMENSION]                     BIGINT           NOT NULL,
    [REMITTANCECOLLECTIONLEDGERDIMENSION] BIGINT           NOT NULL,
    [REMITTANCEDISCOUNTLEDGERDIMENSION]   BIGINT           NOT NULL,
    [ACTIVEFROM]                          DATETIME         NOT NULL,
    [ACTIVEFROMTZID]                      INT              NOT NULL,
    [ACTIVETO]                            DATETIME         NOT NULL,
    [ACTIVETOTZID]                        INT              NOT NULL,
    [BANKACCOUNTSTATUS]                   INT              NOT NULL,
    [DEFAULTDIMENSION]                    BIGINT           NOT NULL,
    [RFC_MX]                              NVARCHAR (13)    NOT NULL,
    [OVERDRAFTLIMIT]                      NUMERIC (32, 16) NOT NULL,
    [PAYMLOCALEXPORTPATH_LT]              NVARCHAR (259)   NOT NULL,
    [PAYMFOREIGNEXPORTPATH_LT]            NVARCHAR (259)   NOT NULL,
    [ACCOUNTNAMEKANA_JP]                  NVARCHAR (40)    NOT NULL,
    [TRANSTYPE_JP]                        INT              NOT NULL,
    [CURRENCYSELLORDER_TEMPLATENAME_RU]   NVARCHAR (259)   NOT NULL,
    [CORRACCOUNT_W]                       NVARCHAR (35)    NOT NULL,
    [TEMPLATEFILENAME_RU]                 NVARCHAR (259)   NOT NULL,
    [CURRENCYORDER_TEMPLATENAME_RU]       NVARCHAR (259)   NOT NULL,
    [PAYMORDERNUMSEQID_W]                 NVARCHAR (10)    NOT NULL,
    [LVPAYORDERTYPE]                      INT              NOT NULL,
    [BANKCONSTANTSYMBOL]                  BIGINT           NOT NULL,
    [BANKPOSITIVEPAYFORMAT]               BIGINT           NOT NULL,
    [BANKPOSITIVEPAYSTARTDATE]            DATETIME         NOT NULL,
    [BANKRECONALLOWEDPENNYDIFFERENCE]     NUMERIC (32, 16) NOT NULL,
    [BANKRECONCILIATIONENABLED]           INT              NOT NULL,
    [BANKRECONCILIATIONMATCHRULESET]      BIGINT           NOT NULL,
    [BANKRECONCILIATIONSTMTASPAYMCONFIRM] INT              NOT NULL,
    [BANKRECONMATCHAUTOAFTERIMPORT]       INT              NOT NULL,
    [BANKRECONMATCHRULEMANUALMATCH]       BIGINT           NOT NULL,
    [BANKRECONMATCHRULEMANUALREVERSAL]    BIGINT           NOT NULL,
    [BANKSTATEMENTFORMAT]                 BIGINT           NOT NULL,
    [BANKSTATEMENTNAME]                   NVARCHAR (60)    NOT NULL,
    [LVDEFAULTBANK]                       INT              NOT NULL,
    [SPECIFICSYMBOL]                      NVARCHAR (20)    NOT NULL,
    [CFMBANKBALANCEMINIMUM]               NUMERIC (32, 16) NOT NULL,
    [DATAAREAID]                          NVARCHAR (4)     NOT NULL,
    [RECVERSION]                          INT              NOT NULL,
    [PARTITION]                           BIGINT           NOT NULL,
    [RECID]                               BIGINT           NOT NULL,
    CONSTRAINT [I_007ACCOUNTIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [ACCOUNTID] ASC)
);

