CREATE TABLE [dbo].[BARCODESETUP] (
    [BARCODESETUPID]    NVARCHAR (10) DEFAULT ('') NOT NULL,
    [BARCODETYPE]       INT           DEFAULT ((0)) NOT NULL,
    [FONTNAME]          NVARCHAR (32) DEFAULT ('') NOT NULL,
    [FONTSIZE]          INT           DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]       NVARCHAR (60) DEFAULT ('') NOT NULL,
    [MINIMUMLENGTH]     INT           DEFAULT ((0)) NOT NULL,
    [MAXIMUMLENGTH]     INT           DEFAULT ((0)) NOT NULL,
    [RETAILBARCODEMASK] NVARCHAR (80) DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]  DATETIME      DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_MODIFIEDTIME]  INT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]        NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [DATAAREAID]        NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]        INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]         BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    [MANUFACTURERCODE]  NVARCHAR (10) DEFAULT ('') NOT NULL,
    [PREFIX]            NVARCHAR (10) DEFAULT ('') NOT NULL,
    CONSTRAINT [I_1214BARCODESETUPIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [BARCODESETUPID] ASC),
    CHECK ([RECID]<>(0))
);

