CREATE TABLE [dbo].[BOMCALCTRANS] (
    [COSTGROUPID]               NVARCHAR (10)    NOT NULL,
    [LEVEL_]                    INT              NOT NULL,
    [QTY]                       NUMERIC (32, 16) NOT NULL,
    [COSTPRICE]                 NUMERIC (32, 16) NOT NULL,
    [COSTMARKUP]                NUMERIC (32, 16) NOT NULL,
    [SALESPRICE]                NUMERIC (32, 16) NOT NULL,
    [SALESMARKUP]               NUMERIC (32, 16) NOT NULL,
    [TRANSDATE]                 DATETIME         NOT NULL,
    [LINENUM]                   NUMERIC (32, 16) NOT NULL,
    [RESOURCE_]                 NVARCHAR (30)    NOT NULL,
    [UNITID]                    NVARCHAR (10)    NOT NULL,
    [OPRID]                     NVARCHAR (10)    NOT NULL,
    [INVENTDIMSTR]              NVARCHAR (20)    NOT NULL,
    [CONSUMPTIONVARIABLE]       NUMERIC (32, 16) NOT NULL,
    [CONSUMPTIONCONSTANT]       NUMERIC (32, 16) NOT NULL,
    [BOM]                       INT              NOT NULL,
    [OPRNUM]                    INT              NOT NULL,
    [CALCTYPE]                  INT              NOT NULL,
    [COSTPRICEUNIT]             NUMERIC (32, 16) NOT NULL,
    [COSTPRICEQTY]              NUMERIC (32, 16) NOT NULL,
    [SALESPRICEQTY]             NUMERIC (32, 16) NOT NULL,
    [COSTMARKUPQTY]             NUMERIC (32, 16) NOT NULL,
    [SALESMARKUPQTY]            NUMERIC (32, 16) NOT NULL,
    [PRICECALCID]               NVARCHAR (20)    NOT NULL,
    [NUMOFSERIES]               NUMERIC (32, 16) NOT NULL,
    [OPRNUMNEXT]                INT              NOT NULL,
    [OPRPRIORITY]               INT              NOT NULL,
    [CONSUMPTIONINVENT]         NUMERIC (32, 16) NOT NULL,
    [INVENTDIMID]               NVARCHAR (20)    NOT NULL,
    [VENDID]                    NVARCHAR (20)    NOT NULL,
    [CONSUMPTYPE]               INT              NOT NULL,
    [SALESPRICEUNIT]            NUMERIC (32, 16) NOT NULL,
    [NETWEIGHTQTY]              NUMERIC (32, 16) NOT NULL,
    [INFOLOG]                   VARBINARY (MAX)  NULL,
    [SALESPRICEMODELUSED]       INT              NOT NULL,
    [PRICEDISCQTY]              NUMERIC (32, 16) NOT NULL,
    [COSTPRICEMODELUSED]        INT              NOT NULL,
    [CALCGROUPID]               NVARCHAR (10)    NOT NULL,
    [COSTPRICEFALLBACKVERSION]  NVARCHAR (10)    NOT NULL,
    [SALESPRICEFALLBACKVERSION] NVARCHAR (10)    NOT NULL,
    [ROUTELEVEL]                INT              NOT NULL,
    [COSTPRICEQTYSECCUR_RU]     NUMERIC (32, 16) NOT NULL,
    [COSTMARKUPQTYSECCUR_RU]    NUMERIC (32, 16) NOT NULL,
    [COSTPRICESECCUR_RU]        NUMERIC (32, 16) NOT NULL,
    [COSTMARKUPSECCUR_RU]       NUMERIC (32, 16) NOT NULL,
    [CONSISTOFPRICE]            NVARCHAR (20)    NOT NULL,
    [PARENTBOMCALCTRANS]        BIGINT           NOT NULL,
    [COSTCALCULATIONMETHOD]     INT              NOT NULL,
    [CREATEDDATETIME]           DATETIME         NOT NULL,
    [DATAAREAID]                NVARCHAR (4)     NOT NULL,
    [RECVERSION]                INT              NOT NULL,
    [PARTITION]                 BIGINT           NOT NULL,
    [RECID]                     BIGINT           NOT NULL,
    CONSTRAINT [I_020RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC)
);

