CREATE TABLE [dbo].[CURRENCYEURODENOMINATION] (
    [CURRENCYCODE] NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [STARTDATE]    DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [EXCHANGERATE] NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [RECVERSION]   INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]    BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]        BIGINT           NOT NULL,
    CONSTRAINT [I_6895RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

