CREATE TABLE [dbo].[CUSTPACKINGSLIPTRANS] (
    [PACKINGSLIPID]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DELIVERYDATE]                   DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [LINENUM]                        NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVENTTRANSID]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ITEMID]                         NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [EXTERNALITEMID]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [NAME]                           NVARCHAR (1000)  DEFAULT ('') NOT NULL,
    [ORDERED]                        NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTY]                            NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [REMAIN]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SALESGROUP]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PRICEUNIT]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VALUEMST]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SALESID]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SALESUNIT]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSACTIONCODE]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSPORT]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [COUNTRYREGIONOFSHIPMENT]        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTREFID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ORIGSALESID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [LINEHEADER]                     NVARCHAR (80)    DEFAULT ('') NOT NULL,
    [INVENTDIMID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [STATPROCID]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PORT]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NUMBERSEQUENCEGROUP]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYINVENTTRANSID]      NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [REMAININVENT]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SCRAP]                          INT              DEFAULT ((0)) NOT NULL,
    [STATVALUEMST]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INTRASTATDISPATCHID]            NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTQTY]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVENTREFTRANSID]               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DELIVERYTYPE]                   INT              DEFAULT ((0)) NOT NULL,
    [INVENTREFTYPE]                  INT              DEFAULT ((0)) NOT NULL,
    [SALESCATEGORY]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [ITEMCODEID]                     NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [ORIGCOUNTRYREGIONID]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ORIGSTATEID]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WEIGHT]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [DELIVERYPOSTALADDRESS]          BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTDIMENSION]               BIGINT           DEFAULT ((0)) NOT NULL,
    [SALESLINESHIPPINGDATEREQUESTED] DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [SALESLINESHIPPINGDATECONFIRMED] DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [SOURCEDOCUMENTLINE]             BIGINT           DEFAULT ((0)) NOT NULL,
    [FULLYMATCHED]                   INT              DEFAULT ((0)) NOT NULL,
    [STOCKEDPRODUCT]                 INT              DEFAULT ((0)) NOT NULL,
    [NGPCODESTABLE_FR]               BIGINT           DEFAULT ((0)) NOT NULL,
    [INVOICETRANSREFRECID]           BIGINT           DEFAULT ((0)) NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]    DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [STATISTICVALUE_LT]              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [AMOUNTCUR]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [DLVTERM]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PDSCWQTY]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWREMAIN]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                INT              DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                     INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                      BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    CONSTRAINT [I_072RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

