CREATE TABLE [dbo].[CUSTPACKINGSLIPJOUR] (
    [REFNUM]                           INT              DEFAULT ((0)) NOT NULL,
    [SALESID]                          NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ORDERACCOUNT]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEACCOUNT]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PACKINGSLIPID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PURCHASEORDER]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DELIVERYDATE]                     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DELIVERYNAME]                     NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [QTY]                              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VOLUME]                           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [WEIGHT]                           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRINTED]                          INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYPOSTED]               INT              DEFAULT ((0)) NOT NULL,
    [INTRASTATDISPATCH]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DLVTERM]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVMODE]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PRINTMGMTSITEID]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LEDGERVOUCHER]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RETURNITEMNUM]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SALESTYPE]                        INT              DEFAULT ((0)) NOT NULL,
    [FREIGHTSLIPTYPE]                  INT              DEFAULT ((0)) NOT NULL,
    [FREIGHTSLIPNUM]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PARMID]                           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [LISTCODE]                         INT              DEFAULT ((0)) NOT NULL,
    [CUSTOMERREF]                      NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [LANGUAGEID]                       NVARCHAR (7)     DEFAULT ('') NOT NULL,
    [INVENTLOCATIONID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BILLOFLADINGID]                   NVARCHAR (17)    DEFAULT ('') NOT NULL,
    [EXPORTREASON]                     NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [DOCUMENTDATE]                     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [NUMBERSEQUENCEGROUP]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYCOMPANYID]            NVARCHAR (4)     DEFAULT ('') NOT NULL,
    [INTERCOMPANYPURCHID]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [BOLPACKAGEAPPEARANCE]             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [BOLCARRIERNAME]                   NVARCHAR (140)   DEFAULT ('') NOT NULL,
    [BOLADDRESS]                       NVARCHAR (250)   DEFAULT ('') NOT NULL,
    [INVOICINGNAME]                    NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [DLVREASON]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BOLFREIGHTEDBY]                   INT              DEFAULT ((0)) NOT NULL,
    [RETURNPACKINGSLIPID]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERDELIVERYCONTACT]       NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERACCOUNT]               NVARCHAR (25)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERID]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERBLINDSHIPMENT]         INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERPHONE]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SHIPCARRIEREMAIL]                 NVARCHAR (80)    DEFAULT ('') NOT NULL,
    [DELIVERYPOSTALADDRESS]            BIGINT           DEFAULT ((0)) NOT NULL,
    [INVOICEPOSTALADDRESS]             BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTDIMENSION]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [WORKERSALESTAKER]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTHEADER]             BIGINT           DEFAULT ((0)) NOT NULL,
    [INTERNALPACKINGSLIPID]            NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [COMPILER]                         BIGINT           DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDELIVERYLOADER]     BIGINT           DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDELIVERYOWNER]      BIGINT           DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDELIVERYCONTRACTOR] BIGINT           DEFAULT ((0)) NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]      DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [INVENTPROFILETYPE_RU]             INT              DEFAULT ((0)) NOT NULL,
    [PACKINGSLIPREGISTER_LT]           INT              DEFAULT ((0)) NOT NULL,
    [PACKINGSLIPNUMBERINGCODE_LT]      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PACKINGSLIPSTATUS_LT]             INT              DEFAULT ((0)) NOT NULL,
    [PRINTBLANKDATE_LT]                INT              DEFAULT ((0)) NOT NULL,
    [CONTACTPERSONID]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEISSUEDUEDATE_W]            DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [OFFSESSIONID_RU]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PDSCWQTY]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [REASONTABLEREF_BR]                BIGINT           DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDOCUMENT]           BIGINT           DEFAULT ((0)) NOT NULL,
    [BANKLCEXPORTLINE]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                  DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                  INT              DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                       NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                       INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                        BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                            BIGINT           NOT NULL,
    [ROLINTERCOMPANYDATAAREAID]        NVARCHAR (5)     DEFAULT ('') NOT NULL,
    [ROLINTERCOMPANYPACKINGSLIPID]     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ROLINTERCOMPANYSALESID]           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    CONSTRAINT [I_071RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

