CREATE TABLE [dbo].[CUSTINVOICEJOUR] (
    [CUSTGROUP]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [REFNUM]                      INT              DEFAULT ((0)) NOT NULL,
    [SALESID]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ORDERACCOUNT]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEACCOUNT]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEDATE]                 DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DUEDATE]                     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CASHDISC]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CASHDISCDATE]                DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [QTY]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [VOLUME]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [WEIGHT]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUMLINEDISC]                 NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SALESBALANCE]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ENDDISC]                     NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVOICEAMOUNT]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CURRENCYCODE]                NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [EXCHRATE]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVOICEID]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [LEDGERVOUCHER]               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [UPDATED]                     INT              DEFAULT ((0)) NOT NULL,
    [ONACCOUNTAMOUNT]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TAXPRINTONINVOICE]           INT              DEFAULT ((0)) NOT NULL,
    [LISTCODE]                    INT              DEFAULT ((0)) NOT NULL,
    [DOCUMENTNUM]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DOCUMENTDATE]                DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CASHDISCPERCENT]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INTRASTATDISPATCH]           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DELIVERYNAME]                NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [ENTERPRISENUMBER]            NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [PURCHASEORDER]               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DLVTERM]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVMODE]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMENT]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISCCODE]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVOICEROUNDOFF]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUMMARKUP]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [COVSTATUS]                   INT              DEFAULT ((0)) NOT NULL,
    [RETURNITEMNUM]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [POSTINGPROFILE]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BACKORDER]                   INT              DEFAULT ((0)) NOT NULL,
    [PREPAYMENT]                  INT              DEFAULT ((0)) NOT NULL,
    [TAXGROUP]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TAXITEMGROUP]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TAXSPECIFYBYLINE]            INT              DEFAULT ((0)) NOT NULL,
    [EINVOICELINESPECIFIC]        INT              DEFAULT ((0)) NOT NULL,
    [ONETIMECUSTOMER]             INT              DEFAULT ((0)) NOT NULL,
    [PAYMENTSCHED]                NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [SUMTAX]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SALESTYPE]                   INT              DEFAULT ((0)) NOT NULL,
    [EINVOICEACCOUNTCODE]         NVARCHAR (35)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYPOSTED]          INT              DEFAULT ((0)) NOT NULL,
    [PARMID]                      NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RETURNREASONCODEID]          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [EUSALESLIST]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [EXCHRATESECONDARY]           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TRIANGULATION]               INT              DEFAULT ((0)) NOT NULL,
    [CUSTOMERREF]                 NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [VATNUM]                      NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [NUMBERSEQUENCEGROUP]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LANGUAGEID]                  NVARCHAR (7)     DEFAULT ('') NOT NULL,
    [INCLTAX]                     INT              DEFAULT ((0)) NOT NULL,
    [LOG]                         NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [PAYMDAYID]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVOICINGNAME]               NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [GIROTYPE]                    INT              DEFAULT ((0)) NOT NULL,
    [CONTACTPERSONID]             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SALESORIGINID]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BILLOFLADINGID]              NVARCHAR (17)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONID]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FIXEDDUEDATE]                DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [INVOICEAMOUNTMST]            NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVOICEROUNDOFFMST]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUMMARKUPMST]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUMLINEDISCMST]              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ENDDISCMST]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SALESBALANCEMST]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUMTAXMST]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRINTMGMTSITEID]             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETURNSTATUS]                INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYCOMPANYID]       NVARCHAR (4)     DEFAULT ('') NOT NULL,
    [INTERCOMPANYPURCHID]         NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PRINTEDORIGINALS]            INT              DEFAULT ((0)) NOT NULL,
    [PROFORMA]                    INT              DEFAULT ((0)) NOT NULL,
    [RCSALESLIST_UK]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [REVERSECHARGE_UK]            NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [DELIVERYPOSTALADDRESS]       BIGINT           DEFAULT ((0)) NOT NULL,
    [INVOICEPOSTALADDRESS]        BIGINT           DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTHEADER]        BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTDIMENSION]            BIGINT           DEFAULT ((0)) NOT NULL,
    [BANKLCEXPORTLINE]            BIGINT           DEFAULT ((0)) NOT NULL,
    [WORKERSALESTAKER]            BIGINT           DEFAULT ((0)) NOT NULL,
    [REVERSEDRECID]               BIGINT           DEFAULT ((0)) NOT NULL,
    [RECEIPTDATECONFIRMED_ES]     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [PAYMID]                      NVARCHAR (200)   DEFAULT ('') NOT NULL,
    [TAXINVOICESALESID]           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU] DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [MCREMAIL]                    NVARCHAR (80)    DEFAULT ('') NOT NULL,
    [MCRPAYMAMOUNT]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [MCRDUEAMOUNT]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CASHDISCBASEDATE]            DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DIRECTDEBITMANDATE]          BIGINT           DEFAULT ((0)) NOT NULL,
    [ISCORRECTION]                INT              DEFAULT ((0)) NOT NULL,
    [REASONTABLEREF]              BIGINT           DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTLINE]          BIGINT           DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDOCUMENT]      BIGINT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]            DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDDATETIME]             DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]             INT              DEFAULT ((0)) NOT NULL,
    [CREATEDBY]                   NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [DATAAREAID]                  NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                  INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                   BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                       BIGINT           NOT NULL,
    [EDICUSTINVOICESTATUS]        INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_062RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_CUSTINVJOUR_CODE]
    ON [dbo].[CUSTINVOICEJOUR]([CURRENCYCODE] ASC, [PARTITION] ASC)
    INCLUDE([SALESID], [INVOICEDATE], [INVOICEID], [NUMBERSEQUENCEGROUP], [DATAAREAID]);

