CREATE TABLE [dbo].[CUSTOMER_PRIMARY_LEGAL_ENTITY_ACCT] (
    [ACCOUNTNUM]           VARCHAR (30) NOT NULL,
    [PRIMARY_LEGAL_ENTITY] VARCHAR (4)  NULL,
    CONSTRAINT [PK_CUSTOMER_PRIMARY_LEGAL_ENTITY_ACCT] PRIMARY KEY CLUSTERED ([ACCOUNTNUM] ASC)
);

