CREATE TABLE [dbo].[CUSTTRANS] (
    [ACCOUNTNUM]                        NVARCHAR (20)    NOT NULL,
    [TRANSDATE]                         DATETIME         NOT NULL,
    [VOUCHER]                           NVARCHAR (20)    NOT NULL,
    [INVOICE]                           NVARCHAR (20)    NOT NULL,
    [TXT]                               NVARCHAR (60)    NOT NULL,
    [AMOUNTCUR]                         NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTCUR]                   NUMERIC (32, 16) NOT NULL,
    [AMOUNTMST]                         NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTMST]                   NUMERIC (32, 16) NOT NULL,
    [CURRENCYCODE]                      NVARCHAR (3)     NOT NULL,
    [DUEDATE]                           DATETIME         NOT NULL,
    [LASTSETTLEVOUCHER]                 NVARCHAR (20)    NOT NULL,
    [LASTSETTLEDATE]                    DATETIME         NOT NULL,
    [LASTEXCHADJVOUCHER]                NVARCHAR (20)    NOT NULL,
    [CLOSED]                            DATETIME         NOT NULL,
    [TRANSTYPE]                         INT              NOT NULL,
    [APPROVED]                          INT              NOT NULL,
    [EXCHADJUSTMENT]                    NUMERIC (32, 16) NOT NULL,
    [DOCUMENTNUM]                       NVARCHAR (20)    NOT NULL,
    [DOCUMENTDATE]                      DATETIME         NOT NULL,
    [LASTEXCHADJRATE]                   NUMERIC (32, 16) NOT NULL,
    [FIXEDEXCHRATE]                     INT              NOT NULL,
    [LASTEXCHADJ]                       DATETIME         NOT NULL,
    [CORRECT]                           INT              NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]        NVARCHAR (10)    NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]        NVARCHAR (140)   NOT NULL,
    [SETTLEMENT]                        INT              NOT NULL,
    [INTEREST]                          INT              NOT NULL,
    [COLLECTIONLETTER]                  INT              NOT NULL,
    [DEFAULTDIMENSION]                  BIGINT           NOT NULL,
    [POSTINGPROFILECLOSE]               NVARCHAR (10)    NOT NULL,
    [EXCHRATESECOND]                    NUMERIC (32, 16) NOT NULL,
    [BANKLCEXPORTLINE]                  BIGINT           NOT NULL,
    [ACCOUNTINGEVENT]                   BIGINT           NOT NULL,
    [EXCHRATE]                          NUMERIC (32, 16) NOT NULL,
    [LASTSETTLEACCOUNTNUM]              NVARCHAR (20)    NOT NULL,
    [COMPANYBANKACCOUNTID]              NVARCHAR (10)    NOT NULL,
    [THIRDPARTYBANKACCOUNTID]           NVARCHAR (10)    NOT NULL,
    [PAYMMODE]                          NVARCHAR (10)    NOT NULL,
    [PAYMREFERENCE]                     NVARCHAR (20)    NOT NULL,
    [PAYMMETHOD]                        INT              NOT NULL,
    [CASHPAYMENT]                       INT              NOT NULL,
    [CONTROLNUM]                        NVARCHAR (20)    NOT NULL,
    [DELIVERYMODE]                      NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILE]                    NVARCHAR (10)    NOT NULL,
    [OFFSETRECID]                       BIGINT           NOT NULL,
    [EUROTRIANGULATION]                 INT              NOT NULL,
    [ORDERACCOUNT]                      NVARCHAR (20)    NOT NULL,
    [CASHDISCCODE]                      NVARCHAR (10)    NOT NULL,
    [PREPAYMENT]                        INT              NOT NULL,
    [PAYMSPEC]                          NVARCHAR (10)    NOT NULL,
    [CUSTEXCHADJUSTMENTREALIZED]        NUMERIC (32, 16) NOT NULL,
    [CUSTEXCHADJUSTMENTUNREALIZED]      NUMERIC (32, 16) NOT NULL,
    [PAYMMANLACKDATE]                   DATETIME         NOT NULL,
    [PAYMMANBATCH]                      NVARCHAR (20)    NOT NULL,
    [PAYMID]                            NVARCHAR (200)   NOT NULL,
    [BILLOFEXCHANGEID]                  NVARCHAR (20)    NOT NULL,
    [BILLOFEXCHANGESTATUS]              INT              NOT NULL,
    [BILLOFEXCHANGESEQNUM]              INT              NOT NULL,
    [BANKREMITTANCEFILEID]              NVARCHAR (10)    NOT NULL,
    [COLLECTIONLETTERCODE]              INT              NOT NULL,
    [INVOICEPROJECT]                    INT              NOT NULL,
    [LASTSETTLECOMPANY]                 NVARCHAR (4)     NOT NULL,
    [CANCELLEDPAYMENT]                  INT              NOT NULL,
    [REASONREFRECID]                    BIGINT           NOT NULL,
    [REPORTINGCURRENCYAMOUNT]           NUMERIC (32, 16) NOT NULL,
    [REPORTINGEXCHADJUSTMENTREALIZED]   NUMERIC (32, 16) NOT NULL,
    [REPORTINGEXCHADJUSTMENTUNREALIZED] NUMERIC (32, 16) NOT NULL,
    [LASTEXCHADJRATEREPORTING]          NUMERIC (32, 16) NOT NULL,
    [REPORTINGCURRENCYCROSSRATE]        NUMERIC (32, 16) NOT NULL,
    [EXCHADJUSTMENTREPORTING]           NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTREPORTING]             NUMERIC (32, 16) NOT NULL,
    [APPROVER]                          BIGINT           NOT NULL,
    [TAXINVOICESALESID]                 NVARCHAR (20)    NOT NULL,
    [CONCESSIONCONTRACTID]              NVARCHAR (10)    NOT NULL,
    [CONCESSIONSETTLEMENTID]            NVARCHAR (10)    NOT NULL,
    [RETAILCUSTTRANS]                   INT              NOT NULL,
    [RETAILSTOREID]                     NVARCHAR (10)    NOT NULL,
    [RETAILTERMINALID]                  NVARCHAR (10)    NOT NULL,
    [RETAILTRANSACTIONID]               NVARCHAR (44)    NOT NULL,
    [CUSTBILLINGCLASSIFICATION]         BIGINT           NOT NULL,
    [MCRPAYMORDERID]                    NVARCHAR (20)    NOT NULL,
    [DIRECTDEBITMANDATE]                BIGINT           NOT NULL,
    [MODIFIEDDATETIME]                  DATETIME         NOT NULL,
    [DEL_MODIFIEDTIME]                  INT              NOT NULL,
    [MODIFIEDBY]                        NVARCHAR (8)     NOT NULL,
    [MODIFIEDTRANSACTIONID]             BIGINT           NOT NULL,
    [CREATEDDATETIME]                   DATETIME         NOT NULL,
    [DEL_CREATEDTIME]                   INT              NOT NULL,
    [CREATEDBY]                         NVARCHAR (8)     NOT NULL,
    [CREATEDTRANSACTIONID]              BIGINT           NOT NULL,
    [DATAAREAID]                        NVARCHAR (4)     NOT NULL,
    [RECVERSION]                        INT              NOT NULL,
    [PARTITION]                         BIGINT           NOT NULL,
    [RECID]                             BIGINT           NOT NULL,
    CONSTRAINT [I_078RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC)
);

