CREATE TABLE [dbo].[DATA_LOAD_ERROR] (
    [ERROR_ID]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [ERROR_AREA]     NVARCHAR (50)   NULL,
    [ERROR_SEVERITY] NVARCHAR (2)    NULL,
    [ERROR_MESSAGE]  NVARCHAR (2000) NULL,
    [ERROR_DATETIME] DATETIME        NULL,
    CONSTRAINT [PK_DATA_LOAD_ERROR] PRIMARY KEY CLUSTERED ([ERROR_ID] ASC)
);

