CREATE TABLE [dbo].[DIMENSIONATTRIBUTEDIRCATEGORY] (
    [DIMENSIONATTRIBUTE] BIGINT NOT NULL,
    [DIRCATEGORY]        BIGINT NOT NULL,
    [RECVERSION]         INT    NOT NULL,
    [PARTITION]          BIGINT NOT NULL,
    [RECID]              BIGINT NOT NULL,
    CONSTRAINT [I_372RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

