CREATE TABLE [dbo].[DIMENSIONATTRIBUTE] (
    [NAME]                                     NVARCHAR (60)    NOT NULL,
    [KEYATTRIBUTE]                             INT              NOT NULL,
    [VALUEATTRIBUTE]                           INT              NOT NULL,
    [NAMEATTRIBUTE]                            INT              NOT NULL,
    [BACKINGENTITYTYPE]                        INT              NOT NULL,
    [REPORTCOLUMNNAME]                         NVARCHAR (6)     NOT NULL,
    [HASHKEY]                                  UNIQUEIDENTIFIER NOT NULL,
    [TYPE]                                     INT              NOT NULL,
    [VIEWNAME]                                 NVARCHAR (40)    NOT NULL,
    [BACKINGENTITYTABLENAME]                   NVARCHAR (40)    NOT NULL,
    [BACKINGENTITYKEYFIELDNAME]                NVARCHAR (40)    NOT NULL,
    [BACKINGENTITYVALUEFIELDNAME]              NVARCHAR (40)    NOT NULL,
    [BACKINGENTITYTABLEID]                     INT              NOT NULL,
    [BACKINGENTITYKEYFIELDID]                  INT              NOT NULL,
    [BACKINGENTITYVALUEFIELDID]                INT              NOT NULL,
    [ISBALANCING_PSN]                          INT              NOT NULL,
    [BALANCINGDIMENSION_PSN]                   BIGINT           NOT NULL,
    [DOCUDATASOURCEQUERYNAME]                  NVARCHAR (40)    NOT NULL,
    [TRANSLATIONKEYFIELDID]                    INT              NOT NULL,
    [TRANSLATIONKEYFIELDNAME]                  NVARCHAR (40)    NOT NULL,
    [TRANSLATIONLANGUAGEIDFIELDID]             INT              NOT NULL,
    [TRANSLATIONLANGUAGEIDFIELDNAME]           NVARCHAR (40)    NOT NULL,
    [TRANSLATIONNAMEFIELDID]                   INT              NOT NULL,
    [TRANSLATIONNAMEFIELDNAME]                 NVARCHAR (40)    NOT NULL,
    [TRANSLATIONTABLEID]                       INT              NOT NULL,
    [TRANSLATIONTABLENAME]                     NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWID]                        INT              NOT NULL,
    [TRANSLATIONVIEWKEYFIELDID]                INT              NOT NULL,
    [TRANSLATIONVIEWKEYFIELDNAME]              NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWLANGUAGEIDFIELDID]         INT              NOT NULL,
    [TRANSLATIONVIEWLANGUAGEIDFIELDNAME]       NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWNAME]                      NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWNAMEFIELDID]               INT              NOT NULL,
    [TRANSLATIONVIEWNAMEFIELDNAME]             NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWSYSTEMLANGUAGEIDFIELDID]   INT              NOT NULL,
    [TRANSLATIONVIEWSYSTEMLANGUAGEIDFIELDNAME] NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWTRANSLATEDNAMEFIELDID]     INT              NOT NULL,
    [TRANSLATIONVIEWTRANSLATEDNAMEFIELDNAME]   NVARCHAR (40)    NOT NULL,
    [TRANSLATIONVIEWVALUEFIELDID]              INT              NOT NULL,
    [TRANSLATIONVIEWVALUEFIELDNAME]            NVARCHAR (40)    NOT NULL,
    [USETRANSLATIONNAMEMETHOD]                 INT              NOT NULL,
    [MODIFIEDBY]                               NVARCHAR (8)     NOT NULL,
    [RECVERSION]                               INT              NOT NULL,
    [PARTITION]                                BIGINT           NOT NULL,
    [RECID]                                    BIGINT           NOT NULL,
    CONSTRAINT [I_362RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

