CREATE TABLE [dbo].[DIMENSIONATTRIBUTEVALUECOMBINATION] (
    [DISPLAYVALUE]        NVARCHAR (500) NOT NULL,
    [MAINACCOUNT]         BIGINT         NOT NULL,
    [ACCOUNTSTRUCTURE]    BIGINT         NOT NULL,
    [LEDGERDIMENSIONTYPE] INT            NOT NULL,
    [HASH]                VARBINARY (28) NULL,
    [MODIFIEDBY]          NVARCHAR (8)   NOT NULL,
    [RECVERSION]          INT            NOT NULL,
    [PARTITION]           BIGINT         NOT NULL,
    [RECID]               BIGINT         NOT NULL,
    CONSTRAINT [I_385RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

