CREATE TABLE [dbo].[DIMENSIONFINANCIALTAG] (
    [DESCRIPTION]          NVARCHAR (60) NOT NULL,
    [VALUE]                NVARCHAR (30) NOT NULL,
    [FINANCIALTAGCATEGORY] BIGINT        NOT NULL,
    [RECVERSION]           INT           NOT NULL,
    [PARTITION]            BIGINT        NOT NULL,
    [RECID]                BIGINT        NOT NULL,
    CONSTRAINT [I_656RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

