CREATE TABLE [dbo].[DIMENSIONATTRIBUTEVALUEGROUPCOMBINATION] (
    [ORDINAL]                            INT    NOT NULL,
    [DIMENSIONATTRIBUTEVALUECOMBINATION] BIGINT NOT NULL,
    [DIMENSIONATTRIBUTEVALUEGROUP]       BIGINT NOT NULL,
    [RECVERSION]                         INT    NOT NULL,
    [PARTITION]                          BIGINT NOT NULL,
    [RECID]                              BIGINT NOT NULL,
    CONSTRAINT [I_473RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC)
);

