CREATE TABLE [dbo].[DIRDUNSNUMBER] (
    [DUNSNUMBER] NVARCHAR (20) DEFAULT ('') NOT NULL,
    [MODIFIEDBY] NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [RECVERSION] INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]  BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    CONSTRAINT [I_7736RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

