CREATE TABLE [dbo].[DIRPERSONNAME] (
    [PERSON]        BIGINT        DEFAULT ((0)) NOT NULL,
    [FIRSTNAME]     NVARCHAR (25) DEFAULT ('') NOT NULL,
    [MIDDLENAME]    NVARCHAR (25) DEFAULT ('') NOT NULL,
    [LASTNAME]      NVARCHAR (25) DEFAULT ('') NOT NULL,
    [VALIDFROM]     DATETIME      DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [VALIDFROMTZID] INT           DEFAULT ((37001)) NOT NULL,
    [VALIDTO]       DATETIME      DEFAULT ('2154-12-31T23:59:59.000') NOT NULL,
    [VALIDTOTZID]   INT           DEFAULT ((37001)) NOT NULL,
    [MODIFIEDBY]    NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [CREATEDBY]     NVARCHAR (8)  DEFAULT ('?') NOT NULL,
    [RECVERSION]    INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]     BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    CHECK ([RECID]<>(0))
);

