CREATE TABLE [dbo].[DIRPARTYLOCATION] (
    [PARTY]                    BIGINT         DEFAULT ((0)) NOT NULL,
    [LOCATION]                 BIGINT         DEFAULT ((0)) NOT NULL,
    [ATTENTIONTOADDRESSLINE]   NVARCHAR (255) DEFAULT ('') NOT NULL,
    [ISPOSTALADDRESS]          INT            DEFAULT ((0)) NOT NULL,
    [ISPRIMARY]                INT            DEFAULT ((0)) NOT NULL,
    [ISPRIVATE]                INT            DEFAULT ((0)) NOT NULL,
    [ISLOCATIONOWNER]          INT            DEFAULT ((0)) NOT NULL,
    [ISPRIMARYTAXREGISTRATION] INT            DEFAULT ((0)) NOT NULL,
    [ISROLEBUSINESS]           INT            DEFAULT ((0)) NOT NULL,
    [ISROLEDELIVERY]           INT            DEFAULT ((0)) NOT NULL,
    [ISROLEHOME]               INT            DEFAULT ((0)) NOT NULL,
    [ISROLEINVOICE]            INT            DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]               NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [RECVERSION]               INT            DEFAULT ((1)) NOT NULL,
    [PARTITION]                BIGINT         DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                    BIGINT         NOT NULL,
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_DIRPARTYLOC]
    ON [dbo].[DIRPARTYLOCATION]([ISPOSTALADDRESS] ASC, [ISPRIMARY] ASC)
    INCLUDE([PARTY], [LOCATION], [PARTITION], [RECID]);


GO
CREATE NONCLUSTERED INDEX [VM_INDX_DPL]
    ON [dbo].[DIRPARTYLOCATION]([PARTY] ASC, [ISPOSTALADDRESS] ASC, [ISPRIMARY] ASC);

