CREATE TABLE [dbo].[DIRPARTYTABLE] (
    [BUSINESSACTIVITY_SA]             NVARCHAR (10)    DEFAULT (NULL) NULL,
    [BUSINESSACTIVITYDESC_SA]         NVARCHAR (60)    DEFAULT (NULL) NULL,
    [FILENUMBER_SA]                   NVARCHAR (15)    DEFAULT (NULL) NULL,
    [COMPANYNAFCODE]                  BIGINT           DEFAULT (NULL) NULL,
    [BUSINESSNUMBER_CA]               NVARCHAR (9)     DEFAULT (NULL) NULL,
    [SOFTWAREIDENTIFICATIONCODE_CA]   NVARCHAR (8)     DEFAULT (NULL) NULL,
    [FISCALCODE_IT]                   NVARCHAR (11)    DEFAULT (NULL) NULL,
    [COMPANYTYPE_MX]                  INT              DEFAULT (NULL) NULL,
    [RFC_MX]                          NVARCHAR (13)    DEFAULT (NULL) NULL,
    [CURP_MX]                         NVARCHAR (18)    DEFAULT (NULL) NULL,
    [STATEINSCRIPTION_MX]             NVARCHAR (30)    DEFAULT (NULL) NULL,
    [LEGALNATURE_IT]                  INT              DEFAULT (NULL) NULL,
    [BANK]                            NVARCHAR (10)    DEFAULT (NULL) NULL,
    [GIRO]                            NVARCHAR (35)    DEFAULT (NULL) NULL,
    [REGNUM]                          NVARCHAR (25)    DEFAULT (NULL) NULL,
    [COREGNUM]                        NVARCHAR (25)    DEFAULT (NULL) NULL,
    [VATNUM]                          NVARCHAR (20)    DEFAULT (NULL) NULL,
    [IMPORTVATNUM]                    NVARCHAR (20)    DEFAULT (NULL) NULL,
    [UPSNUM]                          NVARCHAR (20)    DEFAULT (NULL) NULL,
    [TAX1099REGNUM]                   NVARCHAR (11)    DEFAULT (NULL) NULL,
    [NAMECONTROL]                     NVARCHAR (4)     DEFAULT (NULL) NULL,
    [TCC]                             NVARCHAR (5)     DEFAULT (NULL) NULL,
    [KEY_]                            INT              DEFAULT (NULL) NULL,
    [DVRID]                           NVARCHAR (20)    DEFAULT (NULL) NULL,
    [INTRASTATCODE]                   NVARCHAR (10)    DEFAULT (NULL) NULL,
    [GIROCONTRACT]                    NVARCHAR (10)    DEFAULT (NULL) NULL,
    [GIROCONTRACTACCOUNT]             NVARCHAR (11)    DEFAULT (NULL) NULL,
    [BRANCHID]                        NVARCHAR (10)    DEFAULT (NULL) NULL,
    [VATNUMBRANCHID]                  NVARCHAR (10)    DEFAULT (NULL) NULL,
    [IMPORTVATNUMBRANCHID]            NVARCHAR (10)    DEFAULT (NULL) NULL,
    [ACTIVITYCODE]                    NVARCHAR (9)     DEFAULT (NULL) NULL,
    [CONVERSIONDATE]                  DATETIME         DEFAULT (NULL) NULL,
    [ADDRFORMAT]                      NVARCHAR (10)    DEFAULT (NULL) NULL,
    [COMPANYREGCOMFR]                 NVARCHAR (30)    DEFAULT (NULL) NULL,
    [PACKMATERIALFEELICENSENUM]       NVARCHAR (20)    DEFAULT (NULL) NULL,
    [PAYMROUTINGDNB]                  NVARCHAR (8)     DEFAULT (NULL) NULL,
    [PAYMTRADERNUMBER]                NVARCHAR (4)     DEFAULT (NULL) NULL,
    [ISSUINGSIGNATURE]                NVARCHAR (20)    DEFAULT (NULL) NULL,
    [SIACODE]                         NVARCHAR (5)     DEFAULT (NULL) NULL,
    [BANKCENTRALBANKPURPOSECODE]      NVARCHAR (10)    DEFAULT (NULL) NULL,
    [BANKCENTRALBANKPURPOSETEXT]      NVARCHAR (140)   DEFAULT (NULL) NULL,
    [DBA]                             NVARCHAR (60)    DEFAULT (NULL) NULL,
    [FOREIGNENTITYINDICATOR]          INT              DEFAULT (NULL) NULL,
    [COMBINEDFEDSTATEFILER]           INT              DEFAULT (NULL) NULL,
    [LASTFILINGINDICATOR]             INT              DEFAULT (NULL) NULL,
    [VALIDATE1099ONENTRY]             INT              DEFAULT (NULL) NULL,
    [LEGALFORMFR]                     NVARCHAR (100)   DEFAULT (NULL) NULL,
    [SHIPPINGCALENDARID]              NVARCHAR (10)    DEFAULT (NULL) NULL,
    [ENTERPRISENUMBER]                NVARCHAR (50)    DEFAULT (NULL) NULL,
    [BRANCHNUMBER]                    NVARCHAR (13)    DEFAULT (NULL) NULL,
    [CUSTOMSCUSTOMERNUMBER_FI]        NVARCHAR (20)    DEFAULT (NULL) NULL,
    [CUSTOMSLICENSENUMBER_FI]         NVARCHAR (20)    DEFAULT (NULL) NULL,
    [DATAAREA]                        NVARCHAR (4)     DEFAULT (NULL) NULL,
    [PLANNINGCOMPANY]                 INT              DEFAULT (NULL) NULL,
    [TAXREPRESENTATIVE]               NVARCHAR (45)    DEFAULT (NULL) NULL,
    [ORGID]                           NVARCHAR (10)    DEFAULT (NULL) NULL,
    [BANKACCTUSEDFOR1099]             NVARCHAR (10)    DEFAULT (NULL) NULL,
    [PAYMINSTRUCTION1]                BIGINT           DEFAULT (NULL) NULL,
    [PAYMINSTRUCTION2]                BIGINT           DEFAULT (NULL) NULL,
    [PAYMINSTRUCTION3]                BIGINT           DEFAULT (NULL) NULL,
    [PAYMINSTRUCTION4]                BIGINT           DEFAULT (NULL) NULL,
    [LEGALREPRESENTATIVENAME_MX]      NVARCHAR (50)    DEFAULT (NULL) NULL,
    [LEGALREPRESENTATIVERFC_MX]       NVARCHAR (13)    DEFAULT (NULL) NULL,
    [LEGALREPRESENTATIVECURP_MX]      NVARCHAR (18)    DEFAULT (NULL) NULL,
    [FICREDITORID_DK]                 NVARCHAR (8)     DEFAULT (NULL) NULL,
    [ISCONSOLIDATIONCOMPANY]          INT              DEFAULT (NULL) NULL,
    [ISELIMINATIONCOMPANY]            INT              DEFAULT (NULL) NULL,
    [ACCOUNTINGPERSONNEL_JP]          NVARCHAR (60)    DEFAULT (NULL) NULL,
    [TEMPLATEFOLDER_W]                NVARCHAR (259)   DEFAULT (NULL) NULL,
    [COMPANYREPRESENTATIVE_JP]        NVARCHAR (60)    DEFAULT (NULL) NULL,
    [CNAE_BR]                         NVARCHAR (10)    DEFAULT (NULL) NULL,
    [RESIDENT_W]                      INT              DEFAULT (NULL) NULL,
    [PFREGNUM_RU]                     NVARCHAR (14)    DEFAULT (NULL) NULL,
    [RALIENCORPCOUNTRY]               NVARCHAR (10)    DEFAULT (NULL) NULL,
    [RALIENCORPNAME]                  NVARCHAR (60)    DEFAULT (NULL) NULL,
    [RFULLNAME]                       NVARCHAR (60)    DEFAULT (NULL) NULL,
    [ENTERPRISECODE]                  NVARCHAR (50)    DEFAULT (NULL) NULL,
    [COMMERCIALREGISTERSECTION]       NVARCHAR (10)    DEFAULT (NULL) NULL,
    [COMMERCIALREGISTERINSETNUMBER]   NVARCHAR (10)    DEFAULT (NULL) NULL,
    [COMMERCIALREGISTER]              NVARCHAR (40)    DEFAULT (NULL) NULL,
    [FSS_RU]                          NVARCHAR (10)    DEFAULT (NULL) NULL,
    [ORGANIZATIONLEGALFORM_RU]        NVARCHAR (40)    DEFAULT (NULL) NULL,
    [SUBORDINATECODE]                 NVARCHAR (5)     DEFAULT (NULL) NULL,
    [FSSACCOUNT_RU]                   NVARCHAR (20)    DEFAULT (NULL) NULL,
    [ACCOUNTANT_LT]                   NVARCHAR (60)    DEFAULT (NULL) NULL,
    [ACCOUNTOFFICEREFNUM]             NVARCHAR (13)    DEFAULT (NULL) NULL,
    [BUSINESSCOMMENCEDDATE_JP]        DATETIME         DEFAULT (NULL) NULL,
    [BUSINESSINITIALCAPITAL_JP]       NUMERIC (32, 16) DEFAULT (NULL) NULL,
    [BUSINESSITEM_JP]                 NVARCHAR (30)    DEFAULT (NULL) NULL,
    [CERTIFIEDTAXACCOUNTANT_JP]       NVARCHAR (60)    DEFAULT (NULL) NULL,
    [CUC_IT]                          NVARCHAR (8)     DEFAULT (NULL) NULL,
    [HEAD_LT]                         NVARCHAR (60)    DEFAULT (NULL) NULL,
    [LEGALREPRESENTATIVE_JP]          NVARCHAR (60)    DEFAULT (NULL) NULL,
    [PERSONINCHARGE_JP]               NVARCHAR (60)    DEFAULT (NULL) NULL,
    [PRINTCORRINVOICELABEL_DE]        INT              DEFAULT (NULL) NULL,
    [PRINTCORRINVOICELABELEFFDATE_DE] DATETIME         DEFAULT (NULL) NULL,
    [PRINTENTERPRISEREGISTER_NO]      INT              DEFAULT (NULL) NULL,
    [PRINTINNKPPINADDRESS_RU]         INT              DEFAULT (NULL) NULL,
    [TAXAUTHORITY_RU]                 NVARCHAR (10)    DEFAULT (NULL) NULL,
    [EEENABLEPERSONALDATAREADLOG]     INT              DEFAULT (NULL) NULL,
    [EEENABLEROLECHANGELOG]           INT              DEFAULT (NULL) NULL,
    [ORGANIZATIONTYPE]                INT              DEFAULT (NULL) NULL,
    [OMOPERATINGUNITTYPE]             INT              DEFAULT (NULL) NULL,
    [HCMWORKER]                       BIGINT           DEFAULT (NULL) NULL,
    [OMOPERATINGUNITNUMBER]           NVARCHAR (8)     DEFAULT (NULL) NULL,
    [INITIALS]                        NVARCHAR (10)    DEFAULT (NULL) NULL,
    [CHILDRENNAMES]                   NVARCHAR (150)   DEFAULT (NULL) NULL,
    [MARITALSTATUS]                   INT              DEFAULT (NULL) NULL,
    [HOBBIES]                         NVARCHAR (150)   DEFAULT (NULL) NULL,
    [GENDER]                          INT              DEFAULT (NULL) NULL,
    [NAMESEQUENCE]                    BIGINT           DEFAULT (NULL) NULL,
    [PHONETICFIRSTNAME]               NVARCHAR (25)    DEFAULT (NULL) NULL,
    [PHONETICMIDDLENAME]              NVARCHAR (25)    DEFAULT (NULL) NULL,
    [PHONETICLASTNAME]                NVARCHAR (25)    DEFAULT (NULL) NULL,
    [PERSONALTITLE]                   BIGINT           DEFAULT (NULL) NULL,
    [PERSONALSUFFIX]                  BIGINT           DEFAULT (NULL) NULL,
    [PROFESSIONALTITLE]               NVARCHAR (50)    DEFAULT (NULL) NULL,
    [PROFESSIONALSUFFIX]              NVARCHAR (50)    DEFAULT (NULL) NULL,
    [BIRTHMONTH]                      INT              DEFAULT (NULL) NULL,
    [BIRTHDAY]                        INT              DEFAULT (NULL) NULL,
    [BIRTHYEAR]                       INT              DEFAULT (NULL) NULL,
    [ANNIVERSARYMONTH]                INT              DEFAULT (NULL) NULL,
    [ANNIVERSARYDAY]                  INT              DEFAULT (NULL) NULL,
    [ANNIVERSARYYEAR]                 INT              DEFAULT (NULL) NULL,
    [COMMUNICATORSIGNIN]              BIGINT           DEFAULT (NULL) NULL,
    [NUMBEROFEMPLOYEES]               INT              DEFAULT (NULL) NULL,
    [ORGNUMBER]                       NVARCHAR (25)    DEFAULT (NULL) NULL,
    [ABC]                             INT              DEFAULT (NULL) NULL,
    [TEAMMEMBERSHIPCRITERION]         BIGINT           DEFAULT (NULL) NULL,
    [DESCRIPTION]                     NVARCHAR (60)    DEFAULT (NULL) NULL,
    [ISACTIVE]                        INT              DEFAULT (NULL) NULL,
    [TEAMADMINISTRATOR]               NVARCHAR (8)     DEFAULT (NULL) NULL,
    [PHONETICNAME]                    NVARCHAR (100)   DEFAULT (NULL) NULL,
    [DUNSNUMBERRECID]                 BIGINT           DEFAULT (NULL) NULL,
    [NAME]                            NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [LANGUAGEID]                      NVARCHAR (7)     DEFAULT ('') NOT NULL,
    [NAMEALIAS]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PARTYNUMBER]                     NVARCHAR (40)    DEFAULT ('') NOT NULL,
    [INSTANCERELATIONTYPE]            BIGINT           DEFAULT ((0)) NOT NULL,
    [KNOWNAS]                         NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [PRIMARYADDRESSLOCATION]          BIGINT           DEFAULT ((0)) NOT NULL,
    [PRIMARYCONTACTEMAIL]             BIGINT           DEFAULT ((0)) NOT NULL,
    [PRIMARYCONTACTFAX]               BIGINT           DEFAULT ((0)) NOT NULL,
    [PRIMARYCONTACTPHONE]             BIGINT           DEFAULT ((0)) NOT NULL,
    [PRIMARYCONTACTTELEX]             BIGINT           DEFAULT ((0)) NOT NULL,
    [PRIMARYCONTACTURL]               BIGINT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]                DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                      NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]                 DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                       NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [RECVERSION]                      INT              DEFAULT ((1)) NOT NULL,
    [RELATIONTYPE]                    BIGINT           DEFAULT ((0)) NOT NULL,
    [PARTITION]                       BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                           BIGINT           NOT NULL,
    [ROLUPCMFRSNO]                    NVARCHAR (30)    DEFAULT (NULL) NULL,
    [ROLUPDATEPRODUCTS]               INT              DEFAULT (NULL) NULL,
    CONSTRAINT [I_2303RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

