CREATE TABLE [dbo].[ECORESPRODUCTRELATIONTABLE] (
    [PRODUCT1]            BIGINT DEFAULT ((0)) NOT NULL,
    [PRODUCTRELATIONTYPE] BIGINT DEFAULT ((0)) NOT NULL,
    [PRODUCT2]            BIGINT DEFAULT ((0)) NOT NULL,
    [RECVERSION]          INT    DEFAULT ((1)) NOT NULL,
    [PARTITION]           BIGINT DEFAULT ((5637144576.)) NOT NULL,
    [RECID]               BIGINT NOT NULL,
    CONSTRAINT [I_2858RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

