CREATE TABLE [dbo].[ECORESPRODUCTCATEGORY] (
    [CATEGORYHIERARCHY] BIGINT   DEFAULT ((0)) NOT NULL,
    [CATEGORY]          BIGINT   DEFAULT ((0)) NOT NULL,
    [PRODUCT]           BIGINT   DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]  DATETIME DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [RECVERSION]        INT      DEFAULT ((1)) NOT NULL,
    [PARTITION]         BIGINT   DEFAULT ((5637144576.)) NOT NULL,
    [RECID]             BIGINT   NOT NULL,
    CONSTRAINT [I_3444RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_ERPC]
    ON [dbo].[ECORESPRODUCTCATEGORY]([CATEGORY] ASC)
    INCLUDE([PRODUCT]);

