CREATE TABLE [dbo].[ECORESPRODUCTRELATIONTYPE] (
    [NAME]       NVARCHAR (60) DEFAULT ('') NOT NULL,
    [RECVERSION] INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]  BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]      BIGINT        NOT NULL,
    CONSTRAINT [I_2859RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

