CREATE TABLE [dbo].[ECORESCATEGORY] (
    [REUSEENABLED]                  INT              DEFAULT (NULL) NULL,
    [CATEGORYHIERARCHY]             BIGINT           DEFAULT ((0)) NOT NULL,
    [PARENTCATEGORY]                BIGINT           DEFAULT ((0)) NOT NULL,
    [NAME]                          NVARCHAR (254)   DEFAULT ('') NOT NULL,
    [CODE]                          NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ISACTIVE]                      INT              DEFAULT ((0)) NOT NULL,
    [CHANGESTATUS]                  INT              DEFAULT ((0)) NOT NULL,
    [LEVEL_]                        BIGINT           DEFAULT ((0)) NOT NULL,
    [NESTEDSETRIGHT]                BIGINT           DEFAULT ((0)) NOT NULL,
    [NESTEDSETLEFT]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [ISCATEGORYATTRIBUTESINHERITED] INT              DEFAULT ((0)) NOT NULL,
    [INSTANCERELATIONTYPE]          BIGINT           DEFAULT ((0)) NOT NULL,
    [ISTANGIBLE]                    INT              DEFAULT ((0)) NOT NULL,
    [DEFAULTPROJECTGLOBALCATEGORY]  BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTTHRESHOLD_PSN]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PKWIUCODE]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]              DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]                    NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]               DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                     NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [RECVERSION]                    INT              DEFAULT ((1)) NOT NULL,
    [RELATIONTYPE]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [PARTITION]                     BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                         BIGINT           NOT NULL,
    CONSTRAINT [I_2665RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

