CREATE TABLE [dbo].[EXCHANGERATETYPE] (
    [NAME]        NVARCHAR (20) DEFAULT ('') NOT NULL,
    [DESCRIPTION] NVARCHAR (60) DEFAULT ('') NOT NULL,
    [RECVERSION]  INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]   BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    CONSTRAINT [I_6882RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

