CREATE TABLE [dbo].[INTRASTATPORT] (
    [PORTID]             NVARCHAR (10) NOT NULL,
    [DESCRIPTION]        NVARCHAR (60) NOT NULL,
    [COUNTRYREGIONID_HU] NVARCHAR (10) NOT NULL,
    [PORTSTATE_BR]       NVARCHAR (10) NOT NULL,
    [DATAAREAID]         NVARCHAR (4)  NOT NULL,
    [RECVERSION]         INT           NOT NULL,
    [PARTITION]          BIGINT        NOT NULL,
    [RECID]              BIGINT        NOT NULL,
    [ROLIMPORTCONTACT]   BIGINT        NOT NULL,
    CONSTRAINT [I_747PORTIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [PORTID] ASC)
);

