CREATE TABLE [dbo].[INVENTTRANSPOSTING] (
    [ITEMID]                 NVARCHAR (20) NOT NULL,
    [TRANSDATE]              DATETIME      NOT NULL,
    [VOUCHER]                NVARCHAR (20) NOT NULL,
    [POSTINGTYPE]            INT           NOT NULL,
    [POSTINGTYPEOFFSET]      INT           NOT NULL,
    [INVENTTRANSPOSTINGTYPE] INT           NOT NULL,
    [ISPOSTED]               INT           NOT NULL,
    [PROJID]                 NVARCHAR (20) NOT NULL,
    [INVENTTRANSORIGIN]      BIGINT        NOT NULL,
    [LEDGERDIMENSION]        BIGINT        NOT NULL,
    [OFFSETLEDGERDIMENSION]  BIGINT        NOT NULL,
    [DEFAULTDIMENSION]       BIGINT        NOT NULL,
    [TRANSBEGINTIME]         DATETIME      NOT NULL,
    [TRANSBEGINTIMETZID]     INT           NOT NULL,
    [DATAAREAID]             NVARCHAR (4)  NOT NULL,
    [RECVERSION]             INT           NOT NULL,
    [PARTITION]              BIGINT        NOT NULL,
    [RECID]                  BIGINT        NOT NULL,
    CONSTRAINT [I_553DATEVOUCHERTRANSIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [TRANSDATE] ASC, [VOUCHER] ASC, [INVENTTRANSORIGIN] ASC, [INVENTTRANSPOSTINGTYPE] ASC)
);

