CREATE TABLE [dbo].[INVENTJOURNALTRANS] (
    [JOURNALID]                     NVARCHAR (10)    NOT NULL,
    [LINENUM]                       NUMERIC (32, 16) NOT NULL,
    [TRANSDATE]                     DATETIME         NOT NULL,
    [VOUCHER]                       NVARCHAR (20)    NOT NULL,
    [JOURNALTYPE]                   INT              NOT NULL,
    [ITEMID]                        NVARCHAR (20)    NOT NULL,
    [QTY]                           NUMERIC (32, 16) NOT NULL,
    [COSTPRICE]                     NUMERIC (32, 16) NOT NULL,
    [PRICEUNIT]                     NUMERIC (32, 16) NOT NULL,
    [COSTMARKUP]                    NUMERIC (32, 16) NOT NULL,
    [COSTAMOUNT]                    NUMERIC (32, 16) NOT NULL,
    [SALESAMOUNT]                   NUMERIC (32, 16) NOT NULL,
    [PROJTRANSID]                   NVARCHAR (20)    NOT NULL,
    [INVENTTRANSID]                 NVARCHAR (20)    NOT NULL,
    [INVENTTRANSIDFATHER]           NVARCHAR (20)    NOT NULL,
    [INVENTONHAND]                  NUMERIC (32, 16) NOT NULL,
    [COUNTED]                       NUMERIC (32, 16) NOT NULL,
    [BOMLINE]                       INT              NOT NULL,
    [INVENTTRANSIDRETURN]           NVARCHAR (20)    NOT NULL,
    [PROJCATEGORYID]                NVARCHAR (30)    NOT NULL,
    [PROJID]                        NVARCHAR (20)    NOT NULL,
    [TOINVENTTRANSID]               NVARCHAR (20)    NOT NULL,
    [REASONREFRECID]                BIGINT           NOT NULL,
    [INVENTDIMID]                   NVARCHAR (20)    NOT NULL,
    [TOINVENTDIMID]                 NVARCHAR (20)    NOT NULL,
    [REQPOID]                       NVARCHAR (20)    NOT NULL,
    [ASSETTRANSTYPE]                INT              NOT NULL,
    [ASSETID]                       NVARCHAR (20)    NOT NULL,
    [ASSETBOOKID]                   NVARCHAR (10)    NOT NULL,
    [PROJTAXGROUPID]                NVARCHAR (10)    NOT NULL,
    [PROJSALESCURRENCYID]           NVARCHAR (3)     NOT NULL,
    [PROJLINEPROPERTYID]            NVARCHAR (10)    NOT NULL,
    [PROJTAXITEMGROUPID]            NVARCHAR (10)    NOT NULL,
    [PROJUNITID]                    NVARCHAR (10)    NOT NULL,
    [PROJSALESPRICE]                NUMERIC (32, 16) NOT NULL,
    [INVENTREFTYPE]                 INT              NOT NULL,
    [INVENTREFID]                   NVARCHAR (20)    NOT NULL,
    [INVENTREFTRANSID]              NVARCHAR (20)    NOT NULL,
    [PROFITSET]                     INT              NOT NULL,
    [ACTIVITYNUMBER]                NVARCHAR (50)    NOT NULL,
    [RELEASEDATE]                   DATETIME         NOT NULL,
    [RELEASEDATETZID]               INT              NOT NULL,
    [LEDGERDIMENSION]               BIGINT           NOT NULL,
    [WORKER]                        BIGINT           NOT NULL,
    [DEFAULTDIMENSION]              BIGINT           NOT NULL,
    [EXCISETARIFFCODES_IN]          BIGINT           NOT NULL,
    [EXCISETYPE_IN]                 INT              NOT NULL,
    [EXCISERECORDTYPE_IN]           INT              NOT NULL,
    [DSA_IN]                        INT              NOT NULL,
    [STORNO_RU]                     INT              NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]   DATETIME         NOT NULL,
    [SCRAPTYPEID_RU]                NVARCHAR (10)    NOT NULL,
    [RETAILINFOCODEIDEX2]           NVARCHAR (10)    NOT NULL,
    [RETAILINFORMATIONSUBCODEIDEX2] NVARCHAR (10)    NOT NULL,
    [PDSCOPYBATCHATTRIB]            INT              NOT NULL,
    [PDSCWINVENTONHAND]             NUMERIC (32, 16) NOT NULL,
    [PDSCWINVENTQTYCOUNTED]         NUMERIC (32, 16) NOT NULL,
    [PDSCWQTY]                      NUMERIC (32, 16) NOT NULL,
    [POSTALADDRESS_IN]              BIGINT           NOT NULL,
    [WAREHOUSELOCATION_IN]          BIGINT           NOT NULL,
    [MODIFIEDDATETIME]              DATETIME         NOT NULL,
    [DATAAREAID]                    NVARCHAR (4)     NOT NULL,
    [RECVERSION]                    INT              NOT NULL,
    [PARTITION]                     BIGINT           NOT NULL,
    [RECID]                         BIGINT           NOT NULL,
    CONSTRAINT [I_155LINEIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [JOURNALID] ASC, [LINENUM] ASC)
);

