CREATE TABLE [dbo].[INVENTDIM] (
    [INVENTDIMID]        NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [INVENTBATCHID]      NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [WMSLOCATIONID]      NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [WMSPALLETID]        NVARCHAR (18)  DEFAULT ('') NOT NULL,
    [INVENTSERIALID]     NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [INVENTLOCATIONID]   NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [CONFIGID]           NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTSIZEID]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTCOLORID]      NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTSITEID]       NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTGTDID_RU]     NVARCHAR (30)  DEFAULT ('') NOT NULL,
    [INVENTPROFILEID_RU] NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTOWNERID_RU]   NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [INVENTSTYLEID]      NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [LICENSEPLATEID]     NVARCHAR (25)  DEFAULT ('') NOT NULL,
    [INVENTSTATUSID]     NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [SHA1HASH]           VARBINARY (28) DEFAULT (NULL) NULL,
    [MODIFIEDDATETIME]   DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [MODIFIEDBY]         NVARCHAR (8)   DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]    DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DATAAREAID]         NVARCHAR (4)   DEFAULT ('dat') NOT NULL,
    [RECVERSION]         INT            DEFAULT ((1)) NOT NULL,
    [PARTITION]          BIGINT         DEFAULT ((5637144576.)) NOT NULL,
    [RECID]              BIGINT         NOT NULL,
    CONSTRAINT [I_698DIMIDIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [INVENTDIMID] ASC),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_INVENTDIM]
    ON [dbo].[INVENTDIM]([DATAAREAID] ASC)
    INCLUDE([INVENTDIMID], [INVENTLOCATIONID]);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_INVENTDIM_ID]
    ON [dbo].[INVENTDIM]([INVENTDIMID] ASC, [DATAAREAID] ASC)
    INCLUDE([INVENTLOCATIONID]);

