CREATE TABLE [dbo].[INVENTBUYERGROUP] (
    [DESCRIPTION] NVARCHAR (60) DEFAULT ('') NOT NULL,
    [GROUP_]      NVARCHAR (10) DEFAULT ('') NOT NULL,
    [DATAAREAID]  NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]  INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]   BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]       BIGINT        NOT NULL,
    CONSTRAINT [I_714GROUPIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [GROUP_] ASC),
    CHECK ([RECID]<>(0))
);

