CREATE TABLE [dbo].[INVENTTRANSFERLINE] (
    [TRANSFERID]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [LINENUM]                           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ITEMID]                            NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTDIMID]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTTRANSID]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTTRANSIDRECEIVE]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTTRANSIDSCRAP]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [QTYTRANSFER]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYSHIPPED]                        NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYRECEIVED]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYSHIPNOW]                        NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYRECEIVENOW]                     NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYREMAINSHIP]                     NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [QTYREMAINRECEIVE]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SHIPDATE]                          DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [RECEIVEDATE]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [REMAINSTATUS]                      INT              DEFAULT ((0)) NOT NULL,
    [QTYSCRAPPED]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [AUTORESERVATION]                   INT              DEFAULT ((0)) NOT NULL,
    [UNITID]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTTRANSIDTRANSITTO]            NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [OVERDELIVERYPCT]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [UNDERDELIVERYPCT]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVENTTRANSIDTRANSITFROM]          NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ATPTIMEFENCE]                      INT              DEFAULT ((0)) NOT NULL,
    [DELIVERYDATECONTROLTYPE]           INT              DEFAULT ((0)) NOT NULL,
    [ATPINCLPLANNEDORDERS]              INT              DEFAULT ((0)) NOT NULL,
    [ATPAPPLYSUPPLYTIMEFENCE]           INT              DEFAULT ((0)) NOT NULL,
    [ATPAPPLYDEMANDTIMEFENCE]           INT              DEFAULT ((0)) NOT NULL,
    [ATPBACKWARDSUPPLYTIMEFENCE]        INT              DEFAULT ((0)) NOT NULL,
    [ATPBACKWARDDEMANDTIMEFENCE]        INT              DEFAULT ((0)) NOT NULL,
    [STATPROCID]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PORT]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSPORT]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSACTIONCODE]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ORIGCOUNTRYREGIONID]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ORIGSTATEID]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [STATISTICALVALUE]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [AMOUNTVALUE]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [UNITPRICE_IN]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [NETAMOUNT_IN]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRICETYPE_IN]                      INT              DEFAULT ((0)) NOT NULL,
    [INVNTCOSTPRICE_IN]                 NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [FROMEXCISERECORDTYPE_IN]           INT              DEFAULT ((0)) NOT NULL,
    [TAXGROUP_IN]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TAXITEMGROUP_IN]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FROMDIRECTSETTLEMENT_IN]           INT              DEFAULT ((0)) NOT NULL,
    [FROMDSA_IN]                        INT              DEFAULT ((0)) NOT NULL,
    [VATPRICETYPE_IN]                   INT              DEFAULT ((0)) NOT NULL,
    [RETENTION_IN]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TOEXCISERECORDTYPE_IN]             INT              DEFAULT ((0)) NOT NULL,
    [VATRETENTIONCODE_IN]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CURRENCYCODE_IN]                   NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [UNITID_IN]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SALESTAXFORMTYPES_IN]              BIGINT           DEFAULT ((0)) NOT NULL,
    [EXCISETARIFFCODES_IN]              BIGINT           DEFAULT ((0)) NOT NULL,
    [FROMEXCISETYPE_IN]                 INT              DEFAULT ((0)) NOT NULL,
    [TOEXCISETYPE_IN]                   INT              DEFAULT ((0)) NOT NULL,
    [TODIRECTSETTLEMENT_IN]             INT              DEFAULT ((0)) NOT NULL,
    [RETAILREPLENISHREFTABLEID]         INT              DEFAULT ((0)) NOT NULL,
    [RETAILREPLENISHREFRECID]           BIGINT           DEFAULT ((0)) NOT NULL,
    [RETAILAREAID]                      NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [RETAILINFOCODEIDEX2]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETAILINFORMATIONSUBCODEIDEX2]     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [HHTHANDHELDUSERID]                 NVARCHAR (25)    DEFAULT ('') NOT NULL,
    [HHTTRANSTIME]                      INT              DEFAULT ((0)) NOT NULL,
    [HHTTRANSDATE]                      DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DEFAULTDIMENSION_IN]               BIGINT           DEFAULT ((0)) NOT NULL,
    [INTRACODE]                         NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [INTRASTATSPECMOVE_CZ]              NVARCHAR (2)     DEFAULT ('') NOT NULL,
    [INVENTDIMIDTO_RU]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [LINEAMOUNT_RU]                     NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ORIGCOUNTYID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PDSCWQTYRECEIVED]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYRECEIVENOW]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYREMAINRECEIVE]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYREMAINSHIP]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYSCRAPPED]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYSHIPNOW]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYSHIPPED]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWQTYTRANSFER]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSOVERRIDEFEFO]                   INT              DEFAULT ((0)) NOT NULL,
    [PRICE_RU]                          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRICEUNIT_RU]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TODSA_IN]                          INT              DEFAULT ((0)) NOT NULL,
    [COMBINEDTRANSFERORDERLINEDELIVERY] BIGINT           DEFAULT ((0)) NOT NULL,
    [DIMENSIONDEFAULTSHIPFROM]          BIGINT           DEFAULT ((0)) NOT NULL,
    [DIMENSIONDEFAULTSHIPTO]            BIGINT           DEFAULT ((0)) NOT NULL,
    [PURCHPRICE_IN]                     NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                   DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DATAAREAID]                        NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                        INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                         BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                             BIGINT           NOT NULL,
    [ROLWMSRESERVEDSTATUS]              INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_1705LINEIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [TRANSFERID] ASC, [LINENUM] ASC),
    CHECK ([RECID]<>(0))
);

