CREATE TABLE [dbo].[INVENTITEMGROUPITEM] (
    [ITEMID]              NVARCHAR (20) NOT NULL,
    [ITEMDATAAREAID]      NVARCHAR (4)  NOT NULL,
    [ITEMGROUPID]         NVARCHAR (10) NOT NULL,
    [ITEMGROUPDATAAREAID] NVARCHAR (4)  NOT NULL,
    [RECVERSION]          INT           NOT NULL,
    [PARTITION]           BIGINT        NOT NULL,
    [RECID]               BIGINT        NOT NULL,
    CONSTRAINT [I_7051RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC)
);

