CREATE TABLE [dbo].[INVENTITEMLOCATION] (
    [ITEMID]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [COUNTGROUPID]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSSTOREZONEID]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSPICKINGLOCATION]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSLOCATIONIDDEFAULTISSUE]     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSLOCATIONIDDEFAULTRECEIPT]   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTDIMID]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [USEWMSORDER]                   INT              DEFAULT ((0)) NOT NULL,
    [PICKINGLOCATIONREFILLMIN]      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PICKINGLOCATIONMAXQTY]         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [USEEMPTYPALLETLOCATION]        INT              DEFAULT ((0)) NOT NULL,
    [PDSCWPICKINGLOCATIONREFILLMIN] NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSCWPICKINGLOCATIONMAXQTY]    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                    NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                    INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                     BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                         BIGINT           NOT NULL,
    CONSTRAINT [I_659ITEMDIMIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [ITEMID] ASC, [INVENTDIMID] ASC),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_IILOC]
    ON [dbo].[INVENTITEMLOCATION]([INVENTDIMID] ASC)
    INCLUDE([ITEMID], [DATAAREAID]);

