CREATE TABLE [dbo].[INVENTLOCATION] (
    [INVENTLOCATIONID]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NAME]                                 NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [MANUAL]                               INT              DEFAULT ((0)) NOT NULL,
    [EMPTYPALLETLOCATION]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MAXPICKINGROUTEVOLUME]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PICKINGLINETIME]                      INT              DEFAULT ((0)) NOT NULL,
    [MAXPICKINGROUTETIME]                  INT              DEFAULT ((0)) NOT NULL,
    [WMSLOCATIONIDDEFAULTRECEIPT]          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSLOCATIONIDDEFAULTISSUE]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONIDREQMAIN]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [REQREFILL]                            INT              DEFAULT ((0)) NOT NULL,
    [INVENTLOCATIONTYPE]                   INT              DEFAULT ((0)) NOT NULL,
    [INVENTLOCATIONIDQUARANTINE]           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONLEVEL]                  INT              DEFAULT ((0)) NOT NULL,
    [REQCALENDARID]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSAISLENAMEACTIVE]                   INT              DEFAULT ((0)) NOT NULL,
    [WMSRACKNAMEACTIVE]                    INT              DEFAULT ((0)) NOT NULL,
    [WMSRACKFORMAT]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSLEVELNAMEACTIVE]                   INT              DEFAULT ((0)) NOT NULL,
    [WMSLEVELFORMAT]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSPOSITIONNAMEACTIVE]                INT              DEFAULT ((0)) NOT NULL,
    [WMSPOSITIONFORMAT]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [USEWMSORDERS]                         INT              DEFAULT ((0)) NOT NULL,
    [INVENTLOCATIONIDTRANSIT]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VENDACCOUNT]                          NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [BRANCHNUMBER]                         NVARCHAR (13)    DEFAULT ('') NOT NULL,
    [INVENTSITEID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTCOUNTINGGROUP_BR]               INT              DEFAULT ((0)) NOT NULL,
    [CUSTACCOUNT_BR]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTPROFILETYPE_RU]                 INT              DEFAULT ((0)) NOT NULL,
    [INVENTPROFILEID_RU]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONIDGOODSINROUTE_RU]      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WMSLOCATIONIDGOODSINROUTE_RU]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ACTIVITYTYPE_RU]                      NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [NUMBERSEQUENCEGROUP_RU]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETAILWEIGHTEX1]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [FSHSTORE]                             INT              DEFAULT ((0)) NOT NULL,
    [RBODEFAULTWMSPALLETID]                NVARCHAR (18)    DEFAULT ('') NOT NULL,
    [RBODEFAULTWMSLOCATIONID]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RBODEFAULTINVENTPROFILEID_RU]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ALLOWLABORSTANDARDS]                  INT              DEFAULT ((0)) NOT NULL,
    [ALLOWMARKINGRESERVATIONREMOVAL]       INT              DEFAULT ((0)) NOT NULL,
    [CONSOLIDATESHIPATRTW]                 INT              DEFAULT ((0)) NOT NULL,
    [CUSTACCOUNT_HU]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CYCLECOUNTALLOWPALLETMOVE]            INT              DEFAULT ((0)) NOT NULL,
    [DECREMENTLOADLINE]                    INT              DEFAULT ((0)) NOT NULL,
    [DEFAULTKANBANFINISHEDGOODSLOCATION]   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DEFAULTPRODUCTIONFINISHGOODSLOCATION] NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DEFAULTSHIPMAINTENANCELOC]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DEFAULTSTATUSID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PRINTBOLBEFORESHIPCONFIRM]            INT              DEFAULT ((0)) NOT NULL,
    [PRODRESERVEONLYWHSE]                  INT              DEFAULT ((0)) NOT NULL,
    [REMOVEINVENTBLOCKINGONSTATUSCHANGE]   INT              DEFAULT ((0)) NOT NULL,
    [RESERVEATLOADPOST]                    INT              DEFAULT ((0)) NOT NULL,
    [RETAILINVENTNEGFINANCIAL]             INT              DEFAULT ((0)) NOT NULL,
    [RETAILINVENTNEGPHYSICAL]              INT              DEFAULT ((0)) NOT NULL,
    [RETAILWMSLOCATIONIDDEFAULTRETURN]     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETAILWMSPALLETIDDEFAULTRETURN]       NVARCHAR (18)    DEFAULT ('') NOT NULL,
    [UNIQUECHECKDIGITS]                    INT              DEFAULT ((0)) NOT NULL,
    [VENDACCOUNTCUSTOM_RU]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [WAREHOUSEAUTORELEASERESERVATION]      INT              DEFAULT ((0)) NOT NULL,
    [WHSENABLED]                           INT              DEFAULT ((0)) NOT NULL,
    [DEFAULTCONTAINERTYPECODE]             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DEFAULTPRODUCTIONINPUTLOCATION]       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DEFAULTRETURNCREDITONLYLOCATION]      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [WHSRAWMATERIALPOLICY]                 INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]                     DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_MODIFIEDTIME]                     INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]                           NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]                      DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                      INT              DEFAULT ((0)) NOT NULL,
    [CREATEDBY]                            NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [DATAAREAID]                           NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                           INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                            BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                                BIGINT           NOT NULL,
    [ROLWMSELIGIBLE]                       INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDI940]                          INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDI943]                          INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDI944]                          INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDI945]                          INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_158INVENTLOCATIONIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [INVENTLOCATIONID] ASC),
    CHECK ([RECID]<>(0))
);

