CREATE TABLE [dbo].[INVENTTABLEMODULE] (
    [ITEMID]                         NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [MODULETYPE]                     INT              DEFAULT ((0)) NOT NULL,
    [UNITID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PRICE]                          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRICEUNIT]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [MARKUP]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [LINEDISC]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MULTILINEDISC]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENDDISC]                        INT              DEFAULT ((0)) NOT NULL,
    [TAXITEMGROUPID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MARKUPGROUPID]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PRICEDATE]                      DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [PRICEQTY]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ALLOCATEMARKUP]                 INT              DEFAULT ((0)) NOT NULL,
    [OVERDELIVERYPCT]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [UNDERDELIVERYPCT]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SUPPITEMGROUPID]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYBLOCKED]            INT              DEFAULT ((0)) NOT NULL,
    [TAXWITHHOLDITEMGROUPHEADING_TH] BIGINT           DEFAULT ((0)) NOT NULL,
    [TAXWITHHOLDCALCULATE_TH]        INT              DEFAULT ((0)) NOT NULL,
    [MAXIMUMRETAILPRICE_IN]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRICESECCUR_RU]                 NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [MARKUPSECCUR_RU]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PDSPRICINGPRECISION]            INT              DEFAULT ((0)) NOT NULL,
    [TAXGSTRELIEFCATEGORY_MY]        BIGINT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]               DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_MODIFIEDTIME]               INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]                     NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]                DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                INT              DEFAULT ((0)) NOT NULL,
    [CREATEDBY]                      NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                     INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                      BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    CONSTRAINT [I_176ITEMMODULEIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [ITEMID] ASC, [MODULETYPE] ASC),
    CHECK ([RECID]<>(0))
);

