CREATE TABLE [dbo].[INVENTTRANSFERTABLE] (
    [TRANSFERID]                         NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [INVENTLOCATIONIDFROM]               NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTLOCATIONIDTO]                 NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [TRANSFERSTATUS]                     INT            DEFAULT ((0)) NOT NULL,
    [SHIPDATE]                           DATETIME       DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [RECEIVEDATE]                        DATETIME       DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [FROMADDRESSNAME]                    NVARCHAR (100) DEFAULT ('') NOT NULL,
    [TOADDRESSNAME]                      NVARCHAR (100) DEFAULT ('') NOT NULL,
    [AUTORESERVATION]                    INT            DEFAULT ((0)) NOT NULL,
    [DLVMODEID]                          NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [DLVTERMID]                          NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [FREIGHTZONEID]                      NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [FREIGHTSLIPTYPE]                    INT            DEFAULT ((0)) NOT NULL,
    [FROMCONTACTPERSON]                  BIGINT         DEFAULT ((0)) NOT NULL,
    [INVENTLOCATIONIDTRANSIT]            NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [ATPINCLPLANNEDORDERS]               INT            DEFAULT ((0)) NOT NULL,
    [ATPTIMEFENCE]                       INT            DEFAULT ((0)) NOT NULL,
    [DELIVERYDATECONTROLTYPE]            INT            DEFAULT ((0)) NOT NULL,
    [TOCONTACTPERSON]                    BIGINT         DEFAULT ((0)) NOT NULL,
    [ATPAPPLYSUPPLYTIMEFENCE]            INT            DEFAULT ((0)) NOT NULL,
    [ATPAPPLYDEMANDTIMEFENCE]            INT            DEFAULT ((0)) NOT NULL,
    [ATPBACKWARDDEMANDTIMEFENCE]         INT            DEFAULT ((0)) NOT NULL,
    [ATPBACKWARDSUPPLYTIMEFENCE]         INT            DEFAULT ((0)) NOT NULL,
    [FROMPOSTALADDRESS]                  BIGINT         DEFAULT ((0)) NOT NULL,
    [TOPOSTALADDRESS]                    BIGINT         DEFAULT ((0)) NOT NULL,
    [STATPROCID]                         NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [PORT]                               NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [TRANSPORT]                          NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [TRANSACTIONCODE]                    NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [TRANSFERTYPE_IN]                    INT            DEFAULT ((0)) NOT NULL,
    [TRPACKINGSLIPAUTONUMBERING_LT]      INT            DEFAULT ((0)) NOT NULL,
    [INVENTPROFILETYPE_RU]               INT            DEFAULT ((0)) NOT NULL,
    [INVENTPROFILEID_RU]                 NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [INVENTPROFILEUSERELATED_RU]         INT            DEFAULT ((0)) NOT NULL,
    [DRIVERCONTACT_RU]                   NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [TRANSPORTINVOICETYPE_RU]            INT            DEFAULT ((0)) NOT NULL,
    [CARGODESCRIPTION_RU]                NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [CARGOPACKING_RU]                    NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [RETAILREPLENISHREFTABLEID]          INT            DEFAULT ((0)) NOT NULL,
    [RETAILREPLENISHREFRECID]            BIGINT         DEFAULT ((0)) NOT NULL,
    [RETAILRETAILSTATUSTYPE]             INT            DEFAULT ((0)) NOT NULL,
    [CARRIERCODE_RU]                     NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [CARRIERTYPE_RU]                     INT            DEFAULT ((0)) NOT NULL,
    [CURRENCYCODE_RU]                    NVARCHAR (3)   DEFAULT ('') NOT NULL,
    [DELIVERYDATE_RU]                    DATETIME       DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DRIVER_RU]                          NVARCHAR (25)  DEFAULT ('') NOT NULL,
    [DRIVERNAME_RU]                      NVARCHAR (60)  DEFAULT ('') NOT NULL,
    [DRIVINGLICENSENUM_RU]               NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]        DATETIME       DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [INTRASTATSPECMOVE_CZ]               NVARCHAR (2)   DEFAULT ('') NOT NULL,
    [INVENTPROFILEIDTO_RU]               NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [LADINGPOSTALADDRESS_RU]             BIGINT         DEFAULT ((0)) NOT NULL,
    [LICENSECARDNUM_RU]                  NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [LICENSECARDREGNUM_RU]               NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [LICENSECARDSERIES_RU]               NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [LICENSECARDTYPE_RU]                 INT            DEFAULT ((0)) NOT NULL,
    [PARTYACCOUNTNUM_RU]                 NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [PARTYAGREEMENTHEADEREXT_RU]         BIGINT         DEFAULT ((0)) NOT NULL,
    [PDSOVERRIDEFEFO]                    INT            DEFAULT ((0)) NOT NULL,
    [PRICEGROUPID_RU]                    NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [TRANSFERTYPE_RU]                    INT            DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONDOCUMENT]             BIGINT         DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONPAYER_RU]             NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [TRANSPORTATIONPAYERTYPE_RU]         INT            DEFAULT ((0)) NOT NULL,
    [TRANSPORTATIONTYPE_RU]              NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [UNLADINGPOSTALADDRESS_RU]           BIGINT         DEFAULT ((0)) NOT NULL,
    [VEHICLEMODEL_RU]                    NVARCHAR (10)  DEFAULT ('') NOT NULL,
    [VEHICLEPLATENUM_RU]                 NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [WAYBILLNUM_RU]                      NVARCHAR (20)  DEFAULT ('') NOT NULL,
    [SHOULDPOSTEXPENSEAMTTOINVENTORY_IN] INT            DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                    DATETIME       DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DATAAREAID]                         NVARCHAR (4)   DEFAULT ('dat') NOT NULL,
    [RECVERSION]                         INT            DEFAULT ((1)) NOT NULL,
    [PARTITION]                          BIGINT         DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                              BIGINT         NOT NULL,
    [ROLWMSCONFIRMSTATUS]                INT            DEFAULT ((0)) NOT NULL,
    [ROLWMSRESERVEDSTATUS]               INT            DEFAULT ((0)) NOT NULL,
    [ROLWMSSENDSTATUS]                   INT            DEFAULT ((0)) NOT NULL,
    [EDITRANSFERSTATUS]                  INT            DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_1704TRANSFERIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [TRANSFERID] ASC),
    CHECK ([RECID]<>(0))
);

