CREATE TABLE [dbo].[INVENTTRANSORIGIN] (
    [INVENTTRANSID]     NVARCHAR (20) DEFAULT ('') NOT NULL,
    [REFERENCECATEGORY] INT           DEFAULT ((0)) NOT NULL,
    [REFERENCEID]       NVARCHAR (20) DEFAULT ('') NOT NULL,
    [ITEMID]            NVARCHAR (20) DEFAULT ('') NOT NULL,
    [ITEMINVENTDIMID]   NVARCHAR (20) DEFAULT ('') NOT NULL,
    [PARTY]             BIGINT        DEFAULT ((0)) NOT NULL,
    [DATAAREAID]        NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]        INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]         BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    CONSTRAINT [I_2938RECID] PRIMARY KEY CLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

