CREATE TABLE [dbo].[INVENTLOCATIONLOGISTICSLOCATIONROLE] (
    [LOCATIONLOGISTICSLOCATION] BIGINT DEFAULT ((0)) NOT NULL,
    [LOCATIONROLE]              BIGINT DEFAULT ((0)) NOT NULL,
    [RECVERSION]                INT    DEFAULT ((1)) NOT NULL,
    [PARTITION]                 BIGINT DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                     BIGINT NOT NULL,
    CONSTRAINT [I_7517RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

