CREATE TABLE [dbo].[INVENTTRANSORIGINPURCHLINE] (
    [PURCHLINEINVENTTRANSID] NVARCHAR (20) NOT NULL,
    [INVENTTRANSORIGIN]      BIGINT        NOT NULL,
    [PURCHLINEDATAAREAID]    NVARCHAR (4)  NOT NULL,
    [RECVERSION]             INT           NOT NULL,
    [PARTITION]              BIGINT        NOT NULL,
    [RECID]                  BIGINT        NOT NULL,
    CONSTRAINT [I_2989RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC)
);

