CREATE TABLE [dbo].[L6_SF_SalesOrder_Incremental] (
    [SALESID]                               NVARCHAR (20)    NOT NULL,
    [SALESNAME]                             NVARCHAR (60)    NOT NULL,
    [RESERVATION]                           INT              NOT NULL,
    [CUSTACCOUNT]                           NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]                        NVARCHAR (20)    NOT NULL,
    [DELIVERYDATE]                          DATETIME         NOT NULL,
    [URL]                                   NVARCHAR (255)   NOT NULL,
    [PURCHORDERFORMNUM]                     NVARCHAR (20)    NOT NULL,
    [SALESGROUP]                            NVARCHAR (10)    NOT NULL,
    [FREIGHTSLIPTYPE]                       INT              NOT NULL,
    [DOCUMENTSTATUS]                        INT              NOT NULL,
    [INTERCOMPANYORIGINALSALESID]           NVARCHAR (20)    NOT NULL,
    [CURRENCYCODE]                          NVARCHAR (3)     NOT NULL,
    [PAYMENT]                               NVARCHAR (10)    NOT NULL,
    [CASHDISC]                              NVARCHAR (10)    NOT NULL,
    [TAXGROUP]                              NVARCHAR (10)    NOT NULL,
    [LINEDISC]                              NVARCHAR (10)    NOT NULL,
    [CUSTGROUP]                             NVARCHAR (10)    NOT NULL,
    [DISCPERCENT]                           NUMERIC (32, 16) NOT NULL,
    [INTERCOMPANYORIGINALCUSTACCOUNT]       NVARCHAR (20)    NOT NULL,
    [PRICEGROUPID]                          NVARCHAR (10)    NOT NULL,
    [MULTILINEDISC]                         NVARCHAR (10)    NOT NULL,
    [ENDDISC]                               NVARCHAR (10)    NOT NULL,
    [CUSTOMERREF]                           NVARCHAR (60)    NOT NULL,
    [COUNTYORIGDEST]                        NVARCHAR (10)    NOT NULL,
    [LISTCODE]                              INT              NOT NULL,
    [DLVTERM]                               NVARCHAR (10)    NOT NULL,
    [DLVMODE]                               NVARCHAR (10)    NOT NULL,
    [PURCHID]                               NVARCHAR (20)    NOT NULL,
    [SALESSTATUS]                           INT              NOT NULL,
    [MARKUPGROUP]                           NVARCHAR (10)    NOT NULL,
    [SALESTYPE]                             INT              NOT NULL,
    [SALESPOOLID]                           NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILE]                        NVARCHAR (10)    NOT NULL,
    [TRANSACTIONCODE]                       NVARCHAR (10)    NOT NULL,
    [INTERCOMPANYAUTOCREATEORDERS]          INT              NOT NULL,
    [INTERCOMPANYDIRECTDELIVERY]            INT              NOT NULL,
    [INTERCOMPANYDIRECTDELIVERYORIG]        INT              NOT NULL,
    [SETTLEVOUCHER]                         INT              NOT NULL,
    [ENTERPRISENUMBER]                      NVARCHAR (50)    NOT NULL,
    [INTERCOMPANYALLOWINDIRECTCREATION]     INT              NOT NULL,
    [INTERCOMPANYALLOWINDIRECTCREATIONORIG] INT              NOT NULL,
    [DELIVERYNAME]                          NVARCHAR (100)   NOT NULL,
    [ONETIMECUSTOMER]                       INT              NOT NULL,
    [COVSTATUS]                             INT              NOT NULL,
    [COMMISSIONGROUP]                       NVARCHAR (10)    NOT NULL,
    [PAYMENTSCHED]                          NVARCHAR (30)    NOT NULL,
    [INTERCOMPANYORIGIN]                    INT              NOT NULL,
    [EMAIL]                                 NVARCHAR (80)    NOT NULL,
    [FREIGHTZONE]                           NVARCHAR (10)    NOT NULL,
    [RETURNITEMNUM]                         NVARCHAR (10)    NOT NULL,
    [CASHDISCPERCENT]                       NUMERIC (32, 16) NOT NULL,
    [CONTACTPERSONID]                       NVARCHAR (20)    NOT NULL,
    [DEADLINE]                              DATETIME         NOT NULL,
    [PROJID]                                NVARCHAR (20)    NOT NULL,
    [INVENTLOCATIONID]                      NVARCHAR (10)    NOT NULL,
    [ADDRESSREFTABLEID]                     INT              NOT NULL,
    [VATNUM]                                NVARCHAR (20)    NOT NULL,
    [PORT]                                  NVARCHAR (10)    NOT NULL,
    [INCLTAX]                               INT              NOT NULL,
    [EINVOICELINESPEC]                      INT              NOT NULL,
    [NUMBERSEQUENCEGROUP]                   NVARCHAR (10)    NOT NULL,
    [FIXEDEXCHRATE]                         NUMERIC (32, 16) NOT NULL,
    [LANGUAGEID]                            NVARCHAR (7)     NOT NULL,
    [AUTOSUMMARYMODULETYPE]                 INT              NOT NULL,
    [GIROTYPE]                              INT              NOT NULL,
    [SALESORIGINID]                         NVARCHAR (10)    NOT NULL,
    [ESTIMATE]                              NUMERIC (32, 16) NOT NULL,
    [TRANSPORT]                             NVARCHAR (10)    NOT NULL,
    [PAYMMODE]                              NVARCHAR (10)    NOT NULL,
    [PAYMSPEC]                              NVARCHAR (10)    NOT NULL,
    [FIXEDDUEDATE]                          DATETIME         NOT NULL,
    [EXPORTREASON]                          NVARCHAR (30)    NOT NULL,
    [STATPROCID]                            NVARCHAR (10)    NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]            NVARCHAR (140)   NOT NULL,
    [INTERCOMPANYCOMPANYID]                 NVARCHAR (4)     NOT NULL,
    [INTERCOMPANYPURCHID]                   NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYORDER]                     INT              NOT NULL,
    [DLVREASON]                             NVARCHAR (10)    NOT NULL,
    [QUOTATIONID]                           NVARCHAR (20)    NOT NULL,
    [RECEIPTDATEREQUESTED]                  DATETIME         NOT NULL,
    [RECEIPTDATECONFIRMED]                  DATETIME         NOT NULL,
    [SHIPPINGDATEREQUESTED]                 DATETIME         NOT NULL,
    [SHIPPINGDATECONFIRMED]                 DATETIME         NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]            NVARCHAR (10)    NOT NULL,
    [EINVOICEACCOUNTCODE]                   NVARCHAR (35)    NOT NULL,
    [ITEMTAGGING]                           INT              NOT NULL,
    [CASETAGGING]                           INT              NOT NULL,
    [PALLETTAGGING]                         INT              NOT NULL,
    [ADDRESSREFRECID]                       BIGINT           NOT NULL,
    [CUSTINVOICEID]                         NVARCHAR (20)    NOT NULL,
    [INVENTSITEID]                          NVARCHAR (10)    NOT NULL,
    [DEFAULTDIMENSION]                      BIGINT           NOT NULL,
    [CREDITCARDCUSTREFID]                   BIGINT           NOT NULL,
    [SHIPCARRIERACCOUNT]                    NVARCHAR (25)    NOT NULL,
    [SHIPCARRIERID]                         NVARCHAR (10)    NOT NULL,
    [SHIPCARRIERFUELSURCHARGE]              INT              NOT NULL,
    [SHIPCARRIERBLINDSHIPMENT]              INT              NOT NULL,
    [SHIPCARRIERDELIVERYCONTACT]            NVARCHAR (60)    NOT NULL,
    [CREDITCARDAPPROVALAMOUNT]              NUMERIC (32, 16) NOT NULL,
    [CREDITCARDAUTHORIZATION]               NVARCHAR (20)    NOT NULL,
    [RETURNDEADLINE]                        DATETIME         NOT NULL,
    [RETURNREPLACEMENTID]                   NVARCHAR (20)    NOT NULL,
    [RETURNSTATUS]                          INT              NOT NULL,
    [RETURNREASONCODEID]                    NVARCHAR (10)    NOT NULL,
    [CREDITCARDAUTHORIZATIONERROR]          INT              NOT NULL,
    [SHIPCARRIERACCOUNTCODE]                NVARCHAR (20)    NOT NULL,
    [RETURNREPLACEMENTCREATED]              INT              NOT NULL,
    [SHIPCARRIERDLVTYPE]                    INT              NOT NULL,
    [DELIVERYDATECONTROLTYPE]               INT              NOT NULL,
    [SHIPCARRIEREXPEDITEDSHIPMENT]          INT              NOT NULL,
    [SHIPCARRIERRESIDENTIAL]                INT              NOT NULL,
    [MATCHINGAGREEMENT]                     BIGINT           NOT NULL,
    [SYSTEMENTRYSOURCE]                     INT              NOT NULL,
    [SYSTEMENTRYCHANGEPOLICY]               BIGINT           NOT NULL,
    [MANUALENTRYCHANGEPOLICY]               BIGINT           NOT NULL,
    [DELIVERYPOSTALADDRESS]                 BIGINT           NOT NULL,
    [SHIPCARRIERPOSTALADDRESS]              BIGINT           NOT NULL,
    [SHIPCARRIERNAME]                       NVARCHAR (100)   NOT NULL,
    [WORKERSALESTAKER]                      BIGINT           NOT NULL,
    [SOURCEDOCUMENTHEADER]                  BIGINT           NOT NULL,
    [BANKDOCUMENTTYPE]                      INT              NOT NULL,
    [SALESUNITID]                           NVARCHAR (20)    NOT NULL,
    [SMMSALESAMOUNTTOTAL]                   NUMERIC (32, 16) NOT NULL,
    [SMMCAMPAIGNID]                         NVARCHAR (10)    NOT NULL,
    [CUSTOMSEXPORTORDER_IN]                 INT              NOT NULL,
    [CUSTOMSSHIPPINGBILL_IN]                INT              NOT NULL,
    [TDSGROUP_IN]                           NVARCHAR (10)    NOT NULL,
    [TCSGROUP_IN]                           NVARCHAR (10)    NOT NULL,
    [NATUREOFASSESSEE_IN]                   INT              NOT NULL,
    [CONSTARGET_JP]                         INT              NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]           DATETIME         NOT NULL,
    [UNITEDVATINVOICE_LT]                   INT              NOT NULL,
    [INTRASTATADDVALUE_LV]                  NUMERIC (32, 16) NOT NULL,
    [INVOICEREGISTER_LT]                    INT              NOT NULL,
    [PACKINGSLIPREGISTER_LT]                INT              NOT NULL,
    [BANKACCOUNT_LV]                        NVARCHAR (10)    NOT NULL,
    [CASHDISCBASEDATE]                      DATETIME         NOT NULL,
    [CASHDISCBASEDAYS]                      INT              NOT NULL,
    [CREDITNOTEREASONCODE]                  BIGINT           NOT NULL,
    [CURBANKACCOUNT_LV]                     NVARCHAR (10)    NOT NULL,
    [CUSTBANKACCOUNT_LV]                    NVARCHAR (10)    NOT NULL,
    [DAXINTEGRATIONID]                      UNIQUEIDENTIFIER NOT NULL,
    [DIRECTDEBITMANDATE]                    BIGINT           NOT NULL,
    [FISCALDOCTYPE_PL]                      INT              NOT NULL,
    [MCRORDERSTOPPED]                       INT              NOT NULL,
    [PDSBATCHATTRIBAUTORES]                 INT              NOT NULL,
    [PDSCUSTREBATEGROUPID]                  NVARCHAR (20)    NOT NULL,
    [PDSREBATEPROGRAMTMAGROUP]              NVARCHAR (10)    NOT NULL,
    [RELEASESTATUS]                         INT              NOT NULL,
    [TAXPERIODPAYMENTCODE_PL]               NVARCHAR (10)    NOT NULL,
    [TRANSPORTATIONDOCUMENT]                BIGINT           NOT NULL,
    [WORKERSALESRESPONSIBLE]                BIGINT           NOT NULL,
    [RETAILCHANNELTABLE]                    BIGINT           NOT NULL,
    [MODIFIEDDATETIME]                      DATETIME         NOT NULL,
    [DEL_MODIFIEDTIME]                      INT              NOT NULL,
    [MODIFIEDBY]                            NVARCHAR (8)     NOT NULL,
    [MODIFIEDTRANSACTIONID]                 BIGINT           NOT NULL,
    [CREATEDDATETIME]                       DATETIME         NOT NULL,
    [DEL_CREATEDTIME]                       INT              NOT NULL,
    [CREATEDBY]                             NVARCHAR (8)     NOT NULL,
    [CREATEDTRANSACTIONID]                  BIGINT           NOT NULL,
    [DATAAREAID]                            NVARCHAR (4)     NOT NULL,
    [RECVERSION]                            INT              NOT NULL,
    [PARTITION]                             BIGINT           NOT NULL,
    [RECID]                                 BIGINT           NOT NULL,
    [VSIDELIVERYADDRESSRECID]               BIGINT           NOT NULL,
    [ROLCREDITHOLDRELEASED]                 INT              NOT NULL,
    [ROLCROSSDOCKDELIVERYNAME]              NVARCHAR (100)   NOT NULL,
    [ROLCROSSDOCKDELIVERYPOSTALADDRESS]     BIGINT           NOT NULL,
    [ROLORDERCREDITHOLDSTOPPED]             INT              NOT NULL,
    [ROLPROFORMA]                           INT              NOT NULL,
    [ROLRELEASEDBY]                         NVARCHAR (10)    NOT NULL,
    [ROLRELEASEDON]                         DATETIME         NOT NULL,
    [ROLRELEASEDONTZID]                     INT              NOT NULL,
    [ROLWMSARN]                             NVARCHAR (15)    NOT NULL,
    [ROLWMSCONFIRMSTATUS]                   INT              NOT NULL,
    [ROLWMSRESERVEDSTATUS]                  INT              NOT NULL,
    [ROLEDIREVIEWED]                        INT              NOT NULL,
    [VSIMARKFORADDRESSRECID]                BIGINT           NOT NULL,
    [RSMRFLI_EDIDUNSNUMBER]                 NVARCHAR (50)    NOT NULL,
    [PALLETTAGGING1]                        INT              NOT NULL,
    [RSMREBILLORDER]                        INT              NOT NULL,
    [RSMRETURNDISPOSITIONCODEID]            NVARCHAR (10)    NOT NULL,
    [RSMWMSLOCATIONID]                      NVARCHAR (10)    NOT NULL,
    [SalesOrderStatus]                      NVARCHAR (20)    NOT NULL,
    [SalesOrderType]                        NVARCHAR (20)    NOT NULL,
    [SalesDocumentStatus]                   NVARCHAR (50)    NOT NULL,
    [WarehouseNumber]                       NVARCHAR (10)    NULL,
    [WarehouseName]                         NVARCHAR (60)    NULL,
    [shiptodeliveryname]                    NVARCHAR (100)   NOT NULL,
    [shiptoadd1]                            NVARCHAR (250)   NULL,
    [shiptoadd2]                            NVARCHAR (250)   NULL,
    [shiptoadd3]                            VARCHAR (1)      NOT NULL,
    [shiptocity]                            NVARCHAR (60)    NOT NULL,
    [shiptostate]                           NVARCHAR (10)    NOT NULL,
    [shiptozip]                             NVARCHAR (10)    NOT NULL,
    [shiptocountry]                         NVARCHAR (10)    NOT NULL,
    [carrierid]                             NVARCHAR (10)    NULL,
    [carrierdesc]                           NVARCHAR (60)    NULL,
    [CrossDockCity]                         NVARCHAR (60)    NULL,
    [CrossDockName]                         NVARCHAR (100)   NOT NULL,
    [CrossDockState]                        NVARCHAR (10)    NULL,
    [CrossDockZipCode]                      NVARCHAR (10)    NULL,
    [DeliveryTerms]                         NVARCHAR (10)    NOT NULL,
    [DeliveryMode]                          NVARCHAR (10)    NOT NULL,
    [InvoiceDate]                           DATETIME         NULL,
    [InvoiceNum]                            NVARCHAR (20)    NULL,
    [ShipAccount]                           NVARCHAR (20)    NOT NULL,
    [CustomerOrderDate]                     DATETIME         NOT NULL,
    [CreditHoldStatus]                      VARCHAR (8)      NOT NULL,
    [SOReceiptDateRequested]                DATETIME         NULL,
    [WmsConfirmStatus]                      INT              NOT NULL
);

