CREATE TABLE [dbo].[L6_SF_Customer_Incremental] (
    [BrokerId]             NVARCHAR (20)  NULL,
    [BrokerName]           NVARCHAR (100) NULL,
    [Name]                 NVARCHAR (100) NOT NULL,
    [invoiceAccount]       NVARCHAR (20)  NOT NULL,
    [KnownAs]              NVARCHAR (100) NOT NULL,
    [LegalEntity]          NVARCHAR (4)   NULL,
    [AccountNum]           NVARCHAR (20)  NOT NULL,
    [LocationName]         NVARCHAR (60)  NULL,
    [City]                 NVARCHAR (60)  NULL,
    [State]                NVARCHAR (10)  NULL,
    [Zip]                  NVARCHAR (10)  NULL,
    [Street]               NVARCHAR (250) NULL,
    [CountryRegionId]      NVARCHAR (10)  NULL,
    [CountryName]          NVARCHAR (255) NULL,
    [DlvTerm]              NVARCHAR (10)  NOT NULL,
    [DlvMode]              NVARCHAR (10)  NOT NULL,
    [InsideAccountManager] NVARCHAR (100) NULL,
    [ChainCode]            NVARCHAR (20)  NOT NULL,
    [ChainName]            NVARCHAR (60)  NULL,
    [LineOfBusinessId]     NVARCHAR (10)  NOT NULL,
    [LobName]              NVARCHAR (60)  NULL,
    [ModifiedDateTime]     DATETIME       NOT NULL,
    [DivisionCode]         NVARCHAR (20)  NOT NULL,
    [DivisionName]         NVARCHAR (60)  NULL,
    [Warehouse Code]       NVARCHAR (10)  NOT NULL,
    [Warehouse Name]       NVARCHAR (60)  NULL,
    [Account Manager]      NVARCHAR (100) NULL,
    [ChannelCode]          NVARCHAR (30)  NULL,
    [Channel Name]         NVARCHAR (60)  NULL,
    [Sales District]       NVARCHAR (60)  NULL
);

