CREATE TABLE [dbo].[L6_SF_Product_Incremental] (
    [DisplayProductNumber]         NVARCHAR (70)    NOT NULL,
    [Name]                         NVARCHAR (60)    NOT NULL,
    [GrossDepth]                   NUMERIC (32, 16) NOT NULL,
    [GrossHeight]                  NUMERIC (32, 16) NOT NULL,
    [GrossWidth]                   NUMERIC (32, 16) NOT NULL,
    [NetWeight]                    NUMERIC (32, 16) NOT NULL,
    [StandardPalletQuantity]       NUMERIC (32, 16) NOT NULL,
    [PdsShelfLife]                 INT              NOT NULL,
    [UnitVolume]                   NUMERIC (32, 16) NOT NULL,
    [TareWeight]                   NUMERIC (32, 16) NOT NULL,
    [QtyPerLayer]                  NUMERIC (32, 16) NOT NULL,
    [rolCartonMarking]             NVARCHAR (70)    NOT NULL,
    [rolCartonMarkingsInner]       NVARCHAR (70)    NOT NULL,
    [rolShipConditionsSell]        NVARCHAR (100)   NOT NULL,
    [rolShipConditionsPurchase]    NVARCHAR (100)   NOT NULL,
    [Intracode]                    NVARCHAR (15)    NOT NULL,
    [CreatedBy]                    NVARCHAR (8)     NOT NULL,
    [CreatedDatetime]              DATETIME         NOT NULL,
    [ModifiedBy]                   NVARCHAR (8)     NOT NULL,
    [ModifiedDatetime]             DATETIME         NOT NULL,
    [SupplierEngagementSpecialist] NVARCHAR (100)   NOT NULL,
    [BuyerName]                    NVARCHAR (60)    NULL,
    [BuyerId]                      NVARCHAR (10)    NULL,
    [StoppedPurch]                 VARCHAR (3)      NOT NULL,
    [StoppedInvent]                VARCHAR (3)      NOT NULL,
    [StoppedSales]                 VARCHAR (3)      NOT NULL,
    [PackType]                     NVARCHAR (10)    NULL,
    [Category1]                    NVARCHAR (254)   NULL,
    [Category2]                    NVARCHAR (254)   NULL,
    [Pack1]                        NUMERIC (38, 11) NOT NULL,
    [Pack2]                        NUMERIC (38, 11) NOT NULL,
    [StandardPackQty]              NUMERIC (38, 6)  NOT NULL,
    [UnitDepth]                    NUMERIC (32, 16) NULL,
    [UnitHeight]                   NUMERIC (32, 16) NULL,
    [UnitWidth]                    NUMERIC (32, 16) NULL,
    [DrainedWeight]                NUMERIC (32, 16) NULL,
    [UPC]                          NVARCHAR (50)    NULL,
    [GTIN]                         NVARCHAR (50)    NULL,
    [Discontinued]                 VARCHAR (3)      NULL,
    [UnitType]                     NVARCHAR (50)    NULL,
    [BlockConfig]                  NUMERIC (32, 16) NULL,
    [StackConfig]                  NUMERIC (38, 6)  NULL,
    [GrossWeight]                  NUMERIC (32, 16) NULL,
    [BrandNum]                     NVARCHAR (30)    NULL,
    [BrandName]                    NVARCHAR (60)    NULL,
    [FreightClass]                 NVARCHAR (50)    NULL,
    [SubItemId]                    NVARCHAR (70)    NULL,
    [SubstituteName]               NVARCHAR (60)    NULL,
    [Store_temp]                   VARCHAR (32)     NULL
);

