CREATE TABLE [dbo].[LEDGERJOURNALTABLE] (
    [JOURNALNUM]                    NVARCHAR (10)    NOT NULL,
    [NAME]                          NVARCHAR (60)    NOT NULL,
    [LOG]                           NVARCHAR (255)   NOT NULL,
    [JOURNALTYPE]                   INT              NOT NULL,
    [WORKFLOWAPPROVALSTATUS]        INT              NOT NULL,
    [SYSTEMBLOCKED]                 INT              NOT NULL,
    [PAYMENTSGENERATED_IT]          INT              NOT NULL,
    [USERBLOCKID]                   NVARCHAR (8)     NOT NULL,
    [REJECTEDBY]                    NVARCHAR (8)     NOT NULL,
    [REPORTEDASREADYBY]             NVARCHAR (8)     NOT NULL,
    [JOURNALNAME]                   NVARCHAR (10)    NOT NULL,
    [POSTED]                        INT              NOT NULL,
    [SESSIONLOGINDATETIME]          DATETIME         NOT NULL,
    [SESSIONLOGINDATETIMETZID]      INT              NOT NULL,
    [OFFSETACCOUNTTYPE]             INT              NOT NULL,
    [INUSEBY]                       NVARCHAR (8)     NOT NULL,
    [GROUPBLOCKID]                  NVARCHAR (10)    NOT NULL,
    [ORIGINALJOURNALNUM]            NVARCHAR (10)    NOT NULL,
    [CURRENCYCODE]                  NVARCHAR (3)     NOT NULL,
    [FIXEDEXCHRATE]                 INT              NOT NULL,
    [DETAILSUMMARYPOSTING]          INT              NOT NULL,
    [DOCUMENTNUM]                   NVARCHAR (20)    NOT NULL,
    [EXCHRATESECONDARY]             NUMERIC (32, 16) NOT NULL,
    [EXCHRATE]                      NUMERIC (32, 16) NOT NULL,
    [EUROTRIANGULATION]             INT              NOT NULL,
    [FIXEDOFFSETACCOUNT]            INT              NOT NULL,
    [JOURNALTOTALCREDIT]            NUMERIC (32, 16) NOT NULL,
    [JOURNALTOTALDEBIT]             NUMERIC (32, 16) NOT NULL,
    [JOURNALTOTALOFFSETBALANCE]     NUMERIC (32, 16) NOT NULL,
    [REMOVELINEAFTERPOSTING]        INT              NOT NULL,
    [CURRENTOPERATIONSTAX]          INT              NOT NULL,
    [LEDGERJOURNALINCLTAX]          INT              NOT NULL,
    [ORIGINALCOMPANY]               NVARCHAR (4)     NOT NULL,
    [SESSIONID]                     INT              NOT NULL,
    [BANKREMITTANCETYPE]            INT              NOT NULL,
    [BANKACCOUNTID]                 NVARCHAR (10)    NOT NULL,
    [PROTESTSETTLEDBILL]            INT              NOT NULL,
    [JOURNALBALANCE]                NUMERIC (32, 16) NOT NULL,
    [ENDBALANCE]                    NUMERIC (32, 16) NOT NULL,
    [CUSTVENDNEGINSTPROTESTPROCESS] INT              NOT NULL,
    [VOUCHERALLOCATEDATPOSTING]     INT              NOT NULL,
    [NUMOFLINES]                    INT              NOT NULL,
    [LINESLIMITBEFOREDISTRIBUTION]  INT              NOT NULL,
    [POSTEDDATETIME]                DATETIME         NOT NULL,
    [POSTEDDATETIMETZID]            INT              NOT NULL,
    [REVERSEENTRY]                  INT              NOT NULL,
    [REVERSEDATE]                   DATETIME         NOT NULL,
    [DEFAULTDIMENSION]              BIGINT           NOT NULL,
    [OFFSETLEDGERDIMENSION]         BIGINT           NOT NULL,
    [APPROVER]                      BIGINT           NOT NULL,
    [NUMBERSEQUENCETABLE]           BIGINT           NOT NULL,
    [ASSETTRANSFERTYPE_LT]          INT              NOT NULL,
    [RETAILSTATEMENTID]             NVARCHAR (20)    NOT NULL,
    [TAXOBLIGATIONCOMPANY]          INT              NOT NULL,
    [MODIFIEDBY]                    NVARCHAR (8)     NOT NULL,
    [CREATEDBY]                     NVARCHAR (8)     NOT NULL,
    [DATAAREAID]                    NVARCHAR (4)     NOT NULL,
    [RECVERSION]                    INT              NOT NULL,
    [PARTITION]                     BIGINT           NOT NULL,
    [RECID]                         BIGINT           NOT NULL,
    CONSTRAINT [I_211TYPENUMIDX] PRIMARY KEY NONCLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [JOURNALNUM] ASC)
);

