CREATE TABLE [dbo].[LEDGERJOURNALTRANS] (
    [JOURNALNUM]                        NVARCHAR (10)    NOT NULL,
    [LINENUM]                           NUMERIC (32, 16) NOT NULL,
    [ACCOUNTTYPE]                       INT              NOT NULL,
    [COMPANY]                           NVARCHAR (4)     NOT NULL,
    [TXT]                               NVARCHAR (60)    NOT NULL,
    [AMOUNTCURDEBIT]                    NUMERIC (32, 16) NOT NULL,
    [CURRENCYCODE]                      NVARCHAR (3)     NOT NULL,
    [EXCHRATE]                          NUMERIC (32, 16) NOT NULL,
    [TAXGROUP]                          NVARCHAR (10)    NOT NULL,
    [CASHDISCPERCENT]                   NUMERIC (32, 16) NOT NULL,
    [QTY]                               NUMERIC (32, 16) NOT NULL,
    [BANKNEGINSTRECIPIENTNAME]          NVARCHAR (60)    NOT NULL,
    [ENTERPRISENUMBER]                  NVARCHAR (50)    NOT NULL,
    [PRICE]                             NUMERIC (32, 16) NOT NULL,
    [SETTLEVOUCHER]                     INT              NOT NULL,
    [POSTINGPROFILE]                    NVARCHAR (10)    NOT NULL,
    [VOUCHER]                           NVARCHAR (20)    NOT NULL,
    [AMOUNTCURCREDIT]                   NUMERIC (32, 16) NOT NULL,
    [PAYMENTSTATUS]                     INT              NOT NULL,
    [CASHDISCAMOUNT]                    NUMERIC (32, 16) NOT NULL,
    [ACKNOWLEDGEMENTDATE]               DATETIME         NOT NULL,
    [VENDTRANSID]                       BIGINT           NOT NULL,
    [CUSTTRANSID]                       BIGINT           NOT NULL,
    [REMAINAMOUNT]                      NUMERIC (32, 16) NOT NULL,
    [TAXCODE]                           NVARCHAR (10)    NOT NULL,
    [TAX1099RECID]                      BIGINT           NOT NULL,
    [BANKDEPOSITVOUCHER]                INT              NOT NULL,
    [PAYMREFERENCE]                     NVARCHAR (20)    NOT NULL,
    [BANKDEPOSITNUM]                    NVARCHAR (20)    NOT NULL,
    [PAYMSPEC]                          NVARCHAR (10)    NOT NULL,
    [PAYMMODE]                          NVARCHAR (10)    NOT NULL,
    [MARKEDINVOICE]                     NVARCHAR (20)    NOT NULL,
    [OFFSETACCOUNTTYPE]                 INT              NOT NULL,
    [BANKTRANSTYPE]                     NVARCHAR (10)    NOT NULL,
    [OFFSETCOMPANY]                     NVARCHAR (4)     NOT NULL,
    [OFFSETTXT]                         NVARCHAR (60)    NOT NULL,
    [TAX1099AMOUNT]                     NUMERIC (32, 16) NOT NULL,
    [PAYMENTNOTES]                      NVARCHAR (1000)  NOT NULL,
    [MARKEDINVOICERECID]                BIGINT           NOT NULL,
    [FOREIGNVOUCHER]                    NVARCHAR (20)    NOT NULL,
    [FOREIGNCOMPANY]                    NVARCHAR (4)     NOT NULL,
    [TRANSFERRED]                       INT              NOT NULL,
    [CANCEL]                            INT              NOT NULL,
    [NOEDIT]                            INT              NOT NULL,
    [INVISIBLE]                         INT              NOT NULL,
    [TRANSDATE]                         DATETIME         NOT NULL,
    [TRANSACTIONTYPE]                   INT              NOT NULL,
    [DOCUMENTDATE]                      DATETIME         NOT NULL,
    [DOCUMENTNUM]                       NVARCHAR (20)    NOT NULL,
    [APPROVED]                          INT              NOT NULL,
    [PAYMID]                            NVARCHAR (200)   NOT NULL,
    [FREQVALUE]                         INT              NOT NULL,
    [FREQCODE]                          INT              NOT NULL,
    [DUE]                               DATETIME         NOT NULL,
    [DATECASHDISC]                      DATETIME         NOT NULL,
    [TRANSFERREDBY]                     NVARCHAR (8)     NOT NULL,
    [LOADINGDATE]                       DATETIME         NOT NULL,
    [FILECREATED]                       DATETIME         NOT NULL,
    [PAYMENTACCOUNT]                    NVARCHAR (10)    NOT NULL,
    [INVOICE]                           NVARCHAR (20)    NOT NULL,
    [TRANSFERREDTO]                     NVARCHAR (10)    NOT NULL,
    [TRANSFER]                          INT              NOT NULL,
    [LASTTRANSFERRED]                   DATETIME         NOT NULL,
    [TRANSFERREDON]                     DATETIME         NOT NULL,
    [PURCHLEDGERPOSTING]                INT              NOT NULL,
    [BANKCHEQUENUM]                     NVARCHAR (20)    NOT NULL,
    [PAYMENT]                           NVARCHAR (10)    NOT NULL,
    [CASHDISCCODE]                      NVARCHAR (10)    NOT NULL,
    [EXCHRATESECOND]                    NUMERIC (32, 16) NOT NULL,
    [TRIANGULATION]                     INT              NOT NULL,
    [TAXITEMGROUP]                      NVARCHAR (10)    NOT NULL,
    [VATNUMJOURNAL]                     NVARCHAR (20)    NOT NULL,
    [LISTCODE]                          INT              NOT NULL,
    [FURTHERPOSTINGTYPE]                INT              NOT NULL,
    [PURCHIDRANGE]                      NVARCHAR (250)   NOT NULL,
    [POOLRECID]                         BIGINT           NOT NULL,
    [PREPAYMENT]                        INT              NOT NULL,
    [IMPORTDATE]                        DATETIME         NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]        NVARCHAR (10)    NOT NULL,
    [REASONREFRECID]                    BIGINT           NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]        NVARCHAR (140)   NOT NULL,
    [CUSTVENDBANKACCOUNTID]             NVARCHAR (10)    NOT NULL,
    [PAYMENTSEQUENCENUM]                INT              NOT NULL,
    [ERRORCODEPAYMENT]                  NVARCHAR (30)    NOT NULL,
    [FURTHERPOSTINGRECID]               BIGINT           NOT NULL,
    [TAXDIRECTIONCONTROL]               INT              NOT NULL,
    [CUSTVENDNEGINSTPROTESTREASON]      INT              NOT NULL,
    [BANKREMITTANCETYPE]                INT              NOT NULL,
    [BANKREMITTANCEFILEID]              NVARCHAR (10)    NOT NULL,
    [BANKACCOUNTID]                     NVARCHAR (10)    NOT NULL,
    [BANKPROMISSORYNOTENUM]             NVARCHAR (20)    NOT NULL,
    [RELEASEDATECOMMENT]                NVARCHAR (60)    NOT NULL,
    [INVOICERELEASEDATE]                DATETIME         NOT NULL,
    [INVOICERELEASEDATETZID]            INT              NOT NULL,
    [BANKBILLOFEXCHANGENUM]             NVARCHAR (20)    NOT NULL,
    [NEGINSTID]                         NVARCHAR (20)    NOT NULL,
    [TAXWITHHOLDGROUP]                  NVARCHAR (10)    NOT NULL,
    [TAX1099STATEAMOUNT]                NUMERIC (32, 16) NOT NULL,
    [TAX1099STATE]                      NVARCHAR (10)    NOT NULL,
    [REMITTEECURRENCY]                  NVARCHAR (3)     NOT NULL,
    [DEFAULTDIMENSION]                  BIGINT           NOT NULL,
    [OFFSETDEFAULTDIMENSION]            BIGINT           NOT NULL,
    [LEDGERDIMENSION]                   BIGINT           NOT NULL,
    [REVERSEENTRY]                      INT              NOT NULL,
    [REVERSEDATE]                       DATETIME         NOT NULL,
    [REVRECID]                          BIGINT           NOT NULL,
    [OFFSETLEDGERDIMENSION]             BIGINT           NOT NULL,
    [BANKRECONCILEACCOUNTATPOST]        INT              NOT NULL,
    [BANKCHEQUEDEPOSITTRANSREFRECID]    BIGINT           NOT NULL,
    [MARKEDINVOICECOMPANY]              NVARCHAR (4)     NOT NULL,
    [REMITTANCELOCATION]                BIGINT           NOT NULL,
    [REMITTANCEADDRESS]                 BIGINT           NOT NULL,
    [RELEASEDATE]                       DATETIME         NOT NULL,
    [RELEASEDATETZID]                   INT              NOT NULL,
    [CUSTEINVOICEPAYMDELIVERYNUM]       INT              NOT NULL,
    [CUSTEINVOICEPAYMSECTIONNUM]        INT              NOT NULL,
    [CUSTEINVOICEPAYMTRANSNUM]          INT              NOT NULL,
    [PAYMINSTRUCTION1]                  BIGINT           NOT NULL,
    [PAYMINSTRUCTION2]                  BIGINT           NOT NULL,
    [PAYMINSTRUCTION3]                  BIGINT           NOT NULL,
    [PAYMINSTRUCTION4]                  BIGINT           NOT NULL,
    [VENDINVOICEDECLARATION_IS]         BIGINT           NOT NULL,
    [TAX1099FIELDS]                     BIGINT           NOT NULL,
    [GSTHSTTAXTYPE_CA]                  INT              NOT NULL,
    [VENDBANKACCOUNT]                   BIGINT           NOT NULL,
    [CUSTBANKACCOUNT]                   BIGINT           NOT NULL,
    [BUDGETSOURCELEDGERENTRYUNPOSTED]   BIGINT           NOT NULL,
    [OPERATIONTYPE_MX]                  INT              NOT NULL,
    [TAXWITHHOLDITEMGROUPHEADING_TH]    BIGINT           NOT NULL,
    [APPROVER]                          BIGINT           NOT NULL,
    [EUSALESLIST]                       NVARCHAR (20)    NOT NULL,
    [LEDGERJOURNALDLVDATE_ES]           DATETIME         NOT NULL,
    [TAXWITHHOLDCALCULATE_TH]           INT              NOT NULL,
    [TAXWITHHOLDALTERNATEVENDORACCT_TH] NVARCHAR (20)    NOT NULL,
    [CUSTFACTUREAUTOCREATE_RU]          INT              NOT NULL,
    [VATONPAYMENT_RU]                   INT              NOT NULL,
    [CORRECT_RU]                        INT              NOT NULL,
    [INTRACOMVATDUEDATE_W]              INT              NOT NULL,
    [CORRECTEDINVOICEID_RU]             NVARCHAR (20)    NOT NULL,
    [CORRECTEDINVOICEDATE_RU]           DATETIME         NOT NULL,
    [ATTACHMENTS_CN]                    INT              NOT NULL,
    [REFCOPYREVERSE_CN]                 BIGINT           NOT NULL,
    [VOUCHER_CN]                        NVARCHAR (20)    NOT NULL,
    [VATPAYMREFRECID_RU]                BIGINT           NOT NULL,
    [VATTAXAGENTVENDACCOUNT_RU]         NVARCHAR (20)    NOT NULL,
    [VATOPERATIONCODE_RU]               NVARCHAR (10)    NOT NULL,
    [ANNOUNCEMENTNUM_RU]                NVARCHAR (20)    NOT NULL,
    [CASHRECEIPTNUM_LV]                 NVARCHAR (20)    NOT NULL,
    [PAYMENTPRIORITY_LT]                INT              NOT NULL,
    [FOREIGNBANKFEE_LT]                 INT              NOT NULL,
    [INFORMBYTELEX_LT]                  INT              NOT NULL,
    [INFORMBYPHONE_LT]                  INT              NOT NULL,
    [DEBITCURRENCYCODE_LT]              NVARCHAR (3)     NOT NULL,
    [MARKUPCODE_RU]                     NVARCHAR (10)    NOT NULL,
    [CUSTOMSTARIFFDIRECTION_IN]         INT              NOT NULL,
    [ASSESSABLEVALUE_IN]                NUMERIC (32, 16) NOT NULL,
    [MAXIMUMRETAILPRICE_IN]             NUMERIC (32, 16) NOT NULL,
    [EXCISERECORDTYPE_IN]               INT              NOT NULL,
    [GTASERVICECATEGORY_IN]             INT              NOT NULL,
    [NONRECOVERABLEPERCENT_IN]          NUMERIC (32, 16) NOT NULL,
    [VATGOODSTYPE_IN]                   INT              NOT NULL,
    [CONSIGNMENTNOTENUM_IN]             NVARCHAR (15)    NOT NULL,
    [CUSTOMSDUTY_IN]                    NUMERIC (32, 16) NOT NULL,
    [TDSGROUP_IN]                       NVARCHAR (10)    NOT NULL,
    [TCSGROUP_IN]                       NVARCHAR (10)    NOT NULL,
    [NATUREOFASSESSEE_IN]               INT              NOT NULL,
    [COMPANYLOCATION_IN]                BIGINT           NOT NULL,
    [AGREEMENTCOMPANY_RU]               NVARCHAR (4)     NOT NULL,
    [OFFSETAGREEMENTCOMPANY_RU]         NVARCHAR (4)     NOT NULL,
    [LEDGERVOUCHERTYPE_CN]              BIGINT           NOT NULL,
    [SALESTAXFORMTYPES_IN]              BIGINT           NOT NULL,
    [CUSTOMSTARIFFCODETABLE_IN]         BIGINT           NOT NULL,
    [EXCISETARIFFCODES_IN]              BIGINT           NOT NULL,
    [SERVICECODETABLE_IN]               BIGINT           NOT NULL,
    [EXCISETYPE_IN]                     INT              NOT NULL,
    [BANKCURRENCYTRANSFERLOG_RU]        BIGINT           NOT NULL,
    [BANKCENTRALBANKTRANSTYPECUR_RU]    NVARCHAR (10)    NOT NULL,
    [BANKPRINTACCOUNTNUM_RU]            NVARCHAR (20)    NOT NULL,
    [OFFSESSIONID_RU]                   NVARCHAR (20)    NOT NULL,
    [RCASHDOCREPRESPERSONID]            NVARCHAR (20)    NOT NULL,
    [OFFSETPOSTINGPROFILE_RU]           NVARCHAR (10)    NOT NULL,
    [PAYMPURPOSE_LT]                    NVARCHAR (10)    NOT NULL,
    [INTBANK_LV]                        NVARCHAR (10)    NOT NULL,
    [RCASHDOCREPRESTYPE]                INT              NOT NULL,
    [VATDUEDATE_W]                      DATETIME         NOT NULL,
    [TAXBASE_W]                         NUMERIC (32, 16) NOT NULL,
    [RCASHPAYTRANSTYPE]                 INT              NOT NULL,
    [MCRPAYMORDERID]                    NVARCHAR (20)    NOT NULL,
    [MCRCCGENERALLEDGERID]              NVARCHAR (10)    NOT NULL,
    [MCRREFPAYMID]                      BIGINT           NOT NULL,
    [MCRPRINTTXTONCHECK]                INT              NOT NULL,
    [ACCOUNTAGREEMENTID_RU]             NVARCHAR (20)    NOT NULL,
    [ADDRESSING_PL]                     NVARCHAR (250)   NOT NULL,
    [BANKAGREEMENTEXT_RU]               BIGINT           NOT NULL,
    [BANKCLIENTDOCUMENTTYPEID_RU]       NVARCHAR (2)     NOT NULL,
    [BANKCOMMACCOUNTID_RU]              NVARCHAR (10)    NOT NULL,
    [BANKCURRENCY]                      NVARCHAR (3)     NOT NULL,
    [BANKCURRENCYAMOUNT]                NUMERIC (32, 16) NOT NULL,
    [BANKCURRENCYDEALCOURSE_RU]         NUMERIC (32, 16) NOT NULL,
    [BANKPAYMENTREGISTRATIONNUM_LV]     NVARCHAR (20)    NOT NULL,
    [BANKRESPWORKERID_RU]               BIGINT           NOT NULL,
    [BANKSPECACCOUNTID_RU]              NVARCHAR (10)    NOT NULL,
    [BANKVENDACCOUNTID_RU]              NVARCHAR (20)    NOT NULL,
    [CASHDISCBASEDATE]                  DATETIME         NOT NULL,
    [CASHDISCBASEDAYS]                  INT              NOT NULL,
    [CORRECTIONTYPE_RU]                 INT              NOT NULL,
    [CUSTVENDACCOUNT_PL]                NVARCHAR (10)    NOT NULL,
    [CUSTVENDNAME_PL]                   NVARCHAR (60)    NOT NULL,
    [OFFSETACCOUNTAGREEMENTID_RU]       NVARCHAR (20)    NOT NULL,
    [RECEIPTDATE_W]                     DATETIME         NOT NULL,
    [REPRESPERSONCARD_W]                NVARCHAR (100)   NOT NULL,
    [REPRESPERSONNAME_W]                NVARCHAR (60)    NOT NULL,
    [SKIPBLOCKEDFORMANUALENTRYCHECK]    INT              NOT NULL,
    [SOFTWAREDECLRECEIVED_IN]           INT              NOT NULL,
    [TAXPERIODPAYMENTCODE_PL]           NVARCHAR (10)    NOT NULL,
    [TAXSETOFFVOUCHER_IN]               NVARCHAR (20)    NOT NULL,
    [TAXWITHHOLDCODE_IN]                NVARCHAR (10)    NOT NULL,
    [TRANSFERCURRENCY_RU]               NVARCHAR (3)     NOT NULL,
    [CFDIUUID_MX]                       NVARCHAR (36)    NOT NULL,
    [COMMPROFILETYPE_RU]                INT              NOT NULL,
    [INVOICESERIES_MX]                  NVARCHAR (10)    NOT NULL,
    [MODIFIEDDATETIME]                  DATETIME         NOT NULL,
    [DATAAREAID]                        NVARCHAR (4)     NOT NULL,
    [RECVERSION]                        INT              NOT NULL,
    [PARTITION]                         BIGINT           NOT NULL,
    [RECID]                             BIGINT           NOT NULL,
    [ROLBOLDATE]                        DATETIME         NOT NULL,
    [ROLFDADATE]                        DATETIME         NOT NULL,
    [ROLVESSELETADATE]                  DATETIME         NOT NULL,
    CONSTRAINT [I_212RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

