CREATE TABLE [dbo].[LEDGER] (
    [CHARTOFACCOUNTS]         BIGINT        NOT NULL,
    [NAME]                    NVARCHAR (20) NOT NULL,
    [DESCRIPTION]             NVARCHAR (60) NOT NULL,
    [PRIMARYFORLEGALENTITY]   BIGINT        NOT NULL,
    [FISCALCALENDAR]          BIGINT        NOT NULL,
    [DEFAULTEXCHANGERATETYPE] BIGINT        NOT NULL,
    [BUDGETEXCHANGERATETYPE]  BIGINT        NOT NULL,
    [ACCOUNTINGCURRENCY]      NVARCHAR (3)  NOT NULL,
    [REPORTINGCURRENCY]       NVARCHAR (3)  NOT NULL,
    [ISBUDGETCONTROLENABLED]  INT           NOT NULL,
    [MODIFIEDDATETIME]        DATETIME      NOT NULL,
    [RECVERSION]              INT           NOT NULL,
    [PARTITION]               BIGINT        NOT NULL,
    [RECID]                   BIGINT        NOT NULL,
    CONSTRAINT [I_7057RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

