CREATE TABLE [dbo].[LINEOFBUSINESS] (
    [LINEOFBUSINESSID] NVARCHAR (10) DEFAULT ('') NOT NULL,
    [DESCRIPTION]      NVARCHAR (60) DEFAULT ('') NOT NULL,
    [DATAAREAID]       NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]       INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]        BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    CHECK ([RECID]<>(0))
);

