CREATE TABLE [dbo].[LOGISTICSELECTRONICADDRESSROLE] (
    [ELECTRONICADDRESS] BIGINT DEFAULT ((0)) NOT NULL,
    [LOCATIONROLE]      BIGINT DEFAULT ((0)) NOT NULL,
    [RECVERSION]        INT    DEFAULT ((1)) NOT NULL,
    [PARTITION]         BIGINT DEFAULT ((5637144576.)) NOT NULL,
    [RECID]             BIGINT NOT NULL,
    CHECK ([RECID]<>(0))
);

