CREATE TABLE [dbo].[LOGISTICSADDRESSSTATE] (
    [NAME]            NVARCHAR (60) DEFAULT ('') NOT NULL,
    [STATEID]         NVARCHAR (10) DEFAULT ('') NOT NULL,
    [COUNTRYREGIONID] NVARCHAR (10) DEFAULT ('') NOT NULL,
    [INTRASTATCODE]   NVARCHAR (10) DEFAULT ('') NOT NULL,
    [TIMEZONE]        INT           DEFAULT ((0)) NOT NULL,
    [PROPERTIES_RU]   BIGINT        DEFAULT ((0)) NOT NULL,
    [GNISLOCATION]    NVARCHAR (20) DEFAULT ('') NOT NULL,
    [IBGECODE_BR]     NVARCHAR (2)  DEFAULT ('') NOT NULL,
    [STATECODE_IT]    NVARCHAR (2)  DEFAULT ('') NOT NULL,
    [RECVERSION]      INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]       BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    CHECK ([RECID]<>(0))
);

