CREATE TABLE [dbo].[LOGISTICSADDRESSCOUNTY] (
    [COUNTRYREGIONID] NVARCHAR (10) DEFAULT ('') NOT NULL,
    [COUNTYID]        NVARCHAR (10) DEFAULT ('') NOT NULL,
    [STATEID]         NVARCHAR (10) DEFAULT ('') NOT NULL,
    [NAME]            NVARCHAR (60) DEFAULT ('') NOT NULL,
    [COUNTYCODE_SP]   NVARCHAR (2)  DEFAULT ('') NOT NULL,
    [COUNTYCODE_IT]   NVARCHAR (2)  DEFAULT ('') NOT NULL,
    [PROPERTIES_RU]   BIGINT        DEFAULT ((0)) NOT NULL,
    [RECVERSION]      INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]       BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    CHECK ([RECID]<>(0))
);

