CREATE TABLE [dbo].[LOGISTICSADDRESSZIPCODE] (
    [ZIPCODE]         NVARCHAR (10) DEFAULT ('') NOT NULL,
    [CITY]            NVARCHAR (60) DEFAULT ('') NOT NULL,
    [STREETNAME]      NVARCHAR (60) DEFAULT ('') NOT NULL,
    [FROMNUM]         INT           DEFAULT ((0)) NOT NULL,
    [TONUM]           INT           DEFAULT ((0)) NOT NULL,
    [EVENODD]         INT           DEFAULT ((0)) NOT NULL,
    [COUNTY]          NVARCHAR (10) DEFAULT ('') NOT NULL,
    [COUNTRYREGIONID] NVARCHAR (10) DEFAULT ('') NOT NULL,
    [STATE]           NVARCHAR (10) DEFAULT ('') NOT NULL,
    [CITYALIAS]       NVARCHAR (30) DEFAULT ('') NOT NULL,
    [TIMEZONE]        INT           DEFAULT ((0)) NOT NULL,
    [DISTRICT]        BIGINT        DEFAULT ((0)) NOT NULL,
    [CITYRECID]       BIGINT        DEFAULT ((0)) NOT NULL,
    [DISTRICTNAME]    NVARCHAR (60) DEFAULT ('') NOT NULL,
    [RECVERSION]      INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]       BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    CONSTRAINT [I_2947RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

