CREATE TABLE [dbo].[LOGISTICSADDRESSSCITY] (
    [NAME]                NVARCHAR (60) DEFAULT ('') NOT NULL,
    [DESCRIPTION]         NVARCHAR (60) DEFAULT ('') NOT NULL,
    [COUNTRYREGIONID]     NVARCHAR (10) DEFAULT ('') NOT NULL,
    [STATEID]             NVARCHAR (10) DEFAULT ('') NOT NULL,
    [COUNTYID]            NVARCHAR (10) DEFAULT ('') NOT NULL,
    [IBGECODE_BR]         NVARCHAR (7)  DEFAULT ('') NOT NULL,
    [PROPERTIES_RU]       BIGINT        DEFAULT ((0)) NOT NULL,
    [CITYKANA_JP]         NVARCHAR (60) DEFAULT ('') NOT NULL,
    [MUNICIPALITYCODE_IT] NVARCHAR (4)  DEFAULT ('') NOT NULL,
    [CITYCODE_IT]         NVARCHAR (20) DEFAULT ('') NOT NULL,
    [RECVERSION]          INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]           BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]               BIGINT        NOT NULL,
    CHECK ([RECID]<>(0))
);

