CREATE TABLE [dbo].[MAINACCOUNT] (
    [MAINACCOUNTID]                      NVARCHAR (20) NOT NULL,
    [NAME]                               NVARCHAR (60) NOT NULL,
    [CURRENCYCODE]                       NVARCHAR (3)  NOT NULL,
    [TYPE]                               INT           NOT NULL,
    [ACCOUNTCATEGORYREF]                 INT           NOT NULL,
    [DEBITCREDITPROPOSAL]                INT           NOT NULL,
    [DEBITCREDITCHECK]                   INT           NOT NULL,
    [DEBITCREDITBALANCEDEMAND]           INT           NOT NULL,
    [CLOSING]                            INT           NOT NULL,
    [EXCHANGEADJUSTED]                   INT           NOT NULL,
    [MONETARY]                           INT           NOT NULL,
    [MANDATORYPAYMENTREFERENCE]          INT           NOT NULL,
    [VALIDATECURRENCY]                   INT           NOT NULL,
    [USERINFOID]                         NVARCHAR (8)  NOT NULL,
    [VALIDATEUSER]                       INT           NOT NULL,
    [POSTINGTYPE]                        INT           NOT NULL,
    [VALIDATEPOSTING]                    INT           NOT NULL,
    [SRUCODE]                            NVARCHAR (4)  NOT NULL,
    [CONSOLIDATIONMAINACCOUNT]           NVARCHAR (10) NOT NULL,
    [OFFSETLEDGERDIMENSION]              BIGINT        NOT NULL,
    [MAINACCOUNTTEMPLATE]                BIGINT        NOT NULL,
    [LEDGERCHARTOFACCOUNTS]              BIGINT        NOT NULL,
    [INFLATIONADJUSTMENT_MX]             INT           NOT NULL,
    [REPOMOTYPE_MX]                      INT           NOT NULL,
    [ADJUSTMENTMETHOD_MX]                INT           NOT NULL,
    [TRANSFERYEARENDACCOUNT_ES]          BIGINT        NOT NULL,
    [OPENINGACCOUNT]                     BIGINT        NOT NULL,
    [REPORTINGACCOUNTTYPE]               INT           NOT NULL,
    [UNITOFMEASURE]                      BIGINT        NOT NULL,
    [CLOSETYPE]                          INT           NOT NULL,
    [FINANCIALREPORTINGEXCHANGERATETYPE] BIGINT        NOT NULL,
    [FINANCIALREPORTINGTRANSLATIONTYPE]  INT           NOT NULL,
    [PARENTMAINACCOUNT_BR]               BIGINT        NOT NULL,
    [RECVERSION]                         INT           NOT NULL,
    [PARTITION]                          BIGINT        NOT NULL,
    [RECID]                              BIGINT        NOT NULL,
    [ROLISLANDEDCOST]                    INT           NOT NULL,
    [ROLISLANDEDCOSTWIP]                 INT           NOT NULL,
    CONSTRAINT [I_720RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

