CREATE TABLE [dbo].[MARKUPTABLE] (
    [TXT]                                  NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [CUSTPOSTING]                          INT              DEFAULT ((0)) NOT NULL,
    [VENDPOSTING]                          INT              DEFAULT ((0)) NOT NULL,
    [TAXITEMGROUP]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CUSTTYPE]                             INT              DEFAULT ((0)) NOT NULL,
    [VENDTYPE]                             INT              DEFAULT ((0)) NOT NULL,
    [MODULETYPE]                           INT              DEFAULT ((0)) NOT NULL,
    [MARKUPCODE]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [USEINMATCHING]                        INT              DEFAULT ((0)) NOT NULL,
    [MAXAMOUNT]                            NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CUSTOMERLEDGERDIMENSION]              BIGINT           DEFAULT ((0)) NOT NULL,
    [VENDORLEDGERDIMENSION]                BIGINT           DEFAULT ((0)) NOT NULL,
    [ISLETTEROFCREDIT_SA]                  INT              DEFAULT ((0)) NOT NULL,
    [MARKUPCLASSIFICATION_BR]              INT              DEFAULT ((0)) NOT NULL,
    [USECUSTPOSTINGTYPETRANSIT_RU]         INT              DEFAULT ((0)) NOT NULL,
    [RETAILCONCESSIONFEE]                  INT              DEFAULT ((0)) NOT NULL,
    [MCRPRORATE]                           INT              DEFAULT ((0)) NOT NULL,
    [CUSTOMPAYMTYPE_RU]                    INT              DEFAULT ((0)) NOT NULL,
    [MCRBROKERCONTRACTFEE]                 INT              DEFAULT ((0)) NOT NULL,
    [INCLUDEINTOINTRASTATINVOICEVALUE]     INT              DEFAULT ((0)) NOT NULL,
    [INCLUDEINTOINTRASTATSTATISTICALVALUE] INT              DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                           NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                           INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                            BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                                BIGINT           NOT NULL,
    [JSTPMINCLUDEINPRICE]                  INT              DEFAULT ((0)) NOT NULL,
    [ROLINCLUDESOINVOICE]                  INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_229MODULECODEIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [MODULETYPE] ASC, [MARKUPCODE] ASC),
    CHECK ([RECID]<>(0))
);

