CREATE TABLE [dbo].[MCRBROKERCONTRACTTABLE] (
    [CONTRACTID]     NVARCHAR (12)    DEFAULT ('') NOT NULL,
    [MISCCHARGECODE] NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VALUE]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [FROMDATE]       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [TODATE]         DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DESCRIPTION]    NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [VALUETYPE]      INT              DEFAULT ((0)) NOT NULL,
    [STATUS]         INT              DEFAULT ((0)) NOT NULL,
    [BROKERID]       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CURRENCY]       NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [DATAAREAID]     NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]     INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]      BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]          BIGINT           NOT NULL,
    CONSTRAINT [I_30868CONTRACTID] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [CONTRACTID] ASC),
    CHECK ([RECID]<>(0))
);

