CREATE TABLE [dbo].[MCRBROKERCONTRACTLINE] (
    [CONTRACTID]      NVARCHAR (12)    DEFAULT ('') NOT NULL,
    [MISCCHARGECODE]  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VALUE]           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ITEMCODE]        INT              DEFAULT ((0)) NOT NULL,
    [ITEMRELATION]    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [VALUETYPE]       INT              DEFAULT ((0)) NOT NULL,
    [AMOUNT]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [AMOUNTTYPE]      INT              DEFAULT ((0)) NOT NULL,
    [ACCOUNTCODE]     INT              DEFAULT ((0)) NOT NULL,
    [ACCOUNTRELATION] NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [TAXGROUP]        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DATAAREAID]      NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]      INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]       BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]           BIGINT           NOT NULL,
    CONSTRAINT [I_30869RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

