CREATE TABLE [dbo].[Order_Status_Report_Hist] (
    [daily_id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [wh_id]                    VARCHAR (50)    NULL,
    [ordnum]                   VARCHAR (50)    NULL,
    [ord_received]             DATETIME        NULL,
    [ordtyp]                   VARCHAR (50)    NULL,
    [prtnum]                   VARCHAR (50)    NULL,
    [requested_quantity_cases] DECIMAL (18, 6) NULL,
    [lotnum_ordered]           VARCHAR (50)    NULL,
    [lotnum_picked]            VARCHAR (50)    NULL,
    [shipped_quantity_cases]   DECIMAL (18, 6) NULL,
    [staged_quantity_cases]    DECIMAL (18, 6) NULL,
    [picked_quantity_cases]    DECIMAL (18, 6) NULL,
    [shipment_status]          VARCHAR (50)    NULL,
    [carcod]                   VARCHAR (50)    NULL,
    [srvlvl]                   VARCHAR (50)    NULL,
    [ship_id]                  VARCHAR (50)    NULL,
    [order_status]             VARCHAR (50)    NULL,
    [untqty]                   DECIMAL (18, 6) NULL,
    [ordqty]                   DECIMAL (18, 6) NULL,
    [order_allocated_date]     VARCHAR (50)    NULL,
    [order_staged_date]        VARCHAR (50)    NULL,
    [shipment_loaded_date]     VARCHAR (50)    NULL,
    [trlr_dispatched_date]     VARCHAR (50)    NULL,
    [shpsts]                   VARCHAR (50)    NULL,
    [load_date]                DATETIME        CONSTRAINT [DF_Order_Status_Report_Daily_load_date] DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Order_Status_Report_Daily] PRIMARY KEY CLUSTERED ([daily_id] ASC)
);

