CREATE TABLE [dbo].[PAYMTERM] (
    [PAYMTERMID]                      NVARCHAR (10) DEFAULT ('') NOT NULL,
    [PAYMMETHOD]                      INT           DEFAULT ((0)) NOT NULL,
    [NUMOFDAYS]                       INT           DEFAULT ((0)) NOT NULL,
    [DESCRIPTION]                     NVARCHAR (60) DEFAULT ('') NOT NULL,
    [NUMOFMONTHS]                     INT           DEFAULT ((0)) NOT NULL,
    [PAYMSCHED]                       NVARCHAR (30) DEFAULT ('') NOT NULL,
    [CASH]                            INT           DEFAULT ((0)) NOT NULL,
    [PAYMDAYID]                       NVARCHAR (10) DEFAULT ('') NOT NULL,
    [SHIPCARRIERANCILLARYCHARGE]      INT           DEFAULT ((0)) NOT NULL,
    [POSTOFFSETTINGAR]                INT           DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERCERTIFIEDCHECK]       INT           DEFAULT ((0)) NOT NULL,
    [CREDITCARDPAYMENTTYPE]           INT           DEFAULT ((0)) NOT NULL,
    [CREDITCARDCREDITCHECK]           INT           DEFAULT ((0)) NOT NULL,
    [CASHLEDGERDIMENSION]             BIGINT        DEFAULT ((0)) NOT NULL,
    [USEDELIVERYDATEFORDUEDATE_ES]    INT           DEFAULT ((0)) NOT NULL,
    [DUEDATELIMITGROUPID_ES]          NVARCHAR (10) DEFAULT ('') NOT NULL,
    [USEEMPLACCOUNT_RU]               INT           DEFAULT ((0)) NOT NULL,
    [ADDITIONALMONTHS]                INT           DEFAULT ((0)) NOT NULL,
    [CUSTOMERUPDATEDUEDATE]           INT           DEFAULT ((0)) NOT NULL,
    [CUTOFFDAY]                       INT           DEFAULT ((0)) NOT NULL,
    [DEFAULTPAYMTERM_PSN]             INT           DEFAULT ((0)) NOT NULL,
    [VENDORUPDATEDUEDATE]             INT           DEFAULT ((0)) NOT NULL,
    [CFMPAYMENTREQUESTTYPEPAYMENT]    BIGINT        DEFAULT ((0)) NOT NULL,
    [CFMPAYMENTREQUESTTYPEPREPAYMENT] BIGINT        DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                      NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]                      INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]                       BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                           BIGINT        NOT NULL,
    [ROLBOL]                          INT           DEFAULT ((0)) NOT NULL,
    [ROLFDA]                          INT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_276TERMIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [PAYMTERMID] ASC),
    CHECK ([RECID]<>(0))
);

