CREATE TABLE [dbo].[PRICEDISCTABLE] (
    [AGREEMENT]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ITEMCODE]                       INT              DEFAULT ((0)) NOT NULL,
    [ACCOUNTCODE]                    INT              DEFAULT ((0)) NOT NULL,
    [ITEMRELATION]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ACCOUNTRELATION]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [QUANTITYAMOUNTFROM]             NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [FROMDATE]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [TODATE]                         DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [AMOUNT]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CURRENCY]                       NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [PERCENT1]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PERCENT2]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [DELIVERYTIME]                   INT              DEFAULT ((0)) NOT NULL,
    [SEARCHAGAIN]                    INT              DEFAULT ((0)) NOT NULL,
    [PRICEUNIT]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [RELATION]                       INT              DEFAULT ((0)) NOT NULL,
    [QUANTITYAMOUNTTO]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [UNITID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MARKUP]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ALLOCATEMARKUP]                 INT              DEFAULT ((0)) NOT NULL,
    [MODULE]                         INT              DEFAULT ((0)) NOT NULL,
    [INVENTDIMID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CALENDARDAYS]                   INT              DEFAULT ((0)) NOT NULL,
    [GENERICCURRENCY]                INT              DEFAULT ((0)) NOT NULL,
    [MCRPRICEDISCGROUPTYPE]          INT              DEFAULT ((0)) NOT NULL,
    [MCRFIXEDAMOUNTCUR]              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [MCRMERCHANDISINGEVENTID]        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [AGREEMENTHEADEREXT_RU]          BIGINT           DEFAULT ((0)) NOT NULL,
    [DISREGARDLEADTIME]              INT              DEFAULT ((0)) NOT NULL,
    [INVENTBAILEEFREEDAYS_RU]        INT              DEFAULT ((0)) NOT NULL,
    [MAXIMUMRETAILPRICE_IN]          NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ORIGINALPRICEDISCADMTRANSRECID] BIGINT           DEFAULT ((0)) NOT NULL,
    [PDSCALCULATIONID]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]               DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                     INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                      BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    CONSTRAINT [I_315RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0))
);

