CREATE TABLE [dbo].[PRICELIST_CURRENT] (
    [AGREEMENT]               NVARCHAR (10)    NOT NULL,
    [ITEMCODE]                INT              NOT NULL,
    [ACCOUNTCODE]             INT              NOT NULL,
    [ITEMRELATION]            NVARCHAR (20)    NOT NULL,
    [ACCOUNTRELATION]         NVARCHAR (20)    NOT NULL,
    [QUANTITYAMOUNTFROM]      NUMERIC (32, 16) NOT NULL,
    [FROMDATE]                DATETIME         NOT NULL,
    [TODATE]                  DATETIME         NOT NULL,
    [AMOUNT]                  NUMERIC (32, 16) NOT NULL,
    [CURRENCY]                NVARCHAR (3)     NOT NULL,
    [PERCENT1]                NUMERIC (32, 16) NOT NULL,
    [PERCENT2]                NUMERIC (32, 16) NOT NULL,
    [QUANTITYAMOUNTTO]        NUMERIC (32, 16) NOT NULL,
    [DELIVERYTIME]            INT              NOT NULL,
    [SEARCHAGAIN]             INT              NOT NULL,
    [PRICEUNIT]               NUMERIC (32, 16) NOT NULL,
    [RELATION]                INT              NOT NULL,
    [UNITID]                  NVARCHAR (10)    NOT NULL,
    [MARKUP]                  NUMERIC (32, 16) NOT NULL,
    [ALLOCATEMARKUP]          INT              NOT NULL,
    [MODULE]                  INT              NOT NULL,
    [LINENUM]                 NUMERIC (32, 16) NOT NULL,
    [JOURNALNUM]              NVARCHAR (10)    NOT NULL,
    [PRICEDISCTABLEREF]       BIGINT           NOT NULL,
    [LOG]                     NVARCHAR (255)   NOT NULL,
    [INVENTDIMID]             NVARCHAR (20)    NOT NULL,
    [CALENDARDAYS]            INT              NOT NULL,
    [DIFFERENTFROMPOSTED]     INT              NOT NULL,
    [GENERICCURRENCY]         INT              NOT NULL,
    [MUSTBEDELETED]           INT              NOT NULL,
    [AGREEMENTHEADEREXT_RU]   BIGINT           NOT NULL,
    [DISREGARDLEADTIME]       INT              NOT NULL,
    [INVENTBAILEEFREEDAYS_RU] INT              NOT NULL,
    [MAXIMUMRETAILPRICE_IN]   NUMERIC (32, 16) NOT NULL,
    [PDSCALCULATIONID]        NVARCHAR (10)    NOT NULL,
    [MODIFIEDDATETIME]        DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DATAAREAID]              NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]              INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]               BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                   BIGINT           NOT NULL,
    CONSTRAINT [I_972JOURLINENUMIDXC] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [JOURNALNUM] ASC, [LINENUM] ASC, [RECID] ASC),
    CHECK ([RECID]<>(0))
);

