CREATE TABLE [dbo].[pstest4] (
    [SKU]                                   FLOAT (53)  NULL,
    [Name]                                  FLOAT (53)  NULL,
    [Item Name]                             FLOAT (53)  NULL,
    [Product Name]                          FLOAT (53)  NULL,
    [Computed - Pack Size]                  FLOAT (53)  NULL,
    [Unit Quantity]                         FLOAT (53)  NULL,
    [Unit Size]                             FLOAT (53)  NULL,
    [Brand Name]                            FLOAT (53)  NULL,
    [Disabled]                              FLOAT (53)  NULL,
    [Product Category 1]                    FLOAT (53)  NULL,
    [Product Category 2]                    FLOAT (53)  NULL,
    [Supplier Engagement Specialist]        FLOAT (53)  NULL,
    [Buyer Name]                            FLOAT (53)  NULL,
    [Item UPC]                              FLOAT (53)  NULL,
    [Inside UPC Code]                       FLOAT (53)  NULL,
    [Outside UPC Code]                      FLOAT (53)  NULL,
    [Master Pack]                           FLOAT (53)  NULL,
    [Effective Date (mmddyyyy)]             SQL_VARIANT NULL,
    [Supersedes (mmddyyyy)]                 FLOAT (53)  NULL,
    [Reason for Change]                     FLOAT (53)  NULL,
    [Revised By]                            FLOAT (53)  NULL,
    [File]                                  FLOAT (53)  NULL,
    [Pack Size]                             FLOAT (53)  NULL,
    [Pack1]                                 FLOAT (53)  NULL,
    [Pack2]                                 FLOAT (53)  NULL,
    [Supplier #1]                           FLOAT (53)  NULL,
    [Supplier # 10 COO]                     FLOAT (53)  NULL,
    [Supplier #10]                          FLOAT (53)  NULL,
    [Supplier #10 Kosher]                   FLOAT (53)  NULL,
    [Supplier #11]                          FLOAT (53)  NULL,
    [Supplier # 11 COO]                     FLOAT (53)  NULL,
    [Supplier #11 Kosher]                   FLOAT (53)  NULL,
    [Supplier #1 COO]                       FLOAT (53)  NULL,
    [Supplier #2]                           SQL_VARIANT NULL,
    [Supplier #1 Kosher]                    FLOAT (53)  NULL,
    [Supplier #2 Kosher]                    FLOAT (53)  NULL,
    [Supplier #2 COO]                       SQL_VARIANT NULL,
    [Supplier # 3 COO]                      FLOAT (53)  NULL,
    [Supplier #3]                           FLOAT (53)  NULL,
    [Supplier #3 Kosher]                    FLOAT (53)  NULL,
    [Supplier #4]                           SQL_VARIANT NULL,
    [Supplier #4 Kosher]                    FLOAT (53)  NULL,
    [Supplier # 4 COO]                      FLOAT (53)  NULL,
    [Supplier #5]                           FLOAT (53)  NULL,
    [Supplier # 5 COO]                      FLOAT (53)  NULL,
    [Supplier #5 Kosher]                    SQL_VARIANT NULL,
    [Supplier #6]                           FLOAT (53)  NULL,
    [Supplier # 6 COO]                      SQL_VARIANT NULL,
    [Supplier #6 Kosher]                    FLOAT (53)  NULL,
    [Supplier # 7 COO]                      FLOAT (53)  NULL,
    [Supplier #7]                           FLOAT (53)  NULL,
    [Supplier #7 Kosher]                    FLOAT (53)  NULL,
    [Supplier #8]                           FLOAT (53)  NULL,
    [Supplier # 8 COO]                      SQL_VARIANT NULL,
    [Supplier #8 Kosher]                    FLOAT (53)  NULL,
    [Supplier #9]                           FLOAT (53)  NULL,
    [Supplier # 9 COO]                      FLOAT (53)  NULL,
    [Supplier #9 Kosher]                    SQL_VARIANT NULL,
    [Case Length (in)]                      FLOAT (53)  NULL,
    [Case Width (in)]                       FLOAT (53)  NULL,
    [Case Height (in)]                      FLOAT (53)  NULL,
    [Case Net Weight (lb)]                  FLOAT (53)  NULL,
    [Case Gross Weight (lb)]                FLOAT (53)  NULL,
    [Case Tare Weight (lb)]                 FLOAT (53)  NULL,
    [Pallet Hi]                             SQL_VARIANT NULL,
    [Pallet Tie]                            FLOAT (53)  NULL,
    [Gross Pallet Weight (lb)]              FLOAT (53)  NULL,
    [Cases Per Pallet]                      FLOAT (53)  NULL,
    [Case Cube (ft3)]                       FLOAT (53)  NULL,
    [Packaging Type]                        SQL_VARIANT NULL,
    [Net Weight (Unit Label)]               FLOAT (53)  NULL,
    [Net Weight Formula]                    FLOAT (53)  NULL,
    [DR Weight Formula]                     FLOAT (53)  NULL,
    [DR Weight (Unit Label)]                FLOAT (53)  NULL,
    [DR WT Unit (use: g, kg, OZ, LB)]       SQL_VARIANT NULL,
    [Packaging Tare Weight (g)]             FLOAT (53)  NULL,
    [Shelf Life Days (Unopened)]            FLOAT (53)  NULL,
    [Unopened Storage Condition]            FLOAT (53)  NULL,
    [Shelf Life After Opening (Days)]       SQL_VARIANT NULL,
    [Opened Storage Condition]              FLOAT (53)  NULL,
    [Ship Contidions (Sales)]               FLOAT (53)  NULL,
    [Calories (kcal)/100g]                  FLOAT (53)  NULL,
    [Calories from Fat (kcal)/100g]         FLOAT (53)  NULL,
    [Total Fat (g)/100g]                    FLOAT (53)  NULL,
    [Saturated Fat (g)/100g]                FLOAT (53)  NULL,
    [Unsaturated Fat (g)/100g]              FLOAT (53)  NULL,
    [Polyunsaturated Fat (g)/100g]          SQL_VARIANT NULL,
    [Calcium (mg)/100g]                     FLOAT (53)  NULL,
    [Added Sugar (g)/100g]                  FLOAT (53)  NULL,
    [Cholesterol (mg)/100g]                 SQL_VARIANT NULL,
    [Iron (mg)/100g]                        FLOAT (53)  NULL,
    [Dietary Fiber (g)/100g]                FLOAT (53)  NULL,
    [Monounsaturated Fat (g)/100g]          SQL_VARIANT NULL,
    [Moisture/Ash (g)/100g]                 FLOAT (53)  NULL,
    [Protein (g)/100g]                      FLOAT (53)  NULL,
    [Potassium (mg)/100g]                   FLOAT (53)  NULL,
    [Total Carbohydrate (g)/100g]           FLOAT (53)  NULL,
    [Sodium (mg)/100g]                      FLOAT (53)  NULL,
    [Trans Fat (g)/100g]                    FLOAT (53)  NULL,
    [Total Sugar (g)/100g]                  FLOAT (53)  NULL,
    [Vitamin C (mg)/100g]                   FLOAT (53)  NULL,
    [Vitamin A (mcg)/100g]                  SQL_VARIANT NULL,
    [Vitamin D (mcg)/100g]                  FLOAT (53)  NULL,
    [Calories (kcal)/Serving]               FLOAT (53)  NULL,
    [Total Fat (g)/Serving]                 FLOAT (53)  NULL,
    [Saturated Fat (g)/Serving]             FLOAT (53)  NULL,
    [Added Sugar (g)/Serving]               FLOAT (53)  NULL,
    [Monounsaturated Fat (g)/Serving]       FLOAT (53)  NULL,
    [Dietary Fiber (g)/Serving]             FLOAT (53)  NULL,
    [Protein (g)/Serving]                   FLOAT (53)  NULL,
    [Polyunsaturated Fat (g)/Serving]       FLOAT (53)  NULL,
    [Total Sugar (g)/Serving]               FLOAT (53)  NULL,
    [Total Carbs (g)/Serving]               FLOAT (53)  NULL,
    [Trans Fat (g)/Serving]                 FLOAT (53)  NULL,
    [Unsaturated Fat (g)/Serving]           FLOAT (53)  NULL,
    [Calcium (mg)/Serving]                  FLOAT (53)  NULL,
    [Cholesterol (mg)/Serving]              FLOAT (53)  NULL,
    [Potassium (mg)/Serving]                FLOAT (53)  NULL,
    [Iron (mg)/Serving]                     FLOAT (53)  NULL,
    [Sodium (mg)/Serving]                   FLOAT (53)  NULL,
    [Added Sugars (%DV)]                    FLOAT (53)  NULL,
    [Cholesterol (%DV)]                     FLOAT (53)  NULL,
    [Saturated Fat (%DV)]                   FLOAT (53)  NULL,
    [Dietary Fiber (%DV)]                   SQL_VARIANT NULL,
    [Sodium (%DV)]                          FLOAT (53)  NULL,
    [Total Carb (%DV)]                      FLOAT (53)  NULL,
    [Vitamin D (%DV)]                       FLOAT (53)  NULL,
    [Total Fat (%DV)]                       FLOAT (53)  NULL,
    [Ingredient Statement]                  FLOAT (53)  NULL,
    [Calculated Weight/Serving (g)]         FLOAT (53)  NULL,
    [Specific Gravity]                      SQL_VARIANT NULL,
    [Count per Unit]                        FLOAT (53)  NULL,
    [Appearance]                            FLOAT (53)  NULL,
    [Color]                                 FLOAT (53)  NULL,
    [Aroma/Smell]                           FLOAT (53)  NULL,
    [Flavor/Taste]                          FLOAT (53)  NULL,
    [Texture/Feel]                          FLOAT (53)  NULL,
    [Halal]                                 FLOAT (53)  NULL,
    [Label Comments]                        FLOAT (53)  NULL,
    [Label Comments1]                       SQL_VARIANT NULL,
    [Label Comments2]                       FLOAT (53)  NULL,
    [Label Comments3]                       SQL_VARIANT NULL,
    [GMO Status]                            FLOAT (53)  NULL,
    [GMO Status1]                           FLOAT (53)  NULL,
    [Gluten Ingredients Status]             FLOAT (53)  NULL,
    [Lacto-ovo Vegetarian]                  FLOAT (53)  NULL,
    [Vegan]                                 FLOAT (53)  NULL,
    [Qualify for "Made in America Program"] FLOAT (53)  NULL,
    [Salsify Record Type]                   FLOAT (53)  NULL,
    [Vitamin D (mcg)/Serving]               FLOAT (53)  NULL,
    [Calcium (DV%)]                         SQL_VARIANT NULL,
    [Iron (DV%)]                            FLOAT (53)  NULL,
    [Potassium (DV%)]                       FLOAT (53)  NULL,
    [Servings Per Container]                FLOAT (53)  NULL,
    [Product Status]                        FLOAT (53)  NULL,
    [Organic Certifying Body]               FLOAT (53)  NULL,
    [Certified Organic Agent]               FLOAT (53)  NULL,
    [Channels]                              FLOAT (53)  NULL,
    [Channels1]                             FLOAT (53)  NULL,
    [Channels2]                             FLOAT (53)  NULL
);

