CREATE TABLE [dbo].[PURCHTABLE] (
    [PURCHID]                            NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PURCHNAME]                          NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [ORDERACCOUNT]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEACCOUNT]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [FREIGHTZONE]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [EMAIL]                              NVARCHAR (80)    DEFAULT ('') NOT NULL,
    [DELIVERYDATE]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [DELIVERYTYPE]                       INT              DEFAULT ((0)) NOT NULL,
    [ADDRESSREFRECID]                    BIGINT           DEFAULT ((0)) NOT NULL,
    [ADDRESSREFTABLEID]                  INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYORIGINALSALESID]        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYORIGINALCUSTACCOUNT]    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CURRENCYCODE]                       NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [PAYMENT]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISC]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [COUNTYORIGDEST]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYDIRECTDELIVERY]         INT              DEFAULT ((0)) NOT NULL,
    [VENDGROUP]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LINEDISC]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DISCPERCENT]                        NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [PRICEGROUPID]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MULTILINEDISC]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENDDISC]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYCUSTPURCHORDERFORMNUM]  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [TAXGROUP]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVTERM]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVMODE]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PURCHSTATUS]                        INT              DEFAULT ((0)) NOT NULL,
    [MARKUPGROUP]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PURCHASETYPE]                       INT              DEFAULT ((0)) NOT NULL,
    [URL]                                NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [POSTINGPROFILE]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSACTIONCODE]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENTERPRISENUMBER]                   NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [SETTLEVOUCHER]                      INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYALLOWINDIRECTCREATION]  INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYORIGIN]                 INT              DEFAULT ((0)) NOT NULL,
    [CASHDISCPERCENT]                    NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [DELIVERYNAME]                       NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [COVSTATUS]                          INT              DEFAULT ((0)) NOT NULL,
    [PAYMENTSCHED]                       NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [INVENTSITEID]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ONETIMEVENDOR]                      INT              DEFAULT ((0)) NOT NULL,
    [RETURNITEMNUM]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FREIGHTSLIPTYPE]                    INT              DEFAULT ((0)) NOT NULL,
    [DOCUMENTSTATUS]                     INT              DEFAULT ((0)) NOT NULL,
    [CONTACTPERSONID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONID]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ITEMBUYERGROUPID]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PROJID]                             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PURCHPOOLID]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VATNUM]                             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PORT]                               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INCLTAX]                            INT              DEFAULT ((0)) NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]         NVARCHAR (140)   DEFAULT ('') NOT NULL,
    [NUMBERSEQUENCEGROUP]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LANGUAGEID]                         NVARCHAR (7)     DEFAULT ('') NOT NULL,
    [AUTOSUMMARYMODULETYPE]              INT              DEFAULT ((0)) NOT NULL,
    [TRANSPORT]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMMODE]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMSPEC]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FIXEDDUEDATE]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [STATPROCID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VENDORREF]                          NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYCOMPANYID]              NVARCHAR (4)     DEFAULT ('') NOT NULL,
    [INTERCOMPANYSALESID]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYORDER]                  INT              DEFAULT ((0)) NOT NULL,
    [RETURNREASONCODEID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETURNREPLACEMENTCREATED]           INT              DEFAULT ((0)) NOT NULL,
    [REQATTENTION]                       NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [DEFAULTDIMENSION]                   BIGINT           DEFAULT ((0)) NOT NULL,
    [CONFIRMEDDLVEARLIEST]               DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CONTRACTNUM_SA]                     NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [CHANGEREQUESTREQUIRED]              INT              DEFAULT ((0)) NOT NULL,
    [REASONTABLEREF]                     BIGINT           DEFAULT ((0)) NOT NULL,
    [DOCUMENTSTATE]                      INT              DEFAULT ((0)) NOT NULL,
    [ISMODIFIED]                         INT              DEFAULT ((0)) NOT NULL,
    [MATCHINGAGREEMENT]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [SYSTEMENTRYSOURCE]                  INT              DEFAULT ((0)) NOT NULL,
    [SYSTEMENTRYCHANGEPOLICY]            BIGINT           DEFAULT ((0)) NOT NULL,
    [MANUALENTRYCHANGEPOLICY]            BIGINT           DEFAULT ((0)) NOT NULL,
    [VENDINVOICEDECLARATION_IS]          BIGINT           DEFAULT ((0)) NOT NULL,
    [WORKERPURCHPLACER]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [DELIVERYPOSTALADDRESS]              BIGINT           DEFAULT ((0)) NOT NULL,
    [BANKDOCUMENTTYPE]                   INT              DEFAULT ((0)) NOT NULL,
    [LISTCODE]                           INT              DEFAULT ((0)) NOT NULL,
    [ISENCUMBRANCEREQUIRED]              INT              DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTLINE]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTHEADER]               BIGINT           DEFAULT ((0)) NOT NULL,
    [REQUESTER]                          BIGINT           DEFAULT ((0)) NOT NULL,
    [ACCOUNTINGDISTRIBUTIONTEMPLATE]     BIGINT           DEFAULT ((0)) NOT NULL,
    [ACCOUNTINGDATE]                     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [FINALIZECLOSINGDATE]                DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CONSTARGET_JP]                      INT              DEFAULT ((0)) NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]        DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [UNITEDVATINVOICE_LT]                INT              DEFAULT ((0)) NOT NULL,
    [INTRASTATADDVALUE_LV]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVOICEREGISTER_LT]                 INT              DEFAULT ((0)) NOT NULL,
    [PACKINGSLIPREGISTER_LT]             INT              DEFAULT ((0)) NOT NULL,
    [SERVICENAME]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SERVICEADDRESS]                     NVARCHAR (250)   DEFAULT ('') NOT NULL,
    [ONETIMESUPPLIER]                    INT              DEFAULT ((0)) NOT NULL,
    [SERVICEDATE]                        DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CONFIRMEDDLV]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [FSHAUTOCREATED]                     INT              DEFAULT ((0)) NOT NULL,
    [CROSSDOCKINGDATE]                   DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [SERVICECATEGORY]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [AVAILSALESDATE]                     DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [LOCALDELIVERYDATE]                  DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [REPLENISHMENTLOCATION]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETAILRETAILSTATUSTYPE]             INT              DEFAULT ((0)) NOT NULL,
    [RETAILDRIVERDETAILS]                NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [RETAILCONCESSIONPURCH]              INT              DEFAULT ((0)) NOT NULL,
    [CONFIRMINGPO]                       BIGINT           DEFAULT ((0)) NOT NULL,
    [MCRDROPSHIPMENT]                    INT              DEFAULT ((0)) NOT NULL,
    [EXCHANGERATEDATE]                   DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [FIXEDEXCHRATE]                      NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TAMVENDREBATEGROUPID]               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [TAXPERIODPAYMENTCODE_PL]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSPORTATIONDOCUMENT]             BIGINT           DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                    DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [CREATEDBY]                          NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [DATAAREAID]                         NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                         INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                          BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                              BIGINT           NOT NULL,
    [ROLAGENT]                           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ROLREQUESTEDSHIPDATEFROM]           DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [ROLREQUESTEDSHIPDATETO]             DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [ROLDELIVERYTERMSDESCRIPTION]        NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [ROLPORTDISCHARGE]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ROLSHIPNAME]                        NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [ROLSHIPPOSTALADDRESS]               BIGINT           DEFAULT ((0)) NOT NULL,
    [ROLACCRUALAMOUNT]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ROLADJUSTMENTAMOUNT]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ROLINVOICEAMOUNT]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ROLLANDEDCOSTBALANCE]               NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ROLLANDEDCOSTDONESTATUS]            INT              DEFAULT ((0)) NOT NULL,
    [ROLWIPACCRUALAMOUNT]                NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [EDIPOSTATUS]                        INT              DEFAULT ((0)) NOT NULL,
    [EDIPURCHTRANSFERCONFIRMATIONSTATUS] INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_345PURCHIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [PURCHID] ASC),
    CHECK ([RECID]<>(0))
);

