CREATE TABLE [dbo].[ROLCONTAINERBUILDDETAILS] (
    [CONTAINERID]   NVARCHAR (20) NOT NULL,
    [PURCHID]       NVARCHAR (20) NOT NULL,
    [STATUS10PLUS2] INT           NOT NULL,
    [DATAAREAID]    NVARCHAR (4)  NOT NULL,
    [RECVERSION]    INT           NOT NULL,
    [PARTITION]     BIGINT        NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    CONSTRAINT [I_106218RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

