CREATE TABLE [dbo].[ROLCONTAINERBUILDHEADER] (
    [CONTAINERID]   NVARCHAR (20) NOT NULL,
    [CONTAINERTYPE] NVARCHAR (30) NOT NULL,
    [IMPORTCONTACT] BIGINT        NOT NULL,
    [LOADTYPE]      NVARCHAR (30) NOT NULL,
    [DATAAREAID]    NVARCHAR (4)  NOT NULL,
    [RECVERSION]    INT           NOT NULL,
    [PARTITION]     BIGINT        NOT NULL,
    [RECID]         BIGINT        NOT NULL,
    CONSTRAINT [I_106194CONTAINERIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [CONTAINERID] ASC)
);

