CREATE TABLE [dbo].[ROLPROMOTIONSAPPLICATIONWB] (
    [ACCRUALJOURNALNUMBER] NVARCHAR (10)    NOT NULL,
    [AMOUNT]               NUMERIC (32, 16) NOT NULL,
    [CONTRACTPRICE]        NUMERIC (32, 16) NOT NULL,
    [CUSTOMERID]           NVARCHAR (20)    NOT NULL,
    [CUSTOMERNAME]         NVARCHAR (100)   NOT NULL,
    [CUSTOMERTOCREDIT]     NVARCHAR (20)    NOT NULL,
    [DISTINVOICENUMBER]    NVARCHAR (12)    NOT NULL,
    [ENDCUSTOMERID]        NVARCHAR (20)    NOT NULL,
    [ENDCUSTOMERNAME]      NVARCHAR (100)   NOT NULL,
    [IBBTYPE]              NVARCHAR (4)     NOT NULL,
    [ITEMDESCRIPTION]      NVARCHAR (60)    NOT NULL,
    [ITEMID]               NVARCHAR (20)    NOT NULL,
    [POSTEDDATE]           DATETIME         NOT NULL,
    [PROCESSJOURNALNUMBER] NVARCHAR (10)    NOT NULL,
    [PROCESSONREBATE]      INT              NOT NULL,
    [SALESID]              NVARCHAR (20)    NOT NULL,
    [SALESINVOICEID]       NVARCHAR (20)    NOT NULL,
    [SENDTO]               INT              NOT NULL,
    [STATUS]               INT              NOT NULL,
    [STATUSPWB]            INT              NOT NULL,
    [TAAID]                NVARCHAR (10)    NOT NULL,
    [TRANSACTIONNUMBER]    NVARCHAR (20)    NOT NULL,
    [TRANSDATE]            DATETIME         NOT NULL,
    [TYPE]                 NVARCHAR (4)     NOT NULL,
    [VENDORTOPAY]          NVARCHAR (20)    NOT NULL,
    [DATAAREAID]           NVARCHAR (4)     NOT NULL,
    [RECVERSION]           INT              NOT NULL,
    [PARTITION]            BIGINT           NOT NULL,
    [RECID]                BIGINT           NOT NULL,
    [IBBDISTINVOICENUMBER] NVARCHAR (12)    NOT NULL,
    [CURRENCY]             NVARCHAR (3)     NOT NULL
);

