CREATE TABLE [dbo].[ROLVESSELNAMETABLE] (
    [ACTIVE]      INT            NOT NULL,
    [DESCRIPTION] NVARCHAR (60)  NOT NULL,
    [IMONUMBER]   INT            NOT NULL,
    [MMSINUMBER]  INT            NOT NULL,
    [URL]         NVARCHAR (255) NOT NULL,
    [VESSELNAME]  NVARCHAR (30)  NOT NULL,
    [DATAAREAID]  NVARCHAR (4)   NOT NULL,
    [RECVERSION]  INT            NOT NULL,
    [PARTITION]   BIGINT         NOT NULL,
    [RECID]       BIGINT         NOT NULL,
    CONSTRAINT [I_106239RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

