CREATE TABLE [dbo].[SALESTABLE] (
    [SALESID]                               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SALESNAME]                             NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [RESERVATION]                           INT              DEFAULT ((0)) NOT NULL,
    [CUSTACCOUNT]                           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEACCOUNT]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DELIVERYDATE]                          DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [URL]                                   NVARCHAR (255)   DEFAULT ('') NOT NULL,
    [PURCHORDERFORMNUM]                     NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SALESGROUP]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FREIGHTSLIPTYPE]                       INT              DEFAULT ((0)) NOT NULL,
    [DOCUMENTSTATUS]                        INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYORIGINALSALESID]           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CURRENCYCODE]                          NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [PAYMENT]                               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISC]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TAXGROUP]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LINEDISC]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CUSTGROUP]                             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DISCPERCENT]                           NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYORIGINALCUSTACCOUNT]       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PRICEGROUPID]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MULTILINEDISC]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENDDISC]                               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CUSTOMERREF]                           NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [COUNTYORIGDEST]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LISTCODE]                              INT              DEFAULT ((0)) NOT NULL,
    [DLVTERM]                               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVMODE]                               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PURCHID]                               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SALESSTATUS]                           INT              DEFAULT ((0)) NOT NULL,
    [MARKUPGROUP]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SALESTYPE]                             INT              DEFAULT ((0)) NOT NULL,
    [SALESPOOLID]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [POSTINGPROFILE]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSACTIONCODE]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYAUTOCREATEORDERS]          INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYDIRECTDELIVERY]            INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYDIRECTDELIVERYORIG]        INT              DEFAULT ((0)) NOT NULL,
    [SETTLEVOUCHER]                         INT              DEFAULT ((0)) NOT NULL,
    [ENTERPRISENUMBER]                      NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYALLOWINDIRECTCREATION]     INT              DEFAULT ((0)) NOT NULL,
    [INTERCOMPANYALLOWINDIRECTCREATIONORIG] INT              DEFAULT ((0)) NOT NULL,
    [DELIVERYNAME]                          NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [ONETIMECUSTOMER]                       INT              DEFAULT ((0)) NOT NULL,
    [COVSTATUS]                             INT              DEFAULT ((0)) NOT NULL,
    [COMMISSIONGROUP]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMENTSCHED]                          NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYORIGIN]                    INT              DEFAULT ((0)) NOT NULL,
    [EMAIL]                                 NVARCHAR (80)    DEFAULT ('') NOT NULL,
    [FREIGHTZONE]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RETURNITEMNUM]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISCPERCENT]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CONTACTPERSONID]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DEADLINE]                              DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [PROJID]                                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTLOCATIONID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ADDRESSREFTABLEID]                     INT              DEFAULT ((0)) NOT NULL,
    [VATNUM]                                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PORT]                                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [INCLTAX]                               INT              DEFAULT ((0)) NOT NULL,
    [EINVOICELINESPEC]                      INT              DEFAULT ((0)) NOT NULL,
    [NUMBERSEQUENCEGROUP]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FIXEDEXCHRATE]                         NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [LANGUAGEID]                            NVARCHAR (7)     DEFAULT ('') NOT NULL,
    [AUTOSUMMARYMODULETYPE]                 INT              DEFAULT ((0)) NOT NULL,
    [GIROTYPE]                              INT              DEFAULT ((0)) NOT NULL,
    [SALESORIGINID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ESTIMATE]                              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TRANSPORT]                             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMMODE]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMSPEC]                              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FIXEDDUEDATE]                          DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [EXPORTREASON]                          NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [STATPROCID]                            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]            NVARCHAR (140)   DEFAULT ('') NOT NULL,
    [INTERCOMPANYCOMPANYID]                 NVARCHAR (4)     DEFAULT ('') NOT NULL,
    [INTERCOMPANYPURCHID]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INTERCOMPANYORDER]                     INT              DEFAULT ((0)) NOT NULL,
    [DLVREASON]                             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [QUOTATIONID]                           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RECEIPTDATEREQUESTED]                  DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [RECEIPTDATECONFIRMED]                  DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [SHIPPINGDATEREQUESTED]                 DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [SHIPPINGDATECONFIRMED]                 DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [EINVOICEACCOUNTCODE]                   NVARCHAR (35)    DEFAULT ('') NOT NULL,
    [ITEMTAGGING]                           INT              DEFAULT ((0)) NOT NULL,
    [CASETAGGING]                           INT              DEFAULT ((0)) NOT NULL,
    [PALLETTAGGING]                         INT              DEFAULT ((0)) NOT NULL,
    [ADDRESSREFRECID]                       BIGINT           DEFAULT ((0)) NOT NULL,
    [CUSTINVOICEID]                         NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTSITEID]                          NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DEFAULTDIMENSION]                      BIGINT           DEFAULT ((0)) NOT NULL,
    [CREDITCARDCUSTREFID]                   BIGINT           DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERACCOUNT]                    NVARCHAR (25)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SHIPCARRIERFUELSURCHARGE]              INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERBLINDSHIPMENT]              INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERDELIVERYCONTACT]            NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [CREDITCARDAPPROVALAMOUNT]              NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [CREDITCARDAUTHORIZATION]               NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RETURNDEADLINE]                        DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [RETURNREPLACEMENTID]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RETURNSTATUS]                          INT              DEFAULT ((0)) NOT NULL,
    [RETURNREASONCODEID]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CREDITCARDAUTHORIZATIONERROR]          INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERACCOUNTCODE]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RETURNREPLACEMENTCREATED]              INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERDLVTYPE]                    INT              DEFAULT ((0)) NOT NULL,
    [DELIVERYDATECONTROLTYPE]               INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIEREXPEDITEDSHIPMENT]          INT              DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERRESIDENTIAL]                INT              DEFAULT ((0)) NOT NULL,
    [MATCHINGAGREEMENT]                     BIGINT           DEFAULT ((0)) NOT NULL,
    [SYSTEMENTRYSOURCE]                     INT              DEFAULT ((0)) NOT NULL,
    [SYSTEMENTRYCHANGEPOLICY]               BIGINT           DEFAULT ((0)) NOT NULL,
    [MANUALENTRYCHANGEPOLICY]               BIGINT           DEFAULT ((0)) NOT NULL,
    [DELIVERYPOSTALADDRESS]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERPOSTALADDRESS]              BIGINT           DEFAULT ((0)) NOT NULL,
    [SHIPCARRIERNAME]                       NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [WORKERSALESTAKER]                      BIGINT           DEFAULT ((0)) NOT NULL,
    [SOURCEDOCUMENTHEADER]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [BANKDOCUMENTTYPE]                      INT              DEFAULT ((0)) NOT NULL,
    [SALESUNITID]                           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SMMSALESAMOUNTTOTAL]                   NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [SMMCAMPAIGNID]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CUSTOMSEXPORTORDER_IN]                 INT              DEFAULT ((0)) NOT NULL,
    [CUSTOMSSHIPPINGBILL_IN]                INT              DEFAULT ((0)) NOT NULL,
    [TDSGROUP_IN]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TCSGROUP_IN]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NATUREOFASSESSEE_IN]                   INT              DEFAULT ((0)) NOT NULL,
    [CONSTARGET_JP]                         INT              DEFAULT ((0)) NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]           DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [UNITEDVATINVOICE_LT]                   INT              DEFAULT ((0)) NOT NULL,
    [INTRASTATADDVALUE_LV]                  NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [INVOICEREGISTER_LT]                    INT              DEFAULT ((0)) NOT NULL,
    [PACKINGSLIPREGISTER_LT]                INT              DEFAULT ((0)) NOT NULL,
    [BANKACCOUNT_LV]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISCBASEDATE]                      DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CASHDISCBASEDAYS]                      INT              DEFAULT ((0)) NOT NULL,
    [CREDITNOTEREASONCODE]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [CURBANKACCOUNT_LV]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CUSTBANKACCOUNT_LV]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DAXINTEGRATIONID]                      UNIQUEIDENTIFIER DEFAULT ('{00000000-0000-0000-0000-000000000000}') NOT NULL,
    [DIRECTDEBITMANDATE]                    BIGINT           DEFAULT ((0)) NOT NULL,
    [FISCALDOCTYPE_PL]                      INT              DEFAULT ((0)) NOT NULL,
    [MCRORDERSTOPPED]                       INT              DEFAULT ((0)) NOT NULL,
    [PDSBATCHATTRIBAUTORES]                 INT              DEFAULT ((0)) NOT NULL,
    [PDSCUSTREBATEGROUPID]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PDSREBATEPROGRAMTMAGROUP]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RELEASESTATUS]                         INT              DEFAULT ((0)) NOT NULL,
    [TAXPERIODPAYMENTCODE_PL]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [TRANSPORTATIONDOCUMENT]                BIGINT           DEFAULT ((0)) NOT NULL,
    [WORKERSALESRESPONSIBLE]                BIGINT           DEFAULT ((0)) NOT NULL,
    [RETAILCHANNELTABLE]                    BIGINT           DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]                      DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_MODIFIEDTIME]                      INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]                            NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [MODIFIEDTRANSACTIONID]                 BIGINT           DEFAULT ((0)) NOT NULL,
    [CREATEDDATETIME]                       DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                       INT              DEFAULT ((0)) NOT NULL,
    [CREATEDBY]                             NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDTRANSACTIONID]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [DATAAREAID]                            NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                            INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                             BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                                 BIGINT           NOT NULL,
    [VSIDELIVERYADDRESSRECID]               BIGINT           DEFAULT ((0)) NOT NULL,
    [ROLCREDITHOLDRELEASED]                 INT              DEFAULT ((0)) NOT NULL,
    [ROLCROSSDOCKDELIVERYNAME]              NVARCHAR (100)   DEFAULT ('') NOT NULL,
    [ROLCROSSDOCKDELIVERYPOSTALADDRESS]     BIGINT           DEFAULT ((0)) NOT NULL,
    [ROLORDERCREDITHOLDSTOPPED]             INT              DEFAULT ((0)) NOT NULL,
    [ROLPROFORMA]                           INT              DEFAULT ((0)) NOT NULL,
    [ROLRELEASEDBY]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ROLRELEASEDON]                         DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [ROLRELEASEDONTZID]                     INT              DEFAULT ((37001)) NOT NULL,
    [ROLWMSARN]                             NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [ROLWMSCONFIRMSTATUS]                   INT              DEFAULT ((0)) NOT NULL,
    [ROLWMSRESERVEDSTATUS]                  INT              DEFAULT ((0)) NOT NULL,
    [ROLEDIREVIEWED]                        INT              DEFAULT ((0)) NOT NULL,
    [VSIMARKFORADDRESSRECID]                BIGINT           DEFAULT ((0)) NOT NULL,
    [RSMRFLI_EDIDUNSNUMBER]                 NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [PALLETTAGGING1]                        INT              DEFAULT ((0)) NOT NULL,
    [RSMREBILLORDER]                        INT              DEFAULT ((0)) NOT NULL,
    [RSMRETURNDISPOSITIONCODEID]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [RSMWMSLOCATIONID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    CONSTRAINT [I_366SALESIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [SALESID] ASC),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [DR_INDX_CUSTACCOUNT]
    ON [dbo].[SALESTABLE]([CUSTACCOUNT] ASC);

