CREATE TABLE [dbo].[SalsifyProductFeed] (
    [SKU]                                   NVARCHAR (1000) NULL,
    [Name]                                  NVARCHAR (1000) NULL,
    [Item Name]                             NVARCHAR (1000) NULL,
    [Product Name]                          NVARCHAR (1000) NULL,
    [Computed - Pack Size]                  NVARCHAR (1000) NULL,
    [Unit Quantity]                         NVARCHAR (1000) NULL,
    [Unit Size]                             NVARCHAR (1000) NULL,
    [Brand Name]                            NVARCHAR (1000) NULL,
    [Disabled]                              NVARCHAR (1000) NULL,
    [Product Category 1]                    NVARCHAR (1000) NULL,
    [Product Category 2]                    NVARCHAR (1000) NULL,
    [Supplier Engagement Specialist]        NVARCHAR (1000) NULL,
    [Buyer Name]                            NVARCHAR (1000) NULL,
    [Item UPC]                              NVARCHAR (1000) NULL,
    [Inside UPC Code]                       NVARCHAR (1000) NULL,
    [Outside UPC Code]                      NVARCHAR (1000) NULL,
    [Master Pack]                           NVARCHAR (1000) NULL,
    [Effective Date (mmddyyyy)]             NVARCHAR (1000) NULL,
    [Supersedes (mmddyyyy)]                 NVARCHAR (1000) NULL,
    [Reason for Change]                     NVARCHAR (1000) NULL,
    [Revised By]                            NVARCHAR (1000) NULL,
    [File]                                  NVARCHAR (1000) NULL,
    [Pack Size]                             NVARCHAR (1000) NULL,
    [Pack1]                                 NVARCHAR (1000) NULL,
    [Pack2]                                 NVARCHAR (1000) NULL,
    [Supplier #1]                           NVARCHAR (1000) NULL,
    [Supplier # 10 COO]                     NVARCHAR (1000) NULL,
    [Supplier #10]                          NVARCHAR (1000) NULL,
    [Supplier #10 Kosher]                   NVARCHAR (1000) NULL,
    [Supplier #11]                          NVARCHAR (1000) NULL,
    [Supplier # 11 COO]                     NVARCHAR (1000) NULL,
    [Supplier #11 Kosher]                   NVARCHAR (1000) NULL,
    [Supplier #1 COO]                       NVARCHAR (1000) NULL,
    [Supplier #2]                           NVARCHAR (1000) NULL,
    [Supplier #1 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #2 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #2 COO]                       NVARCHAR (1000) NULL,
    [Supplier # 3 COO]                      NVARCHAR (1000) NULL,
    [Supplier #3]                           NVARCHAR (1000) NULL,
    [Supplier #3 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #4]                           NVARCHAR (1000) NULL,
    [Supplier #4 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier # 4 COO]                      NVARCHAR (1000) NULL,
    [Supplier #5]                           NVARCHAR (1000) NULL,
    [Supplier # 5 COO]                      NVARCHAR (1000) NULL,
    [Supplier #5 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #6]                           NVARCHAR (1000) NULL,
    [Supplier # 6 COO]                      NVARCHAR (1000) NULL,
    [Supplier #6 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier # 7 COO]                      NVARCHAR (1000) NULL,
    [Supplier #7]                           NVARCHAR (1000) NULL,
    [Supplier #7 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #8]                           NVARCHAR (1000) NULL,
    [Supplier # 8 COO]                      NVARCHAR (1000) NULL,
    [Supplier #8 Kosher]                    NVARCHAR (1000) NULL,
    [Supplier #9]                           NVARCHAR (1000) NULL,
    [Supplier # 9 COO]                      NVARCHAR (1000) NULL,
    [Supplier #9 Kosher]                    NVARCHAR (1000) NULL,
    [Case Length (in)]                      NVARCHAR (1000) NULL,
    [Case Width (in)]                       NVARCHAR (1000) NULL,
    [Case Height (in)]                      NVARCHAR (1000) NULL,
    [Case Net Weight (lb)]                  NVARCHAR (1000) NULL,
    [Case Gross Weight (lb)]                NVARCHAR (1000) NULL,
    [Case Tare Weight (lb)]                 NVARCHAR (1000) NULL,
    [Pallet Hi]                             NVARCHAR (1000) NULL,
    [Pallet Tie]                            NVARCHAR (1000) NULL,
    [Gross Pallet Weight (lb)]              NVARCHAR (1000) NULL,
    [Cases Per Pallet]                      NVARCHAR (1000) NULL,
    [Case Cube (ft3)]                       NVARCHAR (1000) NULL,
    [Packaging Type]                        NVARCHAR (1000) NULL,
    [Net Weight (Unit Label)]               NVARCHAR (1000) NULL,
    [Net Weight Formula]                    NVARCHAR (1000) NULL,
    [DR Weight Formula]                     NVARCHAR (1000) NULL,
    [DR Weight (Unit Label)]                NVARCHAR (1000) NULL,
    [DR WT Unit (use: g, kg, OZ, LB)]       NVARCHAR (1000) NULL,
    [Packaging Tare Weight (g)]             NVARCHAR (1000) NULL,
    [Shelf Life Days (Unopened)]            NVARCHAR (1000) NULL,
    [Unopened Storage Condition]            NVARCHAR (1000) NULL,
    [Shelf Life After Opening (Days)]       NVARCHAR (1000) NULL,
    [Opened Storage Condition]              NVARCHAR (1000) NULL,
    [Ship Contidions (Sales)]               NVARCHAR (1000) NULL,
    [Calories (kcal)/100g]                  NVARCHAR (1000) NULL,
    [Calories from Fat (kcal)/100g]         NVARCHAR (1000) NULL,
    [Total Fat (g)/100g]                    NVARCHAR (1000) NULL,
    [Saturated Fat (g)/100g]                NVARCHAR (1000) NULL,
    [Unsaturated Fat (g)/100g]              NVARCHAR (1000) NULL,
    [Polyunsaturated Fat (g)/100g]          NVARCHAR (1000) NULL,
    [Calcium (mg)/100g]                     NVARCHAR (1000) NULL,
    [Added Sugar (g)/100g]                  NVARCHAR (1000) NULL,
    [Cholesterol (mg)/100g]                 NVARCHAR (1000) NULL,
    [Iron (mg)/100g]                        NVARCHAR (1000) NULL,
    [Dietary Fiber (g)/100g]                NVARCHAR (1000) NULL,
    [Monounsaturated Fat (g)/100g]          NVARCHAR (1000) NULL,
    [Moisture/Ash (g)/100g]                 NVARCHAR (1000) NULL,
    [Protein (g)/100g]                      NVARCHAR (1000) NULL,
    [Potassium (mg)/100g]                   NVARCHAR (1000) NULL,
    [Total Carbohydrate (g)/100g]           NVARCHAR (1000) NULL,
    [Sodium (mg)/100g]                      NVARCHAR (1000) NULL,
    [Trans Fat (g)/100g]                    NVARCHAR (1000) NULL,
    [Total Sugar (g)/100g]                  NVARCHAR (1000) NULL,
    [Vitamin C (mg)/100g]                   NVARCHAR (1000) NULL,
    [Vitamin A (mcg)/100g]                  NVARCHAR (1000) NULL,
    [Vitamin D (mcg)/100g]                  NVARCHAR (1000) NULL,
    [Calories (kcal)/Serving]               NVARCHAR (1000) NULL,
    [Total Fat (g)/Serving]                 NVARCHAR (1000) NULL,
    [Saturated Fat (g)/Serving]             NVARCHAR (1000) NULL,
    [Added Sugar (g)/Serving]               NVARCHAR (1000) NULL,
    [Monounsaturated Fat (g)/Serving]       NVARCHAR (1000) NULL,
    [Dietary Fiber (g)/Serving]             NVARCHAR (1000) NULL,
    [Protein (g)/Serving]                   NVARCHAR (1000) NULL,
    [Polyunsaturated Fat (g)/Serving]       NVARCHAR (1000) NULL,
    [Total Sugar (g)/Serving]               NVARCHAR (1000) NULL,
    [Total Carbs (g)/Serving]               NVARCHAR (1000) NULL,
    [Trans Fat (g)/Serving]                 NVARCHAR (1000) NULL,
    [Unsaturated Fat (g)/Serving]           NVARCHAR (1000) NULL,
    [Calcium (mg)/Serving]                  NVARCHAR (1000) NULL,
    [Cholesterol (mg)/Serving]              NVARCHAR (1000) NULL,
    [Potassium (mg)/Serving]                NVARCHAR (1000) NULL,
    [Iron (mg)/Serving]                     NVARCHAR (1000) NULL,
    [Sodium (mg)/Serving]                   NVARCHAR (1000) NULL,
    [Added Sugars (%DV)]                    NVARCHAR (1000) NULL,
    [Cholesterol (%DV)]                     NVARCHAR (1000) NULL,
    [Saturated Fat (%DV)]                   NVARCHAR (1000) NULL,
    [Dietary Fiber (%DV)]                   NVARCHAR (1000) NULL,
    [Sodium (%DV)]                          NVARCHAR (1000) NULL,
    [Total Carb (%DV)]                      NVARCHAR (1000) NULL,
    [Vitamin D (%DV)]                       NVARCHAR (1000) NULL,
    [Total Fat (%DV)]                       NVARCHAR (1000) NULL,
    [Ingredient Statement]                  NVARCHAR (1000) NULL,
    [Calculated Weight/Serving (g)]         NVARCHAR (1000) NULL,
    [Specific Gravity]                      NVARCHAR (1000) NULL,
    [Count per Unit]                        NVARCHAR (1000) NULL,
    [Appearance]                            NVARCHAR (1000) NULL,
    [Color]                                 NVARCHAR (1000) NULL,
    [Aroma/Smell]                           NVARCHAR (1000) NULL,
    [Flavor/Taste]                          NVARCHAR (1000) NULL,
    [Texture/Feel]                          NVARCHAR (1000) NULL,
    [Halal]                                 NVARCHAR (1000) NULL,
    [Label Comments]                        NVARCHAR (1000) NULL,
    [LabelComments1]                        NVARCHAR (1000) NULL,
    [LabelComments2]                        NVARCHAR (1000) NULL,
    [LabelComments3]                        NVARCHAR (1000) NULL,
    [GMO Status]                            NVARCHAR (1000) NULL,
    [GMO Status1]                           NVARCHAR (1000) NULL,
    [Gluten Ingredients Status]             NVARCHAR (1000) NULL,
    [Lacto-ovo Vegetarian]                  NVARCHAR (1000) NULL,
    [Vegan]                                 NVARCHAR (1000) NULL,
    [Qualify for "Made in America Program"] NVARCHAR (1000) NULL,
    [Salsify Record Type]                   NVARCHAR (1000) NULL,
    [Vitamin D (mcg)/Serving]               NVARCHAR (1000) NULL,
    [Calcium (DV%)]                         NVARCHAR (1000) NULL,
    [Iron (DV%)]                            NVARCHAR (1000) NULL,
    [Potassium (DV%)]                       NVARCHAR (1000) NULL,
    [Servings Per Container]                NVARCHAR (1000) NULL,
    [Product Status]                        NVARCHAR (1000) NULL,
    [Organic Certifying Body]               NVARCHAR (1000) NULL,
    [Certified Organic Agent]               NVARCHAR (1000) NULL,
    [Channels]                              NVARCHAR (1000) NULL,
    [Channels1]                             NVARCHAR (1000) NULL,
    [Channels2]                             NVARCHAR (1000) NULL
);

