CREATE TABLE [dbo].[Sf_Account] (
    [IsDeleted]                                   BIT            NOT NULL,
    [MasterRecordId]                              VARCHAR (18)   NULL,
    [Type]                                        VARCHAR (40)   NULL,
    [RecordTypeId]                                VARCHAR (18)   NULL,
    [ParentId]                                    VARCHAR (18)   NULL,
    [BillingStreet]                               VARCHAR (255)  NULL,
    [BillingCity]                                 VARCHAR (40)   NULL,
    [BillingState]                                VARCHAR (80)   NULL,
    [BillingPostalCode]                           VARCHAR (20)   NULL,
    [BillingCountry]                              VARCHAR (80)   NULL,
    [BillingLatitude]                             REAL           NULL,
    [BillingLongitude]                            REAL           NULL,
    [BillingGeocodeAccuracy]                      VARCHAR (40)   NULL,
    [BillingAddress]                              VARCHAR (255)  NULL,
    [ShippingStreet]                              VARCHAR (255)  NULL,
    [ShippingCity]                                VARCHAR (40)   NULL,
    [ShippingState]                               VARCHAR (80)   NULL,
    [ShippingPostalCode]                          VARCHAR (20)   NULL,
    [ShippingCountry]                             VARCHAR (80)   NULL,
    [ShippingLatitude]                            REAL           NULL,
    [ShippingLongitude]                           REAL           NULL,
    [ShippingGeocodeAccuracy]                     VARCHAR (40)   NULL,
    [ShippingAddress]                             VARCHAR (255)  NULL,
    [AccountNumber]                               VARCHAR (40)   NULL,
    [Website]                                     VARCHAR (255)  NULL,
    [PhotoUrl]                                    VARCHAR (255)  NULL,
    [Industry]                                    VARCHAR (40)   NULL,
    [AnnualRevenue]                               DECIMAL (18)   NULL,
    [NumberOfEmployees]                           INT            NULL,
    [Description]                                 VARCHAR (8000) NULL,
    [OwnerId]                                     VARCHAR (18)   NOT NULL,
    [LastActivityDate]                            DATETIME       NULL,
    [Jigsaw]                                      VARCHAR (20)   NULL,
    [JigsawCompanyId]                             VARCHAR (20)   NULL,
    [AccountSource]                               VARCHAR (40)   NULL,
    [SicDesc]                                     VARCHAR (80)   NULL,
    [Billing_Type__c]                             VARCHAR (255)  NULL,
    [Broker_Number__c]                            VARCHAR (20)   NULL,
    [Channel__c]                                  VARCHAR (255)  NULL,
    [Country_Region__c]                           VARCHAR (255)  NULL,
    [Default_Warehouse_Number__c]                 VARCHAR (30)   NULL,
    [Default_Warehouse__c]                        VARCHAR (255)  NULL,
    [Delivery_Instructions__c]                    VARCHAR (255)  NULL,
    [Freight_Terms__c]                            VARCHAR (255)  NULL,
    [Global_Duns__c]                              VARCHAR (1300) NULL,
    [Metropolitan_Region__c]                      VARCHAR (255)  NULL,
    [National_Account__c]                         BIT            NOT NULL,
    [Non_Disclosure_Agreement_Effective_Date__c]  DATETIME       NULL,
    [Non_Disclosure_Agreement_on_File__c]         VARCHAR (255)  NULL,
    [Order_Number__c]                             VARCHAR (10)   NULL,
    [Price_Book__c]                               VARCHAR (18)   NULL,
    [Primary_Broker__c]                           VARCHAR (18)   NULL,
    [Salesforce_ID__c]                            VARCHAR (1300) NULL,
    [Scheduled_Review_Date__c]                    DATETIME       NULL,
    [Program__c]                                  VARCHAR (255)  NULL,
    [Shipping_Account_Number__c]                  VARCHAR (255)  NULL,
    [State_Region__c]                             VARCHAR (255)  NULL,
    [Trans_ID__c]                                 VARCHAR (30)   NULL,
    [Temp_ID__c]                                  VARCHAR (255)  NULL,
    [CloudingoAgent__BALA__c]                     REAL           NULL,
    [CloudingoAgent__BALO__c]                     REAL           NULL,
    [CloudingoAgent__BAS__c]                      REAL           NULL,
    [CloudingoAgent__BAV__c]                      VARCHAR (1)    NULL,
    [CloudingoAgent__BCD__c]                      VARCHAR (2)    NULL,
    [CloudingoAgent__BRDI__c]                     VARCHAR (12)   NULL,
    [CloudingoAgent__BRT__c]                      VARCHAR (1)    NULL,
    [CloudingoAgent__BTZ__c]                      VARCHAR (48)   NULL,
    [CloudingoAgent__SALA__c]                     REAL           NULL,
    [CloudingoAgent__SALO__c]                     REAL           NULL,
    [CloudingoAgent__SAR__c]                      VARCHAR (1)    NULL,
    [CloudingoAgent__SAS__c]                      REAL           NULL,
    [CloudingoAgent__SAV__c]                      VARCHAR (1)    NULL,
    [CloudingoAgent__SCD__c]                      VARCHAR (2)    NULL,
    [CloudingoAgent__SRDI__c]                     VARCHAR (12)   NULL,
    [CloudingoAgent__STZ__c]                      VARCHAR (48)   NULL,
    [CloudingoAgent__BAR__c]                      VARCHAR (1)    NULL,
    [Tier__c]                                     VARCHAR (255)  NULL,
    [Segment__c]                                  VARCHAR (255)  NULL,
    [LineOfBiz__c]                                VARCHAR (255)  NULL,
    [X2015_Catalog_Sent__c]                       BIT            NOT NULL,
    [Procedure__c]                                VARCHAR (4099) NULL,
    [Documents__c]                                VARCHAR (4099) NULL,
    [SP_Preferred_Currency__c]                    VARCHAR (35)   NULL,
    [SP_Nearest_Port__c]                          VARCHAR (35)   NULL,
    [SP_Are_you_FDA_registered__c]                VARCHAR (255)  NULL,
    [SP_Do_you_currently_export_U_S__c]           VARCHAR (255)  NULL,
    [SP_Certifications__c]                        VARCHAR (4099) NULL,
    [SP_Capabilities__c]                          VARCHAR (4099) NULL,
    [SP_Audit_Type__c]                            VARCHAR (4099) NULL,
    [SP_Third_Party_or_Trade_Affiliations__c]     VARCHAR (100)  NULL,
    [SP_If_other_AT_selected__c]                  VARCHAR (50)   NULL,
    [If_other_selected__c]                        VARCHAR (50)   NULL,
    [SP_Plant_Locations__c]                       VARCHAR (100)  NULL,
    [SP_Packaging_capabilities__c]                VARCHAR (255)  NULL,
    [SP_Number_of_Plants__c]                      REAL           NULL,
    [SP_No_Interest_Reasons__c]                   VARCHAR (5000) NULL,
    [SP_Reason_for_No_Product_Interest__c]        VARCHAR (4099) NULL,
    [SP_What_product_categories__c]               VARCHAR (255)  NULL,
    [SP_Your_highest_sell_product_categories__c]  VARCHAR (255)  NULL,
    [SP_Origin_of_raw_materials__c]               VARCHAR (35)   NULL,
    [SP_What_brands_do_you_produce_product__c]    VARCHAR (255)  NULL,
    [SP_What_channels_do_you_sell_to__c]          VARCHAR (4099) NULL,
    [SP_Ownership__c]                             VARCHAR (255)  NULL,
    [SP_How_long_have_you_been_in_business__c]    VARCHAR (35)   NULL,
    [SP_Have_you_done_business_with_Roland__c]    VARCHAR (255)  NULL,
    [SP_Who_referred_you__c]                      VARCHAR (35)   NULL,
    [SP_Who_are_your_top_three_customers__c]      VARCHAR (255)  NULL,
    [SP_Started_doing_business_with_Roland__c]    VARCHAR (35)   NULL,
    [SP_Percent_of_business_Roland_represents__c] VARCHAR (35)   NULL,
    [SP_Anual_Output__c]                          VARCHAR (35)   NULL,
    [SP_GFSI_Certifications__c]                   VARCHAR (4099) NULL,
    [SP_List_all_quality_certifications__c]       VARCHAR (8000) NULL,
    [Exports_to_these_regions__c]                 VARCHAR (4099) NULL,
    [SP_Average_Materials_Lead_Time_in_weeks__c]  VARCHAR (35)   NULL,
    [SP_Average_Production_Lead_Time_in_weeks__c] VARCHAR (35)   NULL,
    [SP_Market_Supply_Information__c]             VARCHAR (255)  NULL,
    [SP_What_products_should_we_carry__c]         VARCHAR (255)  NULL,
    [Supplier_Number__c]                          VARCHAR (20)   NULL,
    [Account_Record_Type_Box__c]                  VARCHAR (255)  NULL,
    [What_product_categories_do_you_produce__c]   VARCHAR (255)  NULL,
    [Inactive_Active__c]                          BIT            NOT NULL,
    [Bar_Status__c]                               VARCHAR (1300) NULL,
    [Supplier_Status__c]                          VARCHAR (255)  NULL,
    [Documents_Required__c]                       BIT            NOT NULL,
    [PowerofOne_Acct__c]                          REAL           NULL,
    [Rebate_Group_Code1__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code2__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code3__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code5__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code4__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code6__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code7__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code8__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code9__c]                       VARCHAR (20)   NULL,
    [Rebate_Group_Code10__c]                      VARCHAR (20)   NULL,
    [FDA_Registration__c]                         VARCHAR (30)   NULL,
    [Parent_Supplier_Number__c]                   VARCHAR (1300) NULL,
    [FSQA_Active__c]                              BIT            NOT NULL,
    [Parent_FSQA_Active_Status__c]                BIT            NOT NULL,
    [Parent_Active_Status__c]                     BIT            NOT NULL,
    [Verified__c]                                 BIT            NULL,
    [Salesforce_Account_Number__c]                VARCHAR (30)   NOT NULL,
    [Establishment__c]                            VARCHAR (255)  NULL,
    [Cuisine__c]                                  VARCHAR (255)  NULL,
    [Region_of_Operations__c]                     VARCHAR (255)  NULL,
    [Presence__c]                                 VARCHAR (255)  NULL,
    [Owner_ID__c]                                 VARCHAR (1300) NULL,
    [IAM_1__c]                                    VARCHAR (255)  NULL,
    [Culinary_Specialist__c]                      VARCHAR (255)  NULL,
    [Company__c]                                  VARCHAR (20)   NULL,
    [Issues_Challenges__c]                        VARCHAR (255)  NULL,
    [Risk_Impact_Notes__c]                        VARCHAR (255)  NULL,
    [Risk_Impact_Rating__c]                       VARCHAR (255)  NULL,
    [Risk_Likelihood_Notes__c]                    VARCHAR (255)  NULL,
    [Risk_Likelihood_Rating__c]                   VARCHAR (255)  NULL,
    [Satisfaction_Rating_Notes__c]                VARCHAR (255)  NULL,
    [Satisfaction_Rating__c]                      VARCHAR (255)  NULL,
    [Phone]                                       VARCHAR (40)   NULL,
    [Fax]                                         VARCHAR (40)   NULL,
    [LastViewedDate]                              DATETIME       NULL,
    [LastReferencedDate]                          DATETIME       NULL,
    [Id]                                          VARCHAR (18)   NOT NULL,
    [Name]                                        VARCHAR (255)  NOT NULL,
    [CreatedDate]                                 DATETIME       NOT NULL,
    [CreatedById]                                 VARCHAR (18)   NOT NULL,
    [LastModifiedDate]                            DATETIME       NOT NULL,
    [LastModifiedById]                            VARCHAR (18)   NOT NULL,
    [SystemModstamp]                              DATETIME       NOT NULL
);

