CREATE TABLE [dbo].[Sf_Inquiry__c] (
    [OwnerId]                           VARCHAR (18)    NOT NULL,
    [RecordTypeId]                      VARCHAR (18)    NULL,
    [LastActivityDate]                  DATETIME        NULL,
    [Account__c]                        VARCHAR (18)    NULL,
    [Buyer__c]                          VARCHAR (1300)  NULL,
    [Change_Details__c]                 VARCHAR (8000)  NULL,
    [Order_Change_Type__c]              VARCHAR (255)   NULL,
    [Complaint_Details__c]              VARCHAR (8000)  NULL,
    [Complaint_Reason_s__c]             VARCHAR (4099)  NULL,
    [Contact__c]                        VARCHAR (18)    NULL,
    [Description__c]                    VARCHAR (8000)  NULL,
    [Drop_Ship_Order__c]                BIT             NOT NULL,
    [Due_Date__c]                       DATETIME        NULL,
    [Inquiry_Origin__c]                 VARCHAR (255)   NULL,
    [Inquiry_Subject__c]                VARCHAR (60)    NULL,
    [Inquiry_Type__c]                   VARCHAR (1300)  NULL,
    [Order_Inquiry_Type__c]             VARCHAR (255)   NULL,
    [Inspection_Notes__c]               VARCHAR (600)   NULL,
    [Internal_Comments__c]              VARCHAR (8000)  NULL,
    [Item_Number_old__c]                VARCHAR (1300)  NULL,
    [Production_Code__c]                VARCHAR (40)    NULL,
    [Order_Date__c]                     DATETIME        NULL,
    [Order_Stage__c]                    VARCHAR (255)   NULL,
    [Owners_Department__c]              VARCHAR (1300)  NULL,
    [Priority__c]                       VARCHAR (255)   NULL,
    [Product_Description_old__c]        VARCHAR (1300)  NULL,
    [Product_Disposition__c]            VARCHAR (255)   NULL,
    [Product_Inquiry_Type2__c]          VARCHAR (4099)  NULL,
    [Product_Inspection__c]             VARCHAR (255)   NULL,
    [Product_Qty__c]                    REAL            NULL,
    [Product__c]                        VARCHAR (18)    NULL,
    [QA_Assignee__c]                    VARCHAR (1300)  NULL,
    [Reason_for_Change__c]              VARCHAR (8000)  NULL,
    [Request_Details__c]                VARCHAR (255)   NULL,
    [Resolution__c]                     VARCHAR (8000)  NULL,
    [Roland_Order_Number__c]            VARCHAR (20)    NULL,
    [SFDC_Order_Link__c]                VARCHAR (18)    NULL,
    [Shelf_Life_Notes__c]               VARCHAR (8000)  NULL,
    [Shelf_life_age__c]                 VARCHAR (255)   NULL,
    [Product_Development_Request__c]    BIT             NOT NULL,
    [Status__c]                         VARCHAR (255)   NULL,
    [Supplier_Communication_Notes__c]   VARCHAR (8000)  NULL,
    [Supplier_Communication__c]         VARCHAR (255)   NULL,
    [Supplier_Name__c]                  VARCHAR (50)    NULL,
    [Supplier_Number__c]                VARCHAR (12)    NULL,
    [Unable_to_process_this_request__c] BIT             NOT NULL,
    [Waiting_On__c]                     VARCHAR (255)   NULL,
    [Inquiry_Age_Days__c]               REAL            NULL,
    [Closed_Date__c]                    DATETIME        NULL,
    [Account_Number__c]                 VARCHAR (6)     NULL,
    [CreatedByCurrentUserInd__c]        BIT             NOT NULL,
    [Lot_Number__c]                     VARCHAR (8)     NULL,
    [First_Production_Run__c]           BIT             NOT NULL,
    [Inquiry_Age_Hours__c]              REAL            NULL,
    [Inquiry_Age_Minutes__c]            REAL            NULL,
    [Inquiry_Age_HR_MIN__c]             VARCHAR (1300)  NULL,
    [First_Production_Date__c]          DATETIME        NULL,
    [Account_Default_Freight_Terms__c]  VARCHAR (1300)  NULL,
    [Account_WH_Default_del__c]         VARCHAR (1300)  NULL,
    [Item_No__c]                        VARCHAR (1300)  NULL,
    [Program__c]                        BIT             NOT NULL,
    [Quoted_Price_5__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_2__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_3__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_4__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price__c]                   DECIMAL (10, 2) NULL,
    [X2_Item_No__c]                     VARCHAR (1300)  NULL,
    [X2_Item_Number_old__c]             VARCHAR (1300)  NULL,
    [X2_Product__c]                     VARCHAR (18)    NULL,
    [X3_Item_No__c]                     VARCHAR (1300)  NULL,
    [X3_Item_Number_old__c]             VARCHAR (1300)  NULL,
    [X3_Product__c]                     VARCHAR (18)    NULL,
    [X4_Item_No__c]                     VARCHAR (1300)  NULL,
    [X4_Item_Number_old__c]             VARCHAR (1300)  NULL,
    [X4_Product__c]                     VARCHAR (18)    NULL,
    [X5_Item_No__c]                     VARCHAR (1300)  NULL,
    [X5_Item_Number_old__c]             VARCHAR (1300)  NULL,
    [X5_Product__c]                     VARCHAR (18)    NULL,
    [Acct_Record_Type__c]               VARCHAR (1300)  NULL,
    [Acct_Owner__c]                     VARCHAR (1300)  NULL,
    [Contract_Period__c]                VARCHAR (255)   NULL,
    [Volume__c]                         VARCHAR (255)   NULL,
    [Freight_Details__c]                VARCHAR (255)   NULL,
    [Competitor_Info__c]                VARCHAR (255)   NULL,
    [Other_Details__c]                  VARCHAR (8000)  NULL,
    [Item_Number__c]                    VARCHAR (12)    NULL,
    [Product_Name__c]                   VARCHAR (200)   NULL,
    [Product_Description__c]            VARCHAR (4000)  NULL,
    [Buyer_Name__c]                     VARCHAR (100)   NULL,
    [X6_Product__c]                     VARCHAR (18)    NULL,
    [X7_Product__c]                     VARCHAR (18)    NULL,
    [X8_Product__c]                     VARCHAR (18)    NULL,
    [X9_Product__c]                     VARCHAR (18)    NULL,
    [X10_Product__c]                    VARCHAR (18)    NULL,
    [X2_Item_Number__c]                 VARCHAR (12)    NULL,
    [X3_Item_Number__c]                 VARCHAR (12)    NULL,
    [X4_Item_Number__c]                 VARCHAR (12)    NULL,
    [X5_Item_Number__c]                 VARCHAR (12)    NULL,
    [X6_Item_Number__c]                 VARCHAR (12)    NULL,
    [X7_Item_Number__c]                 VARCHAR (12)    NULL,
    [X8_Item_Number__c]                 VARCHAR (12)    NULL,
    [X9_Item_Number__c]                 VARCHAR (12)    NULL,
    [X10_Item_Number__c]                VARCHAR (12)    NULL,
    [X6_Item_No__c]                     VARCHAR (1300)  NULL,
    [X7_Item_No__c]                     VARCHAR (1300)  NULL,
    [X8_Item_No__c]                     VARCHAR (1300)  NULL,
    [X9_Item_No__c]                     VARCHAR (1300)  NULL,
    [X10_Item_No__c]                    VARCHAR (1300)  NULL,
    [Quoted_Price_6__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_7__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_8__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_9__c]                 DECIMAL (10, 2) NULL,
    [Quoted_Price_10__c]                DECIMAL (10, 2) NULL,
    [Warehouse_Number__c]               VARCHAR (255)   NULL,
    [Id]                                VARCHAR (18)    NOT NULL,
    [IsDeleted]                         BIT             NOT NULL,
    [Name]                              VARCHAR (80)    NOT NULL,
    [CreatedDate]                       DATETIME        NOT NULL,
    [CreatedById]                       VARCHAR (18)    NOT NULL,
    [LastModifiedDate]                  DATETIME        NOT NULL,
    [LastModifiedById]                  VARCHAR (18)    NOT NULL,
    [SystemModstamp]                    DATETIME        NOT NULL,
    [LastViewedDate]                    DATETIME        NULL,
    [LastReferencedDate]                DATETIME        NULL
);

