CREATE TABLE [dbo].[Sf_Lost_Placement__c] (
    [Id]                          VARCHAR (18)   NOT NULL,
    [OwnerId]                     VARCHAR (18)   NOT NULL,
    [IsDeleted]                   BIT            NOT NULL,
    [Name]                        VARCHAR (80)   NULL,
    [CreatedDate]                 DATETIME       NOT NULL,
    [CreatedById]                 VARCHAR (18)   NOT NULL,
    [LastModifiedDate]            DATETIME       NOT NULL,
    [LastModifiedById]            VARCHAR (18)   NOT NULL,
    [SystemModstamp]              DATETIME       NOT NULL,
    [LastActivityDate]            DATETIME       NULL,
    [LastViewedDate]              DATETIME       NULL,
    [LastReferencedDate]          DATETIME       NULL,
    [Division_Name__c]            VARCHAR (80)   NULL,
    [Flagged_because__c]          VARCHAR (255)  NULL,
    [Follup_UP__c]                VARCHAR (255)  NULL,
    [Item__c]                     VARCHAR (12)   NULL,
    [Reason_for_Decl__c]          VARCHAR (255)  NULL,
    [Reason_for_Decline_Notes__c] VARCHAR (255)  NULL,
    [Secondary_Owner__c]          VARCHAR (18)   NULL,
    [Status__c]                   VARCHAR (255)  NULL,
    [Why_Not__c]                  VARCHAR (252)  NULL,
    [related_to__c]               VARCHAR (18)   NULL,
    [Buyer_Name__c]               VARCHAR (1300) NULL,
    [Buyer__c]                    VARCHAR (1300) NULL,
    [Notify_Buyer__c]             BIT            NOT NULL,
    [Product_Name__c]             VARCHAR (18)   NULL
);

