CREATE TABLE [dbo].[Sf_OpportunityLineItem] (
    [OpportunityId]          VARCHAR (18)    NOT NULL,
    [SortOrder]              INT             NULL,
    [PricebookEntryId]       VARCHAR (18)    NULL,
    [Product2Id]             VARCHAR (18)    NULL,
    [ProductCode]            VARCHAR (255)   NULL,
    [Quantity]               REAL            NOT NULL,
    [TotalPrice]             DECIMAL (18, 2) NULL,
    [UnitPrice]              DECIMAL (18, 2) NULL,
    [ListPrice]              DECIMAL (18, 2) NULL,
    [ServiceDate]            DATETIME        NULL,
    [HasRevenueSchedule]     BIT             NOT NULL,
    [HasQuantitySchedule]    BIT             NOT NULL,
    [HasSchedule]            BIT             NOT NULL,
    [CanUseQuantitySchedule] BIT             NOT NULL,
    [CanUseRevenueSchedule]  BIT             NOT NULL,
    [Lost_Reason__c]         VARCHAR (4099)  NULL,
    [Result__c]              VARCHAR (255)   NULL,
    [Item_Buyer__c]          VARCHAR (1300)  NULL,
    [Item_Supplier__c]       VARCHAR (18)    NULL,
    [Buyer_Post__c]          VARCHAR (1300)  NULL,
    [Starting_Price__c]      DECIMAL (16, 2) NULL,
    [Id]                     VARCHAR (18)    NOT NULL,
    [IsDeleted]              BIT             NOT NULL,
    [Name]                   VARCHAR (376)   NULL,
    [Description]            VARCHAR (255)   NULL,
    [CreatedDate]            DATETIME        NOT NULL,
    [CreatedById]            VARCHAR (18)    NOT NULL,
    [LastModifiedDate]       DATETIME        NOT NULL,
    [LastModifiedById]       VARCHAR (18)    NOT NULL,
    [SystemModstamp]         DATETIME        NOT NULL
);

