CREATE TABLE [dbo].[Sf_Program__c] (
    [OwnerId]                     VARCHAR (18)   NOT NULL,
    [RecordTypeId]                VARCHAR (18)   NULL,
    [LastActivityDate]            DATETIME       NULL,
    [Account_Name__c]             VARCHAR (18)   NULL,
    [Activated_Date__c]           DATETIME       NULL,
    [Billing_City__c]             VARCHAR (255)  NULL,
    [Billing_Country__c]          VARCHAR (255)  NULL,
    [Billing_State_Province__c]   VARCHAR (255)  NULL,
    [Billing_Street__c]           VARCHAR (255)  NULL,
    [Billing_Zip_Postal_Code__c]  VARCHAR (255)  NULL,
    [Customer_Signed_By__c]       VARCHAR (18)   NULL,
    [Customer_Signed_Date__c]     DATETIME       NULL,
    [Customer_Signed_Title__c]    VARCHAR (40)   NULL,
    [Description__c]              VARCHAR (8000) NULL,
    [Program_End_Date__c]         DATETIME       NULL,
    [Program_Start_Date__c]       DATETIME       NULL,
    [Program_Term_Months__c]      REAL           NULL,
    [Roland_Signed_Date__c]       DATETIME       NULL,
    [Shipping_City__c]            VARCHAR (255)  NULL,
    [Shipping_Country__c]         VARCHAR (255)  NULL,
    [Shipping_State_Province__c]  VARCHAR (255)  NULL,
    [Shipping_Street__c]          VARCHAR (255)  NULL,
    [Shipping_Zip_Postal_Code__c] VARCHAR (255)  NULL,
    [Special_Terms__c]            VARCHAR (4000) NULL,
    [Status__c]                   VARCHAR (255)  NULL,
    [Program_Type__c]             VARCHAR (4099) NULL,
    [Id]                          VARCHAR (18)   NOT NULL,
    [IsDeleted]                   BIT            NOT NULL,
    [Name]                        VARCHAR (80)   NOT NULL,
    [CreatedDate]                 DATETIME       NOT NULL,
    [CreatedById]                 VARCHAR (18)   NOT NULL,
    [LastModifiedDate]            DATETIME       NOT NULL,
    [LastModifiedById]            VARCHAR (18)   NOT NULL,
    [SystemModstamp]              DATETIME       NOT NULL,
    [LastViewedDate]              DATETIME       NULL,
    [LastReferencedDate]          DATETIME       NULL
);

