CREATE TABLE [dbo].[Sf_Product2] (
    [ProductCode]                        VARCHAR (255)  NULL,
    [QuantityScheduleType]               VARCHAR (40)   NULL,
    [QuantityInstallmentPeriod]          VARCHAR (40)   NULL,
    [NumberOfQuantityInstallments]       INT            NULL,
    [RevenueScheduleType]                VARCHAR (40)   NULL,
    [RevenueInstallmentPeriod]           VARCHAR (40)   NULL,
    [NumberOfRevenueInstallments]        INT            NULL,
    [IsActive]                           BIT            NOT NULL,
    [Family]                             VARCHAR (40)   NULL,
    [ExternalDataSourceId]               VARCHAR (18)   NULL,
    [ExternalId]                         VARCHAR (255)  NULL,
    [DisplayUrl]                         VARCHAR (1000) NULL,
    [QuantityUnitOfMeasure]              VARCHAR (40)   NULL,
    [IsArchived]                         BIT            NOT NULL,
    [StockKeepingUnit]                   VARCHAR (180)  NULL,
    [Benefits_Comment__c]                VARCHAR (2000) NULL,
    [Buyer_Name__c]                      VARCHAR (255)  NULL,
    [Case_Per_Pallet_Quantity__c]        REAL           NULL,
    [Descriptive_Weight__c]              VARCHAR (255)  NULL,
    [Discontinued_Flag__c]               BIT            NOT NULL,
    [Drained_Pack_Description_Number__c] REAL           NULL,
    [Drained_Pack_Description_Unit__c]   VARCHAR (255)  NULL,
    [Freight_Weight__c]                  REAL           NULL,
    [Ingredients__c]                     VARCHAR (2000) NULL,
    [Item_Number__c]                     REAL           NULL,
    [Kosher_Symbol__c]                   VARCHAR (4099) NULL,
    [Markdown_Percent__c]                REAL           NULL,
    [Net_Pack_Description_Number__c]     REAL           NULL,
    [Net_Pack_Description_Unit__c]       VARCHAR (255)  NULL,
    [Other_Comment__c]                   VARCHAR (2000) NULL,
    [Preparation_Comment__c]             VARCHAR (2000) NULL,
    [Primary_Product_Group__c]           VARCHAR (255)  NULL,
    [Purchasing_Pack_1__c]               REAL           NULL,
    [Purchasing_Pack_2__c]               REAL           NULL,
    [Purchasing_Pack_Unit_Type__c]       VARCHAR (255)  NULL,
    [QA_Person__c]                       VARCHAR (1300) NULL,
    [Secondary_Product_Group__c]         VARCHAR (255)  NULL,
    [Shelf_Life__c]                      VARCHAR (255)  NULL,
    [Similar_Products__c]                VARCHAR (2000) NULL,
    [Standard_Pack_Quantity__c]          REAL           NULL,
    [Storage_Temp_Degrees__c]            REAL           NULL,
    [Substitute_Item__c]                 VARCHAR (18)   NULL,
    [Suggested_Uses__c]                  VARCHAR (2000) NULL,
    [Unit_Gross_Weight_oz__c]            REAL           NULL,
    [Unit_Height_Inches__c]              REAL           NULL,
    [Unit_Length_Inches__c]              REAL           NULL,
    [Unit_Width_Inches__c]               REAL           NULL,
    [QA_Resource__c]                     VARCHAR (50)   NULL,
    [Suppliers2__c]                      VARCHAR (255)  NULL,
    [Full_Item_Info__c]                  VARCHAR (1300) NULL,
    [ChatterBuyer__c]                    VARCHAR (1300) NULL,
    [Purchase_Desc_1__c]                 VARCHAR (40)   NULL,
    [Purchase_Desc_2__c]                 VARCHAR (40)   NULL,
    [Purchase_Desc_3__c]                 VARCHAR (40)   NULL,
    [Contract_Description2__c]           VARCHAR (1300) NULL,
    [ProductID__c]                       VARCHAR (1300) NULL,
    [Contract_Description__c]            VARCHAR (255)  NULL,
    [Trans_ID__c]                        VARCHAR (255)  NULL,
    [Id]                                 VARCHAR (18)   NOT NULL,
    [IsDeleted]                          BIT            NOT NULL,
    [Name]                               VARCHAR (255)  NOT NULL,
    [Description]                        VARCHAR (4000) NULL,
    [CreatedDate]                        DATETIME       NOT NULL,
    [CreatedById]                        VARCHAR (18)   NOT NULL,
    [LastModifiedDate]                   DATETIME       NOT NULL,
    [LastModifiedById]                   VARCHAR (18)   NOT NULL,
    [SystemModstamp]                     DATETIME       NOT NULL,
    [LastViewedDate]                     DATETIME       NULL,
    [LastReferencedDate]                 DATETIME       NULL
);

