CREATE TABLE [dbo].[Sf_Supplier_Offer__c] (
    [ContactEmail__c]                    VARCHAR (1300)  NULL,
    [ContactId__c]                       VARCHAR (1300)  NULL,
    [Contact_Name__c]                    VARCHAR (18)    NULL,
    [Customer_Destination_Port__c]       VARCHAR (1300)  NULL,
    [Customer_Shipment_Terms_Request__c] VARCHAR (1300)  NULL,
    [Destination_Port__c]                VARCHAR (100)   NULL,
    [Expiration_Date__c]                 DATETIME        NULL,
    [Freight_Rate__c]                    VARCHAR (80)    NULL,
    [Full_Name__c]                       VARCHAR (1300)  NULL,
    [Grand_Total__c]                     DECIMAL (12, 2) NULL,
    [Is_this_a_Multiple_SO__c]           BIT             NOT NULL,
    [Opportunity_Lookup__c]              VARCHAR (18)    NULL,
    [Opportunity_Name__c]                VARCHAR (80)    NULL,
    [Shipment_Notes__c]                  VARCHAR (255)   NULL,
    [Shipment_Terms__c]                  VARCHAR (255)   NULL,
    [Shipping_Ports__c]                  VARCHAR (80)    NULL,
    [Status__c]                          VARCHAR (255)   NULL,
    [Supplier_Item_List__c]              VARCHAR (18)    NULL,
    [Supplier_Name__c]                   VARCHAR (18)    NULL,
    [Supplier_Offer_Name__c]             VARCHAR (80)    NOT NULL,
    [supplier_address__c]                VARCHAR (1300)  NULL,
    [Vendor_Number__c]                   VARCHAR (15)    NULL,
    [Id]                                 VARCHAR (18)    NOT NULL,
    [IsDeleted]                          BIT             NOT NULL,
    [Name]                               VARCHAR (80)    NOT NULL,
    [OwnerId]                            VARCHAR (18)    NOT NULL,
    [CreatedDate]                        DATETIME        NOT NULL,
    [CreatedById]                        VARCHAR (18)    NOT NULL,
    [LastModifiedDate]                   DATETIME        NOT NULL,
    [LastModifiedById]                   VARCHAR (18)    NOT NULL,
    [SystemModstamp]                     DATETIME        NOT NULL,
    [LastActivityDate]                   DATETIME        NULL,
    [LastViewedDate]                     DATETIME        NULL,
    [LastReferencedDate]                 DATETIME        NULL
);

