CREATE TABLE [dbo].[Sf_Sample_Tracking__c] (
    [OwnerId]                     VARCHAR (18)   NOT NULL,
    [LastActivityDate]            DATETIME       NULL,
    [Contact__c]                  VARCHAR (18)   NULL,
    [Convert_to_Opportunity__c]   BIT            NOT NULL,
    [Customer__c]                 VARCHAR (18)   NULL,
    [Email__c]                    VARCHAR (1300) NULL,
    [Opportunity__c]              VARCHAR (18)   NULL,
    [Order_Reference_No__c]       VARCHAR (20)   NULL,
    [Primary_Phone__c]            VARCHAR (1300) NULL,
    [Same_As__c]                  BIT            NOT NULL,
    [Secondary_Phone__c]          VARCHAR (1300) NULL,
    [Shipping_Address__c]         VARCHAR (255)  NULL,
    [Shipping_City__c]            VARCHAR (30)   NULL,
    [Shipping_State_Province__c]  VARCHAR (30)   NULL,
    [Shipping_Zip_Postal_Code__c] VARCHAR (15)   NULL,
    [Status__c]                   VARCHAR (255)  NULL,
    [UPS_Tracking_Info__c]        VARCHAR (30)   NULL,
    [Canada_Sample_Order__c]      BIT            NOT NULL,
    [Who_Entered_this_Order__c]   VARCHAR (255)  NULL,
    [Channel__c]                  VARCHAR (1300) NULL,
    [Closure_reason__c]           VARCHAR (255)  NULL,
    [Food_Shows__c]               BIT            NOT NULL,
    [Id]                          VARCHAR (18)   NOT NULL,
    [IsDeleted]                   BIT            NOT NULL,
    [Name]                        VARCHAR (80)   NULL,
    [CreatedDate]                 DATETIME       NOT NULL,
    [CreatedById]                 VARCHAR (18)   NOT NULL,
    [LastModifiedDate]            DATETIME       NOT NULL,
    [LastModifiedById]            VARCHAR (18)   NOT NULL,
    [SystemModstamp]              DATETIME       NOT NULL,
    [LastViewedDate]              DATETIME       NULL,
    [LastReferencedDate]          DATETIME       NULL
);

