CREATE TABLE [dbo].[Sf_User] (
    [Username]                                           VARCHAR (80)   NOT NULL,
    [LastName]                                           VARCHAR (80)   NOT NULL,
    [FirstName]                                          VARCHAR (40)   NULL,
    [CompanyName]                                        VARCHAR (80)   NULL,
    [Division]                                           VARCHAR (80)   NULL,
    [Department]                                         VARCHAR (80)   NULL,
    [Title]                                              VARCHAR (80)   NULL,
    [Street]                                             VARCHAR (255)  NULL,
    [City]                                               VARCHAR (40)   NULL,
    [State]                                              VARCHAR (80)   NULL,
    [PostalCode]                                         VARCHAR (20)   NULL,
    [Country]                                            VARCHAR (80)   NULL,
    [Latitude]                                           REAL           NULL,
    [Longitude]                                          REAL           NULL,
    [GeocodeAccuracy]                                    VARCHAR (40)   NULL,
    [Address]                                            VARCHAR (255)  NULL,
    [Email]                                              VARCHAR (128)  NOT NULL,
    [EmailPreferencesAutoBcc]                            BIT            NOT NULL,
    [EmailPreferencesAutoBccStayInTouch]                 BIT            NOT NULL,
    [EmailPreferencesStayInTouchReminder]                BIT            NOT NULL,
    [SenderEmail]                                        VARCHAR (80)   NULL,
    [SenderName]                                         VARCHAR (80)   NULL,
    [Signature]                                          VARCHAR (1333) NULL,
    [StayInTouchSubject]                                 VARCHAR (80)   NULL,
    [StayInTouchSignature]                               VARCHAR (512)  NULL,
    [StayInTouchNote]                                    VARCHAR (512)  NULL,
    [Phone]                                              VARCHAR (40)   NULL,
    [Fax]                                                VARCHAR (40)   NULL,
    [MobilePhone]                                        VARCHAR (40)   NULL,
    [Alias]                                              VARCHAR (8)    NOT NULL,
    [CommunityNickname]                                  VARCHAR (40)   NOT NULL,
    [BadgeText]                                          VARCHAR (80)   NULL,
    [IsActive]                                           BIT            NOT NULL,
    [TimeZoneSidKey]                                     VARCHAR (40)   NOT NULL,
    [UserRoleId]                                         VARCHAR (18)   NULL,
    [LocaleSidKey]                                       VARCHAR (40)   NOT NULL,
    [ReceivesInfoEmails]                                 BIT            NOT NULL,
    [ReceivesAdminInfoEmails]                            BIT            NOT NULL,
    [EmailEncodingKey]                                   VARCHAR (40)   NOT NULL,
    [ProfileId]                                          VARCHAR (18)   NOT NULL,
    [UserType]                                           VARCHAR (40)   NULL,
    [LanguageLocaleKey]                                  VARCHAR (40)   NOT NULL,
    [EmployeeNumber]                                     VARCHAR (20)   NULL,
    [DelegatedApproverId]                                VARCHAR (18)   NULL,
    [ManagerId]                                          VARCHAR (18)   NULL,
    [LastLoginDate]                                      DATETIME       NULL,
    [LastPasswordChangeDate]                             DATETIME       NULL,
    [OfflineTrialExpirationDate]                         DATETIME       NULL,
    [OfflinePdaTrialExpirationDate]                      DATETIME       NULL,
    [UserPermissionsMarketingUser]                       BIT            NOT NULL,
    [UserPermissionsOfflineUser]                         BIT            NOT NULL,
    [UserPermissionsAvantgoUser]                         BIT            NOT NULL,
    [UserPermissionsCallCenterAutoLogin]                 BIT            NOT NULL,
    [UserPermissionsMobileUser]                          BIT            NOT NULL,
    [UserPermissionsSFContentUser]                       BIT            NOT NULL,
    [UserPermissionsInteractionUser]                     BIT            NOT NULL,
    [UserPermissionsSupportUser]                         BIT            NOT NULL,
    [UserPermissionsChatterAnswersUser]                  BIT            NOT NULL,
    [ForecastEnabled]                                    BIT            NOT NULL,
    [UserPreferencesActivityRemindersPopup]              BIT            NOT NULL,
    [UserPreferencesEventRemindersCheckboxDefault]       BIT            NOT NULL,
    [UserPreferencesTaskRemindersCheckboxDefault]        BIT            NOT NULL,
    [UserPreferencesReminderSoundOff]                    BIT            NOT NULL,
    [UserPreferencesDisableAllFeedsEmail]                BIT            NOT NULL,
    [UserPreferencesDisableFollowersEmail]               BIT            NOT NULL,
    [UserPreferencesDisableProfilePostEmail]             BIT            NOT NULL,
    [UserPreferencesDisableChangeCommentEmail]           BIT            NOT NULL,
    [UserPreferencesDisableLaterCommentEmail]            BIT            NOT NULL,
    [UserPreferencesDisProfPostCommentEmail]             BIT            NOT NULL,
    [UserPreferencesContentNoEmail]                      BIT            NOT NULL,
    [UserPreferencesContentEmailAsAndWhen]               BIT            NOT NULL,
    [UserPreferencesApexPagesDeveloperMode]              BIT            NOT NULL,
    [UserPreferencesHideCSNGetChatterMobileTask]         BIT            NOT NULL,
    [UserPreferencesDisableMentionsPostEmail]            BIT            NOT NULL,
    [UserPreferencesDisMentionsCommentEmail]             BIT            NOT NULL,
    [UserPreferencesHideCSNDesktopTask]                  BIT            NOT NULL,
    [UserPreferencesHideChatterOnboardingSplash]         BIT            NOT NULL,
    [UserPreferencesHideSecondChatterOnboardingSplash]   BIT            NOT NULL,
    [UserPreferencesDisCommentAfterLikeEmail]            BIT            NOT NULL,
    [UserPreferencesDisableLikeEmail]                    BIT            NOT NULL,
    [UserPreferencesSortFeedByComment]                   BIT            NOT NULL,
    [UserPreferencesDisableMessageEmail]                 BIT            NOT NULL,
    [UserPreferencesDisableBookmarkEmail]                BIT            NOT NULL,
    [UserPreferencesDisableSharePostEmail]               BIT            NOT NULL,
    [UserPreferencesEnableAutoSubForFeeds]               BIT            NOT NULL,
    [UserPreferencesDisableFileShareNotificationsForApi] BIT            NOT NULL,
    [UserPreferencesShowTitleToExternalUsers]            BIT            NOT NULL,
    [UserPreferencesShowManagerToExternalUsers]          BIT            NOT NULL,
    [UserPreferencesShowEmailToExternalUsers]            BIT            NOT NULL,
    [UserPreferencesShowWorkPhoneToExternalUsers]        BIT            NOT NULL,
    [UserPreferencesShowMobilePhoneToExternalUsers]      BIT            NOT NULL,
    [UserPreferencesShowFaxToExternalUsers]              BIT            NOT NULL,
    [UserPreferencesShowStreetAddressToExternalUsers]    BIT            NOT NULL,
    [UserPreferencesShowCityToExternalUsers]             BIT            NOT NULL,
    [UserPreferencesShowStateToExternalUsers]            BIT            NOT NULL,
    [UserPreferencesShowPostalCodeToExternalUsers]       BIT            NOT NULL,
    [UserPreferencesShowCountryToExternalUsers]          BIT            NOT NULL,
    [UserPreferencesShowProfilePicToGuestUsers]          BIT            NOT NULL,
    [UserPreferencesShowTitleToGuestUsers]               BIT            NOT NULL,
    [UserPreferencesShowCityToGuestUsers]                BIT            NOT NULL,
    [UserPreferencesShowStateToGuestUsers]               BIT            NOT NULL,
    [UserPreferencesShowPostalCodeToGuestUsers]          BIT            NOT NULL,
    [UserPreferencesShowCountryToGuestUsers]             BIT            NOT NULL,
    [UserPreferencesPipelineViewHideHelpPopover]         BIT            NOT NULL,
    [UserPreferencesHideS1BrowserUI]                     BIT            NOT NULL,
    [UserPreferencesDisableEndorsementEmail]             BIT            NOT NULL,
    [UserPreferencesPathAssistantCollapsed]              BIT            NOT NULL,
    [UserPreferencesCacheDiagnostics]                    BIT            NOT NULL,
    [UserPreferencesShowEmailToGuestUsers]               BIT            NOT NULL,
    [UserPreferencesShowManagerToGuestUsers]             BIT            NOT NULL,
    [UserPreferencesShowWorkPhoneToGuestUsers]           BIT            NOT NULL,
    [UserPreferencesShowMobilePhoneToGuestUsers]         BIT            NOT NULL,
    [UserPreferencesShowFaxToGuestUsers]                 BIT            NOT NULL,
    [UserPreferencesShowStreetAddressToGuestUsers]       BIT            NOT NULL,
    [UserPreferencesLightningExperiencePreferred]        BIT            NOT NULL,
    [UserPreferencesPreviewLightning]                    BIT            NOT NULL,
    [UserPreferencesHideEndUserOnboardingAssistantModal] BIT            NOT NULL,
    [UserPreferencesHideLightningMigrationModal]         BIT            NOT NULL,
    [UserPreferencesHideSfxWelcomeMat]                   BIT            NOT NULL,
    [UserPreferencesHideBiggerPhotoCallout]              BIT            NOT NULL,
    [UserPreferencesGlobalNavBarWTShown]                 BIT            NOT NULL,
    [UserPreferencesGlobalNavGridMenuWTShown]            BIT            NOT NULL,
    [UserPreferencesCreateLEXAppsWTShown]                BIT            NOT NULL,
    [UserPreferencesFavoritesWTShown]                    BIT            NOT NULL,
    [UserPreferencesRecordHomeSectionCollapseWTShown]    BIT            NOT NULL,
    [UserPreferencesRecordHomeReservedWTShown]           BIT            NOT NULL,
    [UserPreferencesFavoritesShowTopFavorites]           BIT            NOT NULL,
    [UserPreferencesExcludeMailAppAttachments]           BIT            NOT NULL,
    [UserPreferencesSuppressTaskSFXReminders]            BIT            NOT NULL,
    [UserPreferencesSuppressEventSFXReminders]           BIT            NOT NULL,
    [UserPreferencesPreviewCustomTheme]                  BIT            NOT NULL,
    [UserPreferencesHasCelebrationBadge]                 BIT            NOT NULL,
    [UserPreferencesUserDebugModePref]                   BIT            NOT NULL,
    [UserPreferencesNewLightningReportRunPageEnabled]    BIT            NOT NULL,
    [ContactId]                                          VARCHAR (18)   NULL,
    [AccountId]                                          VARCHAR (18)   NULL,
    [CallCenterId]                                       VARCHAR (18)   NULL,
    [Extension]                                          VARCHAR (40)   NULL,
    [FederationIdentifier]                               VARCHAR (512)  NULL,
    [AboutMe]                                            VARCHAR (1000) NULL,
    [FullPhotoUrl]                                       VARCHAR (1024) NULL,
    [SmallPhotoUrl]                                      VARCHAR (1024) NULL,
    [IsExtIndicatorVisible]                              BIT            NOT NULL,
    [OutOfOfficeMessage]                                 VARCHAR (40)   NULL,
    [MediumPhotoUrl]                                     VARCHAR (1024) NULL,
    [DigestFrequency]                                    VARCHAR (40)   NOT NULL,
    [DefaultGroupNotificationFrequency]                  VARCHAR (40)   NOT NULL,
    [LastViewedDate]                                     DATETIME       NULL,
    [LastReferencedDate]                                 DATETIME       NULL,
    [BannerPhotoUrl]                                     VARCHAR (1024) NULL,
    [SmallBannerPhotoUrl]                                VARCHAR (1024) NULL,
    [MediumBannerPhotoUrl]                               VARCHAR (1024) NULL,
    [IsProfilePhotoActive]                               BIT            NOT NULL,
    [IndividualId]                                       VARCHAR (18)   NULL,
    [Manager_Number__c]                                  VARCHAR (3)    NULL,
    [DB_Region__c]                                       VARCHAR (255)  NULL,
    [Id]                                                 VARCHAR (18)   NOT NULL,
    [Name]                                               VARCHAR (121)  NOT NULL,
    [CreatedDate]                                        DATETIME       NOT NULL,
    [CreatedById]                                        VARCHAR (18)   NOT NULL,
    [LastModifiedDate]                                   DATETIME       NOT NULL,
    [LastModifiedById]                                   VARCHAR (18)   NOT NULL,
    [SystemModstamp]                                     DATETIME       NOT NULL
);

