CREATE TABLE [dbo].[Sl_ProductAttribute_old] (
    [SKU]                            INT            NOT NULL,
    [Name]                           NVARCHAR (100) NOT NULL,
    [ItemName]                       NVARCHAR (100) NULL,
    [ProductName]                    NVARCHAR (100) NOT NULL,
    [ComputedPackSize]               NVARCHAR (50)  NOT NULL,
    [UnitQuantity]                   NVARCHAR (50)  NOT NULL,
    [UnitSize]                       NVARCHAR (50)  NULL,
    [BrandName]                      NVARCHAR (50)  NOT NULL,
    [Disabled]                       NVARCHAR (50)  NOT NULL,
    [ProductCategory1]               NVARCHAR (50)  NULL,
    [ProductCategory2]               NVARCHAR (50)  NULL,
    [SupplierEngagementSpecialist]   NVARCHAR (50)  NULL,
    [BuyerName]                      NVARCHAR (50)  NULL,
    [ItemUPC]                        FLOAT (53)     NOT NULL,
    [InsideUPCCode]                  NVARCHAR (50)  NULL,
    [OutsideUPCCode]                 FLOAT (53)     NULL,
    [MasterPack]                     NVARCHAR (50)  NULL,
    [EffectiveDate]                  DATETIME2 (7)  NULL,
    [SupersedesDate]                 DATETIME2 (7)  NULL,
    [ReasonForChange]                NVARCHAR (50)  NULL,
    [RevisedBy]                      NVARCHAR (50)  NULL,
    [File]                           NVARCHAR (50)  NOT NULL,
    [PackSize]                       NVARCHAR (50)  NULL,
    [Pack1]                          NVARCHAR (50)  NULL,
    [Pack2]                          NVARCHAR (50)  NULL,
    [Supplier1]                      NVARCHAR (50)  NULL,
    [Supplier10COO]                  NVARCHAR (50)  NULL,
    [Supplier10]                     NVARCHAR (50)  NULL,
    [Supplier10Kosher]               NVARCHAR (50)  NULL,
    [Supplier11]                     NVARCHAR (50)  NULL,
    [Supplier11COO]                  NVARCHAR (50)  NULL,
    [Supplier11Kosher]               NVARCHAR (50)  NULL,
    [Supplier1COO]                   NVARCHAR (100) NULL,
    [Supplier2]                      NVARCHAR (50)  NULL,
    [Supplier1Kosher]                NVARCHAR (50)  NULL,
    [Supplier2Kosher]                NVARCHAR (50)  NULL,
    [Supplier2COO]                   NVARCHAR (100) NULL,
    [Supplier3COO]                   NVARCHAR (100) NULL,
    [Supplier3]                      NVARCHAR (50)  NULL,
    [Supplier3Kosher]                NVARCHAR (50)  NULL,
    [Supplier4]                      NVARCHAR (50)  NULL,
    [Supplier4Kosher]                NVARCHAR (50)  NULL,
    [Supplier4COO]                   NVARCHAR (50)  NULL,
    [Supplier5]                      NVARCHAR (50)  NULL,
    [Supplier5COO]                   NVARCHAR (50)  NULL,
    [Supplier5Kosher]                NVARCHAR (50)  NULL,
    [Supplier6]                      NVARCHAR (50)  NULL,
    [Supplier6COO]                   NVARCHAR (50)  NULL,
    [Supplier6Kosher]                NVARCHAR (50)  NULL,
    [Supplier7COO]                   NVARCHAR (50)  NULL,
    [Supplier7]                      NVARCHAR (50)  NULL,
    [Supplier7Kosher]                NVARCHAR (50)  NULL,
    [Supplier8]                      NVARCHAR (50)  NULL,
    [Supplier8COO]                   NVARCHAR (50)  NULL,
    [Supplier8Kosher]                NVARCHAR (50)  NULL,
    [Supplier9]                      NVARCHAR (50)  NULL,
    [Supplier9COO]                   NVARCHAR (50)  NULL,
    [Supplier9Kosher]                NVARCHAR (50)  NULL,
    [CaseLengthIn]                   FLOAT (53)     NULL,
    [CaseWidthIn]                    FLOAT (53)     NULL,
    [CaseHeightIn]                   FLOAT (53)     NULL,
    [CaseNetWeightLb]                NVARCHAR (50)  NULL,
    [CaseGrossWeightLb]              NVARCHAR (50)  NULL,
    [CaseTareWeightLb]               FLOAT (53)     NULL,
    [PalletHi]                       NVARCHAR (50)  NULL,
    [PalletTie]                      NVARCHAR (50)  NULL,
    [GrossPalletWeightLb]            FLOAT (53)     NULL,
    [CasesPerPallet]                 INT            NULL,
    [CaseCubeFt3]                    FLOAT (53)     NULL,
    [PackagingType]                  NVARCHAR (100) NULL,
    [NetWeightUnitLabel]             NVARCHAR (100) NOT NULL,
    [NetWeightFormula]               NVARCHAR (100) NOT NULL,
    [DRWeightFormula]                NVARCHAR (50)  NULL,
    [DRWeightUnitLabel]              NVARCHAR (50)  NULL,
    [DRWTUnitUseGKgOzLb]             NVARCHAR (50)  NULL,
    [PackagingTareWeight]            FLOAT (53)     NULL,
    [ShelfLifeDaysUnopened]          INT            NULL,
    [UnopenedStorageCondition]       NVARCHAR (50)  NULL,
    [ShelfLifeAfterOpeningDays]      INT            NULL,
    [OpenedStorageCondition]         NVARCHAR (50)  NULL,
    [ShipContidionsSales]            NVARCHAR (100) NULL,
    [CaloriesKcal100g]               NVARCHAR (50)  NULL,
    [CaloriesFromFatKcal100g]        NVARCHAR (50)  NULL,
    [TotalFatG100g]                  NVARCHAR (50)  NULL,
    [SaturatedFatG100g]              NVARCHAR (50)  NULL,
    [UnsaturatedFatG100g]            NVARCHAR (50)  NULL,
    [PolyunsaturatedFatG100g]        NVARCHAR (50)  NULL,
    [CalciumMg100g]                  NVARCHAR (50)  NULL,
    [AddedSugarG100g]                NVARCHAR (50)  NULL,
    [CholesterolMg100g]              NVARCHAR (50)  NULL,
    [IronMg100g]                     NVARCHAR (50)  NULL,
    [DietaryFiberG100g]              NVARCHAR (50)  NULL,
    [MonounsaturatedFatG100g]        NVARCHAR (50)  NULL,
    [MoistureAshG100g]               NVARCHAR (50)  NULL,
    [ProteinG100g]                   NVARCHAR (50)  NULL,
    [PotassiumMg100g]                NVARCHAR (50)  NULL,
    [TotalCarbohydrateG100g]         NVARCHAR (50)  NULL,
    [SodiumMg100g]                   NVARCHAR (50)  NULL,
    [TransFatG100g]                  NVARCHAR (50)  NULL,
    [TotalSugarG100g]                NVARCHAR (50)  NULL,
    [VitaminCMg100g]                 NVARCHAR (50)  NULL,
    [VitaminAMcg100g]                NVARCHAR (50)  NULL,
    [VitaminDMcg100g]                NVARCHAR (50)  NULL,
    [CaloriesKcalServing]            NVARCHAR (50)  NULL,
    [TotalFatGServing]               NVARCHAR (50)  NULL,
    [SaturatedFatGServing]           NVARCHAR (50)  NULL,
    [AddedSugarGServing]             NVARCHAR (50)  NULL,
    [MonounsaturatedFatGServing]     NVARCHAR (50)  NULL,
    [DietaryFiberGServing]           NVARCHAR (50)  NULL,
    [ProteinGServing]                NVARCHAR (50)  NULL,
    [PolyunsaturatedFatGServing]     NVARCHAR (50)  NULL,
    [TotalSugarGServing]             NVARCHAR (50)  NULL,
    [TotalCarbsGServing]             NVARCHAR (50)  NULL,
    [TransFatGServing]               NVARCHAR (50)  NULL,
    [UnsaturatedFatGServing]         NVARCHAR (50)  NULL,
    [CalciumMgServing]               NVARCHAR (50)  NULL,
    [CholesterolMgServing]           NVARCHAR (50)  NULL,
    [PotassiumMgServing]             NVARCHAR (50)  NULL,
    [IronMgServing]                  NVARCHAR (50)  NULL,
    [SodiumMgServing]                NVARCHAR (50)  NULL,
    [AddedSugarsDV]                  NVARCHAR (50)  NULL,
    [CholesterolDV]                  NVARCHAR (50)  NULL,
    [SaturatedFatDV]                 NVARCHAR (50)  NULL,
    [DietaryFiberDV]                 NVARCHAR (50)  NULL,
    [SodiumDV]                       NVARCHAR (50)  NULL,
    [TotalCarbDV]                    NVARCHAR (50)  NULL,
    [VitaminDDV]                     NVARCHAR (50)  NULL,
    [TotalFatDV]                     NVARCHAR (50)  NULL,
    [Ingredients1]                   NVARCHAR (450) NULL,
    [IngredientStatement]            NVARCHAR (500) NULL,
    [CalculatedWeightServingG]       FLOAT (53)     NULL,
    [SpecificGravity]                NVARCHAR (50)  NULL,
    [CountPerUnit]                   NVARCHAR (100) NULL,
    [Appearance]                     NVARCHAR (100) NOT NULL,
    [Color]                          NVARCHAR (100) NOT NULL,
    [AromaSmell]                     NVARCHAR (100) NULL,
    [FlavorTaste]                    NVARCHAR (100) NULL,
    [TextureFeel]                    NVARCHAR (100) NULL,
    [Halal]                          NVARCHAR (50)  NULL,
    [LabelComments]                  NVARCHAR (100) NULL,
    [LabelComments1]                 NVARCHAR (100) NULL,
    [LabelComments2]                 NVARCHAR (100) NULL,
    [LabelComments3]                 NVARCHAR (100) NULL,
    [GMOStatus]                      NVARCHAR (400) NULL,
    [GMOStatus1]                     NVARCHAR (100) NULL,
    [GlutenIngredientsStatus]        NVARCHAR (100) NULL,
    [LactoOvoVegetarian]             NVARCHAR (50)  NULL,
    [Vegan]                          NVARCHAR (50)  NULL,
    [QualifyForMadeInAmericaProgram] NVARCHAR (200) NULL,
    [SalsifyRecordType]              NVARCHAR (50)  NOT NULL,
    [VitaminDMcgServing]             NVARCHAR (50)  NULL,
    [CalciumDV]                      NVARCHAR (50)  NULL,
    [IronDV]                         NVARCHAR (50)  NULL,
    [PotassiumDV]                    NVARCHAR (50)  NULL,
    [ServingsPerContainer]           NVARCHAR (50)  NULL,
    CONSTRAINT [PK_slProductTable] PRIMARY KEY CLUSTERED ([SKU] ASC)
);

