CREATE TABLE [dbo].[SMMBUSRELSUBSEGMENTGROUP] (
    [SEGMENTID]             NVARCHAR (20) DEFAULT ('') NOT NULL,
    [SUBSEGMENTID]          NVARCHAR (20) DEFAULT ('') NOT NULL,
    [SUBSEGMENTDESCRIPTION] NVARCHAR (60) DEFAULT ('') NOT NULL,
    [DATAAREAID]            NVARCHAR (4)  DEFAULT ('dat') NOT NULL,
    [RECVERSION]            INT           DEFAULT ((1)) NOT NULL,
    [PARTITION]             BIGINT        DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                 BIGINT        NOT NULL,
    CONSTRAINT [I_8151SEGMENTSIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [SEGMENTID] ASC, [SUBSEGMENTID] ASC),
    CHECK ([RECID]<>(0))
);

