CREATE TABLE [dbo].[SMMBUSRELSALESDISTRICTGROUP] (
    [SALESDISTRICTID] NVARCHAR (20) NOT NULL,
    [DESCRIPTION]     NVARCHAR (60) NOT NULL,
    [DATAAREAID]      NVARCHAR (4)  NOT NULL,
    [RECVERSION]      INT           NOT NULL,
    [PARTITION]       BIGINT        NOT NULL,
    [RECID]           BIGINT        NOT NULL,
    CONSTRAINT [I_8147SALESDISTRICTIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [SALESDISTRICTID] ASC)
);

