CREATE TABLE [dbo].[SMMBUSRELCHAINGROUP] (
    [CHAINID]     NVARCHAR (20) NOT NULL,
    [DESCRIPTION] NVARCHAR (60) NOT NULL,
    [DATAAREAID]  NVARCHAR (4)  NOT NULL,
    [RECVERSION]  INT           NOT NULL,
    [PARTITION]   BIGINT        NOT NULL,
    [RECID]       BIGINT        NOT NULL
);

