CREATE TABLE [dbo].[TAMDEDUCTION] (
    [TAMDEDUCTIONID]                NVARCHAR (20)    NOT NULL,
    [TAMDEDUCTIONSTATUS]            INT              NOT NULL,
    [ACCOUNTNUM]                    NVARCHAR (20)    NOT NULL,
    [JOURNALID]                     NVARCHAR (10)    NOT NULL,
    [LEDGERJOURNALTRANSPARENTRECID] BIGINT           NOT NULL,
    [LEDGERJOURNALTRANSRECID]       BIGINT           NOT NULL,
    [CURRENCYCODE]                  NVARCHAR (3)     NOT NULL,
    [AMOUNTCUR]                     NUMERIC (32, 16) NOT NULL,
    [REMAINAMOUNTCUR]               NUMERIC (32, 16) NOT NULL,
    [MATCHAMOUNTCUR]                NUMERIC (32, 16) NOT NULL,
    [DENYAMOUNTCUR]                 NUMERIC (32, 16) NOT NULL,
    [WRITEOFFAMOUNTCUR]             NUMERIC (32, 16) NOT NULL,
    [TAMPROMOTIONID]                NVARCHAR (10)    NOT NULL,
    [MCRMERCHANDISINGEVENTID]       NVARCHAR (10)    NOT NULL,
    [SALESID]                       NVARCHAR (20)    NOT NULL,
    [CUSTINVOICEID]                 NVARCHAR (20)    NOT NULL,
    [NOTES]                         NVARCHAR (254)   NOT NULL,
    [TAMDEDUCTIONORIGID]            NVARCHAR (20)    NOT NULL,
    [TAMDEDUCTIONDENYREASON]        NVARCHAR (20)    NOT NULL,
    [DENYJOURNALID]                 NVARCHAR (10)    NOT NULL,
    [SPLITAMOUNTCUR]                NUMERIC (32, 16) NOT NULL,
    [TAMDEDUCTIONWRITEOFFREASON]    NVARCHAR (20)    NOT NULL,
    [WRITEOFFJOURNALID]             NVARCHAR (10)    NOT NULL,
    [TAMDEDUCTIONTYPE]              NVARCHAR (20)    NOT NULL,
    [REMAINAMOUNTMST]               NUMERIC (32, 16) NOT NULL,
    [DEDUCTOFFLEDGERDIMENSION]      BIGINT           NOT NULL,
    [HCMWORKERID]                   BIGINT           NOT NULL,
    [DEDUCTWRITEOFFLEDGERDIMENSION] BIGINT           NOT NULL,
    [CUSTTRANSRECID]                BIGINT           NOT NULL,
    [CREATEDDATETIME]               DATETIME         NOT NULL,
    [DATAAREAID]                    NVARCHAR (4)     NOT NULL,
    [RECVERSION]                    INT              NOT NULL,
    [PARTITION]                     BIGINT           NOT NULL,
    [RECID]                         BIGINT           NOT NULL
);

