CREATE TABLE [dbo].[UNITOFMEASURECONVERSION] (
    [FROMUNITOFMEASURE] BIGINT           DEFAULT ((0)) NOT NULL,
    [TOUNITOFMEASURE]   BIGINT           DEFAULT ((0)) NOT NULL,
    [PRODUCT]           BIGINT           DEFAULT ((0)) NOT NULL,
    [FACTOR]            NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [NUMERATOR]         INT              DEFAULT ((0)) NOT NULL,
    [DENOMINATOR]       INT              DEFAULT ((0)) NOT NULL,
    [INNEROFFSET]       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [OUTEROFFSET]       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [ROUNDING]          INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDDATETIME]  DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [RECVERSION]        INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]         BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]             BIGINT           NOT NULL,
    CONSTRAINT [I_4438RECID] PRIMARY KEY NONCLUSTERED ([RECID] ASC),
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_UOM_TO]
    ON [dbo].[UNITOFMEASURECONVERSION]([TOUNITOFMEASURE] ASC)
    INCLUDE([FROMUNITOFMEASURE], [PRODUCT], [FACTOR], [NUMERATOR], [DENOMINATOR], [INNEROFFSET], [OUTEROFFSET], [ROUNDING], [MODIFIEDDATETIME], [RECVERSION], [PARTITION], [RECID]);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_UOMCON]
    ON [dbo].[UNITOFMEASURECONVERSION]([FROMUNITOFMEASURE] ASC)
    INCLUDE([TOUNITOFMEASURE], [PRODUCT], [FACTOR], [NUMERATOR], [DENOMINATOR]);

