CREATE TABLE [dbo].[VENDPACKINGSLIPJOUR] (
    [PURCHID]                     NVARCHAR (20)    NOT NULL,
    [ORDERACCOUNT]                NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]              NVARCHAR (20)    NOT NULL,
    [PACKINGSLIPID]               NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYPOSTED]          INT              NOT NULL,
    [DELIVERYDATE]                DATETIME         NOT NULL,
    [DELIVERYNAME]                NVARCHAR (100)   NOT NULL,
    [DELIVERYPOSTALADDRESS]       BIGINT           NOT NULL,
    [COUNTRYREGIONID]             NVARCHAR (10)    NOT NULL,
    [INTRASTATDISPATCH]           NVARCHAR (20)    NOT NULL,
    [DLVTERM]                     NVARCHAR (10)    NOT NULL,
    [DLVMODE]                     NVARCHAR (10)    NOT NULL,
    [DELIVERYTYPE]                INT              NOT NULL,
    [PURCHASETYPE]                INT              NOT NULL,
    [RETURNITEMNUM]               NVARCHAR (10)    NOT NULL,
    [FREIGHTSLIPNUM]              NVARCHAR (20)    NOT NULL,
    [FREIGHTSLIPTYPE]             INT              NOT NULL,
    [ITEMBUYERGROUPID]            NVARCHAR (10)    NOT NULL,
    [REQATTENTION]                NVARCHAR (255)   NOT NULL,
    [NUMBERSEQUENCEGROUP]         NVARCHAR (10)    NOT NULL,
    [INTERCOMPANYCOMPANYID]       NVARCHAR (4)     NOT NULL,
    [INTERCOMPANYSALESID]         NVARCHAR (20)    NOT NULL,
    [LANGUAGEID]                  NVARCHAR (7)     NOT NULL,
    [DOCUMENTDATE]                DATETIME         NOT NULL,
    [DEFAULTDIMENSION]            BIGINT           NOT NULL,
    [SOURCEDOCUMENTHEADER]        BIGINT           NOT NULL,
    [REQUESTER]                   BIGINT           NOT NULL,
    [RECEIPTLISTDEVIATIONTYPE_RU] INT              NOT NULL,
    [GRNNUMBER_IN]                NVARCHAR (20)    NOT NULL,
    [INVENTPROFILETYPE_RU]        INT              NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU] DATETIME         NOT NULL,
    [OFFSESSIONID_RU]             NVARCHAR (20)    NOT NULL,
    [CURRENCYCODE_W]              NVARCHAR (3)     NOT NULL,
    [ORDERBALANCE_RU]             NUMERIC (32, 16) NOT NULL,
    [ENDDISC_RU]                  NUMERIC (32, 16) NOT NULL,
    [CONSIGNEEACCOUNT_RU]         NVARCHAR (20)    NOT NULL,
    [CONSIGNORACCOUNT_RU]         NVARCHAR (20)    NOT NULL,
    [PACKINGSLIPSTATUS_LT]        INT              NOT NULL,
    [PACKINGSLIPNUMBERINGCODE_LT] NVARCHAR (10)    NOT NULL,
    [PACKINGSLIPREGISTER_LT]      INT              NOT NULL,
    [INVOICEISSUEDUEDATE_W]       DATETIME         NOT NULL,
    [DATAAREAID]                  NVARCHAR (4)     NOT NULL,
    [RECVERSION]                  INT              NOT NULL,
    [PARTITION]                   BIGINT           NOT NULL,
    [RECID]                       BIGINT           NOT NULL,
    CONSTRAINT [I_500RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

