CREATE TABLE [dbo].[VENDINVOICEJOUR] (
    [VENDGROUP]                      NVARCHAR (10)    NOT NULL,
    [PURCHID]                        NVARCHAR (20)    NOT NULL,
    [ORDERACCOUNT]                   NVARCHAR (20)    NOT NULL,
    [INVOICEACCOUNT]                 NVARCHAR (20)    NOT NULL,
    [INVOICEID]                      NVARCHAR (20)    NOT NULL,
    [INVOICEDATE]                    DATETIME         NOT NULL,
    [DUEDATE]                        DATETIME         NOT NULL,
    [CASHDISC]                       NUMERIC (32, 16) NOT NULL,
    [CASHDISCDATE]                   DATETIME         NOT NULL,
    [QTY]                            NUMERIC (32, 16) NOT NULL,
    [VOLUME]                         NUMERIC (32, 16) NOT NULL,
    [WEIGHT]                         NUMERIC (32, 16) NOT NULL,
    [SUMLINEDISC]                    NUMERIC (32, 16) NOT NULL,
    [PREPAYMENT]                     INT              NOT NULL,
    [SALESBALANCE]                   NUMERIC (32, 16) NOT NULL,
    [ENDDISC]                        NUMERIC (32, 16) NOT NULL,
    [INVOICEAMOUNT]                  NUMERIC (32, 16) NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     NOT NULL,
    [EXCHRATE]                       NUMERIC (32, 16) NOT NULL,
    [ENTERPRISENUMBER]               NVARCHAR (50)    NOT NULL,
    [RETURNITEMNUM]                  NVARCHAR (10)    NOT NULL,
    [TAXROUNDOFF]                    NUMERIC (32, 16) NOT NULL,
    [LEDGERVOUCHER]                  NVARCHAR (20)    NOT NULL,
    [TAXPRINTONINVOICE]              INT              NOT NULL,
    [TAXSPECIFYBYLINE]               INT              NOT NULL,
    [DOCUMENTNUM]                    NVARCHAR (20)    NOT NULL,
    [DOCUMENTDATE]                   DATETIME         NOT NULL,
    [COUNTRYREGIONID]                NVARCHAR (10)    NOT NULL,
    [INTRASTATDISPATCH]              NVARCHAR (20)    NOT NULL,
    [INVOICEROUNDOFF]                NUMERIC (32, 16) NOT NULL,
    [SUMMARKUP]                      NUMERIC (32, 16) NOT NULL,
    [PAYMID]                         NVARCHAR (200)   NOT NULL,
    [TAXGROUP]                       NVARCHAR (10)    NOT NULL,
    [CASHDISCCODE]                   NVARCHAR (10)    NOT NULL,
    [CASHDISCPERCENT]                NUMERIC (32, 16) NOT NULL,
    [PAYMENT]                        NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILE]                 NVARCHAR (10)    NOT NULL,
    [PAYMENTSCHED]                   NVARCHAR (30)    NOT NULL,
    [INTERCOMPANYPOSTED]             INT              NOT NULL,
    [PURCHASETYPE]                   INT              NOT NULL,
    [SUMTAX]                         NUMERIC (32, 16) NOT NULL,
    [PARMID]                         NVARCHAR (20)    NOT NULL,
    [EXCHRATESECONDARY]              NUMERIC (32, 16) NOT NULL,
    [TRIANGULATION]                  INT              NOT NULL,
    [ITEMBUYERGROUPID]               NVARCHAR (10)    NOT NULL,
    [VATNUM]                         NVARCHAR (20)    NOT NULL,
    [INTERNALINVOICEID]              NVARCHAR (20)    NOT NULL,
    [NUMBERSEQUENCEGROUP]            NVARCHAR (10)    NOT NULL,
    [INCLTAX]                        INT              NOT NULL,
    [PAYMDAYID]                      NVARCHAR (10)    NOT NULL,
    [DLVTERM]                        NVARCHAR (10)    NOT NULL,
    [DLVMODE]                        NVARCHAR (10)    NOT NULL,
    [FIXEDDUEDATE]                   DATETIME         NOT NULL,
    [INTERCOMPANYCOMPANYID]          NVARCHAR (4)     NOT NULL,
    [INTERCOMPANYSALESID]            NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYLEDGERVOUCHER]      NVARCHAR (20)    NOT NULL,
    [PROFORMA]                       INT              NOT NULL,
    [LANGUAGEID]                     NVARCHAR (7)     NOT NULL,
    [INVOICEAMOUNTMST]               NUMERIC (32, 16) NOT NULL,
    [SUMMARKUPMST]                   NUMERIC (32, 16) NOT NULL,
    [ENDDISCMST]                     NUMERIC (32, 16) NOT NULL,
    [REVERSECHARGE_UK]               NUMERIC (32, 16) NOT NULL,
    [DOCUMENTORIGIN]                 INT              NOT NULL,
    [VENDINVOICEGROUP]               NVARCHAR (10)    NOT NULL,
    [VENDPAYMENTGROUP]               NVARCHAR (10)    NOT NULL,
    [DEFAULTDIMENSION]               BIGINT           NOT NULL,
    [DESCRIPTION]                    NVARCHAR (50)    NOT NULL,
    [CONTRACTNUM_SA]                 NVARCHAR (60)    NOT NULL,
    [REMITTANCEADDRESS]              BIGINT           NOT NULL,
    [VENDINVOICEDECLARATION_IS]      BIGINT           NOT NULL,
    [COSTLEDGERVOUCHER]              NVARCHAR (20)    NOT NULL,
    [SOURCEDOCUMENTHEADER]           BIGINT           NOT NULL,
    [SOURCEDOCUMENTLINE]             BIGINT           NOT NULL,
    [OPERATIONTYPE_MX]               INT              NOT NULL,
    [LISTCODE]                       INT              NOT NULL,
    [EUSALESLIST]                    NVARCHAR (20)    NOT NULL,
    [VENDORREQUESTEDWORKEREMAIL]     NVARCHAR (80)    NOT NULL,
    [LOGISTICSELECTRONICADDRESS]     BIGINT           NOT NULL,
    [BANKLCIMPORTLINE]               BIGINT           NOT NULL,
    [INVOICETYPE]                    INT              NOT NULL,
    [DELIVERYNAME]                   NVARCHAR (100)   NOT NULL,
    [DELIVERYDATE_ES]                DATETIME         NOT NULL,
    [PURCHRECEIPTDATE_W]             DATETIME         NOT NULL,
    [VATONPAYMENT_RU]                INT              NOT NULL,
    [CORRECT_RU]                     INT              NOT NULL,
    [WHOISAUTHOR_LT]                 INT              NOT NULL,
    [INVOICESTATUS_LT]               INT              NOT NULL,
    [INVENTPROFILETYPE_RU]           INT              NOT NULL,
    [TAXINVOICEPURCHID]              NVARCHAR (20)    NOT NULL,
    [NUMBERSEQUENCECODE_LT]          NVARCHAR (10)    NOT NULL,
    [CORRECTEDINVOICEDATE_RU]        DATETIME         NOT NULL,
    [VATAMOUNT_IN]                   NUMERIC (32, 16) NOT NULL,
    [TAXWITHHOLDAMOUNT_IN]           NUMERIC (32, 16) NOT NULL,
    [VENDCONSINVOICE_JP]             BIGINT           NOT NULL,
    [DELIVERYNAME_LT]                NVARCHAR (100)   NOT NULL,
    [DELIVERYADDRESS_LT]             NVARCHAR (250)   NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]    DATETIME         NOT NULL,
    [UNITEDVATINVOICE_LT]            INT              NOT NULL,
    [NONREALREVENUE_RU]              INT              NOT NULL,
    [OFFSESSIONID_RU]                NVARCHAR (20)    NOT NULL,
    [CONSIGNEEACCOUNT_RU]            NVARCHAR (20)    NOT NULL,
    [CONSIGNORACCOUNT_RU]            NVARCHAR (20)    NOT NULL,
    [FACTUREDFULLY_RU]               INT              NOT NULL,
    [ATTORNEYISSUEDNAME_RU]          NVARCHAR (30)    NOT NULL,
    [ATTORNEYID_RU]                  NVARCHAR (30)    NOT NULL,
    [ATTORNEYDATE_RU]                DATETIME         NOT NULL,
    [STATEINVOICEPRINTED_LV]         INT              NOT NULL,
    [DLVADDRESS_LV]                  NVARCHAR (250)   NOT NULL,
    [INTRASTATADDVALUE_LV]           NUMERIC (32, 16) NOT NULL,
    [INVOICEREGISTER_LT]             INT              NOT NULL,
    [PURCHAGREEMENTHEADER_PSN]       BIGINT           NOT NULL,
    [CONSTARGET_JP]                  INT              NOT NULL,
    [CORRECTEDINVOICEID_RU]          NVARCHAR (20)    NOT NULL,
    [CORRECTIONTYPE_RU]              INT              NOT NULL,
    [DELIVERYPOSTALADDRESS]          BIGINT           NOT NULL,
    [FISCALDOCUMENTTYPE_BR]          BIGINT           NOT NULL,
    [INVENTBAILEERECEIPTREPORTID_RU] NVARCHAR (20)    NOT NULL,
    [REASONTABLEREF_BR]              BIGINT           NOT NULL,
    [SALESPURCHOPERATIONTYPE_BR]     BIGINT           NOT NULL,
    [SERVICECODEONDLVADDRESS_BR]     INT              NOT NULL,
    [TAXSETOFFVOUCHER_IN]            NVARCHAR (20)    NOT NULL,
    [TRANSITCONTROLVOUCHER_BR]       NVARCHAR (20)    NOT NULL,
    [TRANSPORTATIONDOCUMENT]         BIGINT           NOT NULL,
    [VENDFINALUSER_BR]               INT              NOT NULL,
    [CFDIUUID_MX]                    NVARCHAR (36)    NOT NULL,
    [INVOICESERIES_MX]               NVARCHAR (10)    NOT NULL,
    [MODIFIEDDATETIME]               DATETIME         NOT NULL,
    [CREATEDDATETIME]                DATETIME         NOT NULL,
    [CREATEDBY]                      NVARCHAR (8)     NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     NOT NULL,
    [RECVERSION]                     INT              NOT NULL,
    [PARTITION]                      BIGINT           NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    CONSTRAINT [I_491RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

