CREATE TABLE [dbo].[VENDTRANS] (
    [ACCOUNTNUM]                        NVARCHAR (20)    NOT NULL,
    [TRANSDATE]                         DATETIME         NOT NULL,
    [VOUCHER]                           NVARCHAR (20)    NOT NULL,
    [INVOICE]                           NVARCHAR (20)    NOT NULL,
    [TXT]                               NVARCHAR (60)    NOT NULL,
    [AMOUNTCUR]                         NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTCUR]                   NUMERIC (32, 16) NOT NULL,
    [AMOUNTMST]                         NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTMST]                   NUMERIC (32, 16) NOT NULL,
    [CURRENCYCODE]                      NVARCHAR (3)     NOT NULL,
    [DUEDATE]                           DATETIME         NOT NULL,
    [LASTSETTLEVOUCHER]                 NVARCHAR (20)    NOT NULL,
    [LASTSETTLEDATE]                    DATETIME         NOT NULL,
    [CLOSED]                            DATETIME         NOT NULL,
    [TRANSTYPE]                         INT              NOT NULL,
    [APPROVED]                          INT              NOT NULL,
    [PAYMID]                            NVARCHAR (200)   NOT NULL,
    [EXCHADJUSTMENT]                    NUMERIC (32, 16) NOT NULL,
    [DOCUMENTNUM]                       NVARCHAR (20)    NOT NULL,
    [DOCUMENTDATE]                      DATETIME         NOT NULL,
    [ARRIVAL]                           INT              NOT NULL,
    [LASTEXCHADJ]                       DATETIME         NOT NULL,
    [CORRECT]                           INT              NOT NULL,
    [LASTEXCHADJVOUCHER]                NVARCHAR (20)    NOT NULL,
    [LASTEXCHADJRATE]                   NUMERIC (32, 16) NOT NULL,
    [POSTINGPROFILE]                    NVARCHAR (10)    NOT NULL,
    [SETTLEMENT]                        INT              NOT NULL,
    [CANCEL]                            INT              NOT NULL,
    [POSTINGPROFILECLOSE]               NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILEAPPROVE]             NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILECANCEL]              NVARCHAR (10)    NOT NULL,
    [POSTINGPROFILEREOPEN]              NVARCHAR (10)    NOT NULL,
    [THIRDPARTYBANKACCOUNTID]           NVARCHAR (10)    NOT NULL,
    [COMPANYBANKACCOUNTID]              NVARCHAR (10)    NOT NULL,
    [PAYMREFERENCE]                     NVARCHAR (20)    NOT NULL,
    [PAYMMODE]                          NVARCHAR (10)    NOT NULL,
    [TAX1099DATE]                       DATETIME         NOT NULL,
    [TAX1099AMOUNT]                     NUMERIC (32, 16) NOT NULL,
    [TAX1099NUM]                        NVARCHAR (20)    NOT NULL,
    [OFFSETRECID]                       BIGINT           NOT NULL,
    [JOURNALNUM]                        NVARCHAR (10)    NOT NULL,
    [EUROTRIANGULATION]                 INT              NOT NULL,
    [CASHDISCCODE]                      NVARCHAR (10)    NOT NULL,
    [PREPAYMENT]                        INT              NOT NULL,
    [PAYMSPEC]                          NVARCHAR (10)    NOT NULL,
    [VENDEXCHADJUSTMENTREALIZED]        NUMERIC (32, 16) NOT NULL,
    [VENDEXCHADJUSTMENTUNREALIZED]      NUMERIC (32, 16) NOT NULL,
    [APPROVEDDATE]                      DATETIME         NOT NULL,
    [PROMISSORYNOTEID]                  NVARCHAR (20)    NOT NULL,
    [PROMISSORYNOTESTATUS]              INT              NOT NULL,
    [PROMISSORYNOTESEQNUM]              INT              NOT NULL,
    [BANKREMITTANCEFILEID]              NVARCHAR (10)    NOT NULL,
    [FIXEDEXCHRATE]                     INT              NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]        NVARCHAR (140)   NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]        NVARCHAR (10)    NOT NULL,
    [TAX1099STATE]                      NVARCHAR (10)    NOT NULL,
    [TAX1099STATEAMOUNT]                NUMERIC (32, 16) NOT NULL,
    [SETTLETAX1099AMOUNT]               NUMERIC (32, 16) NOT NULL,
    [SETTLETAX1099STATEAMOUNT]          NUMERIC (32, 16) NOT NULL,
    [DEFAULTDIMENSION]                  BIGINT           NOT NULL,
    [EXCHRATESECOND]                    NUMERIC (32, 16) NOT NULL,
    [EXCHRATE]                          NUMERIC (32, 16) NOT NULL,
    [LASTSETTLEACCOUNTNUM]              NVARCHAR (20)    NOT NULL,
    [LASTSETTLECOMPANY]                 NVARCHAR (4)     NOT NULL,
    [INVOICEPROJECT]                    INT              NOT NULL,
    [REASONREFRECID]                    BIGINT           NOT NULL,
    [RELEASEDATECOMMENT]                NVARCHAR (60)    NOT NULL,
    [INVOICERELEASEDATE]                DATETIME         NOT NULL,
    [INVOICERELEASEDATETZID]            INT              NOT NULL,
    [VENDPAYMENTGROUP]                  NVARCHAR (10)    NOT NULL,
    [REMITTANCELOCATION]                BIGINT           NOT NULL,
    [REMITTANCEADDRESS]                 BIGINT           NOT NULL,
    [TAX1099FIELDS]                     BIGINT           NOT NULL,
    [BANKLCIMPORTLINE]                  BIGINT           NOT NULL,
    [ACCOUNTINGEVENT]                   BIGINT           NOT NULL,
    [APPROVER]                          BIGINT           NOT NULL,
    [REPORTINGCURRENCYAMOUNT]           NUMERIC (32, 16) NOT NULL,
    [REPORTINGEXCHADJUSTMENTREALIZED]   NUMERIC (32, 16) NOT NULL,
    [REPORTINGEXCHADJUSTMENTUNREALIZED] NUMERIC (32, 16) NOT NULL,
    [LASTEXCHADJRATEREPORTING]          NUMERIC (32, 16) NOT NULL,
    [REPORTINGCURRENCYCROSSRATE]        NUMERIC (32, 16) NOT NULL,
    [EXCHADJUSTMENTREPORTING]           NUMERIC (32, 16) NOT NULL,
    [SETTLEAMOUNTREPORTING]             NUMERIC (32, 16) NOT NULL,
    [TAXINVOICEPURCHID]                 NVARCHAR (20)    NOT NULL,
    [TAX1099RECID]                      BIGINT           NOT NULL,
    [CONSESSIONSETTLEMENTID]            NVARCHAR (10)    NOT NULL,
    [RBOVENDTRANS]                      INT              NOT NULL,
    [MODIFIEDDATETIME]                  DATETIME         NOT NULL,
    [DEL_MODIFIEDTIME]                  INT              NOT NULL,
    [MODIFIEDBY]                        NVARCHAR (8)     NOT NULL,
    [MODIFIEDTRANSACTIONID]             BIGINT           NOT NULL,
    [CREATEDDATETIME]                   DATETIME         NOT NULL,
    [DEL_CREATEDTIME]                   INT              NOT NULL,
    [CREATEDBY]                         NVARCHAR (8)     NOT NULL,
    [CREATEDTRANSACTIONID]              BIGINT           NOT NULL,
    [DATAAREAID]                        NVARCHAR (4)     NOT NULL,
    [RECVERSION]                        INT              NOT NULL,
    [PARTITION]                         BIGINT           NOT NULL,
    [RECID]                             BIGINT           NOT NULL,
    [ROLBOLDATE]                        DATETIME         NOT NULL,
    [ROLFDADATE]                        DATETIME         NOT NULL,
    [ROLPAYMTERMID]                     NVARCHAR (10)    NOT NULL,
    [ROLVESSELETADATE]                  DATETIME         NOT NULL
);

