CREATE TABLE [dbo].[VENDPACKINGSLIPTRANS] (
    [PACKINGSLIPID]                    NVARCHAR (20)    NOT NULL,
    [DELIVERYDATE]                     DATETIME         NOT NULL,
    [LINENUM]                          NUMERIC (32, 16) NOT NULL,
    [INVENTTRANSID]                    NVARCHAR (20)    NOT NULL,
    [DESTCOUNTRYREGIONID]              NVARCHAR (10)    NOT NULL,
    [ITEMID]                           NVARCHAR (20)    NOT NULL,
    [EXTERNALITEMID]                   NVARCHAR (20)    NOT NULL,
    [NAME]                             NVARCHAR (1000)  NOT NULL,
    [ORDERED]                          NUMERIC (32, 16) NOT NULL,
    [QTY]                              NUMERIC (32, 16) NOT NULL,
    [REMAIN]                           NUMERIC (32, 16) NOT NULL,
    [DEL_PURCHASER]                    NVARCHAR (20)    NOT NULL,
    [PRICEUNIT]                        NUMERIC (32, 16) NOT NULL,
    [VALUEMST]                         NUMERIC (32, 16) NOT NULL,
    [INVENTREFID]                      NVARCHAR (20)    NOT NULL,
    [INVENTREFTYPE]                    INT              NOT NULL,
    [PURCHUNIT]                        NVARCHAR (10)    NOT NULL,
    [TRANSACTIONCODE]                  NVARCHAR (10)    NOT NULL,
    [INVENTREFTRANSID]                 NVARCHAR (20)    NOT NULL,
    [INTERCOMPANYINVENTTRANSID]        NVARCHAR (20)    NOT NULL,
    [DESTSTATE]                        NVARCHAR (10)    NOT NULL,
    [REMAININVENT]                     NUMERIC (32, 16) NOT NULL,
    [ORIGPURCHID]                      NVARCHAR (20)    NOT NULL,
    [RETURNACTIONID]                   NVARCHAR (10)    NOT NULL,
    [TRANSPORT]                        NVARCHAR (10)    NOT NULL,
    [INVENTDIMID]                      NVARCHAR (20)    NOT NULL,
    [STATPROCID]                       NVARCHAR (10)    NOT NULL,
    [PORT]                             NVARCHAR (10)    NOT NULL,
    [INVENTDATE]                       DATETIME         NOT NULL,
    [NUMBERSEQUENCEGROUP]              NVARCHAR (10)    NOT NULL,
    [DESTCOUNTY]                       NVARCHAR (10)    NOT NULL,
    [INTRASTATDISPATCHID]              NVARCHAR (20)    NOT NULL,
    [INVENTQTY]                        NUMERIC (32, 16) NOT NULL,
    [REASONTABLEREF]                   BIGINT           NOT NULL,
    [PROCUREMENTCATEGORY]              BIGINT           NOT NULL,
    [ITEMCODEID]                       NVARCHAR (15)    NOT NULL,
    [ORIGSTATEID]                      NVARCHAR (10)    NOT NULL,
    [ORIGCOUNTRYREGIONID]              NVARCHAR (10)    NOT NULL,
    [WEIGHT]                           NUMERIC (32, 16) NOT NULL,
    [DEFAULTDIMENSION]                 BIGINT           NOT NULL,
    [SOURCEDOCUMENTLINE]               BIGINT           NOT NULL,
    [WORKERPURCHASER]                  BIGINT           NOT NULL,
    [PURCHASELINEEXPECTEDDELIVERYDATE] DATETIME         NOT NULL,
    [PURCHASELINELINENUMBER]           BIGINT           NOT NULL,
    [VENDPACKINGSLIPJOUR]              BIGINT           NOT NULL,
    [FULLYMATCHED]                     INT              NOT NULL,
    [COSTLEDGERVOUCHER]                NVARCHAR (20)    NOT NULL,
    [ACCOUNTINGDATE]                   DATETIME         NOT NULL,
    [STOCKEDPRODUCT]                   INT              NOT NULL,
    [NGPCODESTABLE_FR]                 BIGINT           NOT NULL,
    [RECEIVEDQTY_IN]                   NUMERIC (32, 16) NOT NULL,
    [REJECTEDQTY_IN]                   NUMERIC (32, 16) NOT NULL,
    [ACCEPTEDQTY_IN]                   NUMERIC (32, 16) NOT NULL,
    [INVOICETRANSREFRECID]             BIGINT           NOT NULL,
    [INTRASTATFULFILLMENTDATE_HU]      DATETIME         NOT NULL,
    [CURRENCYCODE_W]                   NVARCHAR (3)     NOT NULL,
    [DEVIATIONQTY_RU]                  NUMERIC (32, 16) NOT NULL,
    [EXCISEVALUE_RU]                   NUMERIC (32, 16) NOT NULL,
    [VATVALUE_RU]                      NUMERIC (32, 16) NOT NULL,
    [EXCISEAMOUNT_RU]                  NUMERIC (32, 16) NOT NULL,
    [VATAMOUNT_RU]                     NUMERIC (32, 16) NOT NULL,
    [LINEAMOUNT_W]                     NUMERIC (32, 16) NOT NULL,
    [TAXAMOUNT_RU]                     NUMERIC (32, 16) NOT NULL,
    [TAXITEMGROUP_RU]                  NVARCHAR (10)    NOT NULL,
    [TAXGROUP_RU]                      NVARCHAR (10)    NOT NULL,
    [STATISTICVALUE_LT]                NUMERIC (32, 16) NOT NULL,
    [PDSCWORDERED]                     NUMERIC (32, 16) NOT NULL,
    [PDSCWQTY]                         NUMERIC (32, 16) NOT NULL,
    [PDSCWREMAIN]                      NUMERIC (32, 16) NOT NULL,
    [DATAAREAID]                       NVARCHAR (4)     NOT NULL,
    [RECVERSION]                       INT              NOT NULL,
    [PARTITION]                        BIGINT           NOT NULL,
    [RECID]                            BIGINT           NOT NULL,
    CONSTRAINT [I_501RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

