CREATE TABLE [dbo].[VENDINVOICEPURCHLINK] (
    [INVOICEID]         NVARCHAR (20) NOT NULL,
    [INVOICEDATE]       DATETIME      NOT NULL,
    [PURCHID]           NVARCHAR (20) NOT NULL,
    [ORIGPURCHID]       NVARCHAR (20) NOT NULL,
    [INVOICEACCOUNT]    NVARCHAR (20) NOT NULL,
    [ORDERACCOUNT]      NVARCHAR (20) NOT NULL,
    [PARMID]            NVARCHAR (20) NOT NULL,
    [INTERNALINVOICEID] NVARCHAR (20) NOT NULL,
    [DATAAREAID]        NVARCHAR (4)  NOT NULL,
    [RECVERSION]        INT           NOT NULL,
    [PARTITION]         BIGINT        NOT NULL,
    [RECID]             BIGINT        NOT NULL,
    CONSTRAINT [I_1509RECID] PRIMARY KEY CLUSTERED ([RECID] ASC)
);

