CREATE TABLE [dbo].[VENDINVOICEINFOLINE] (
    [REMAINBEFOREINVENT]             NUMERIC (32, 16) NOT NULL,
    [REMAINAFTERINVENT]              NUMERIC (32, 16) NOT NULL,
    [INVENTNOW]                      NUMERIC (32, 16) NOT NULL,
    [REMAINAFTER]                    NUMERIC (32, 16) NOT NULL,
    [REMAINBEFORE]                   NUMERIC (32, 16) NOT NULL,
    [RECEIVENOW]                     NUMERIC (32, 16) NOT NULL,
    [LINENUM]                        NUMERIC (32, 16) NOT NULL,
    [ITEMID]                         NVARCHAR (20)    NOT NULL,
    [DELIVERYNAME]                   NVARCHAR (100)   NOT NULL,
    [LINEPERCENT]                    NUMERIC (32, 16) NOT NULL,
    [PURCHMARKUP]                    NUMERIC (32, 16) NOT NULL,
    [PRICEUNIT]                      NUMERIC (32, 16) NOT NULL,
    [MULTILNDISC]                    NUMERIC (32, 16) NOT NULL,
    [LINEDISC]                       NUMERIC (32, 16) NOT NULL,
    [PURCHPRICE]                     NUMERIC (32, 16) NOT NULL,
    [MULTILNPERCENT]                 NUMERIC (32, 16) NOT NULL,
    [LINEAMOUNT]                     NUMERIC (32, 16) NOT NULL,
    [ORDERACCOUNT]                   NVARCHAR (20)    NOT NULL,
    [PURCHLINERECID]                 BIGINT           NOT NULL,
    [INVOICEACCOUNT]                 NVARCHAR (20)    NOT NULL,
    [CLOSED]                         INT              NOT NULL,
    [CHANGEDMANUALLY]                INT              NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     NOT NULL,
    [INVENTTRANSID]                  NVARCHAR (20)    NOT NULL,
    [INVENTDIMID]                    NVARCHAR (20)    NOT NULL,
    [ORIGPURCHID]                    NVARCHAR (20)    NOT NULL,
    [TABLEREFID]                     NVARCHAR (20)    NOT NULL,
    [TAX1099AMOUNT]                  NUMERIC (32, 16) NOT NULL,
    [TAX1099STATE]                   NVARCHAR (10)    NOT NULL,
    [TAX1099STATEAMOUNT]             NUMERIC (32, 16) NOT NULL,
    [TAXITEMGROUP]                   NVARCHAR (10)    NOT NULL,
    [TAXGROUP]                       NVARCHAR (10)    NOT NULL,
    [DESCRIPTION]                    NVARCHAR (1000)  NOT NULL,
    [PROCUREMENTCATEGORY]            BIGINT           NOT NULL,
    [DELIVERYPOSTALADDRESS]          BIGINT           NOT NULL,
    [PARMID]                         NVARCHAR (20)    NOT NULL,
    [REMAINBEFOREINVENTPHYSICAL]     NUMERIC (32, 16) NOT NULL,
    [INVOICEINFOTABLEREFID]          NVARCHAR (20)    NOT NULL,
    [REASONTABLEREF]                 BIGINT           NOT NULL,
    [TAX1099FIELDS]                  BIGINT           NOT NULL,
    [CREATEDFROMLINE]                BIGINT           NOT NULL,
    [REQUESTSTATUS]                  INT              NOT NULL,
    [TRANSACTIONCODE]                NVARCHAR (10)    NOT NULL,
    [TRANSPORT]                      NVARCHAR (10)    NOT NULL,
    [PORT]                           NVARCHAR (10)    NOT NULL,
    [STATPROCID]                     NVARCHAR (10)    NOT NULL,
    [COUNTYORIGDEST]                 NVARCHAR (10)    NOT NULL,
    [PURCHUNIT]                      NVARCHAR (10)    NOT NULL,
    [DEFAULTDIMENSION]               BIGINT           NOT NULL,
    [PURCHASELINELINENUMBER]         BIGINT           NOT NULL,
    [SOURCEDOCUMENTLINE]             BIGINT           NOT NULL,
    [LINETYPE]                       INT              NOT NULL,
    [ACCOUNTINGDISTRIBUTIONTEMPLATE] BIGINT           NOT NULL,
    [ADVANCEAPPLICATIONID]           BIGINT           NOT NULL,
    [TAX1099BOXDETAIL]               BIGINT           NOT NULL,
    [AGREEMENTLINE_PSN]              BIGINT           NOT NULL,
    [PAYROLLLEDGERDIMENSION]         BIGINT           NOT NULL,
    [PDSCALCULATEDUNITPRICE]         NUMERIC (32, 16) NOT NULL,
    [PDSCALCULATIONID]               NVARCHAR (10)    NOT NULL,
    [PDSCWRECEIVENOW]                NUMERIC (32, 16) NOT NULL,
    [PDSCWREMAINAFTER]               NUMERIC (32, 16) NOT NULL,
    [PDSCWREMAINBEFORE]              NUMERIC (32, 16) NOT NULL,
    [PSAISFINAL]                     INT              NOT NULL,
    [PSARELEASEAMOUNT]               NUMERIC (32, 16) NOT NULL,
    [PSARELEASEPERCENT]              NUMERIC (32, 16) NOT NULL,
    [PSARETAINAGEAMOUNT]             NUMERIC (32, 16) NOT NULL,
    [PSARETAINAGEBALANCE]            NUMERIC (32, 16) NOT NULL,
    [PSARETAINAGEPERCENT]            NUMERIC (32, 16) NOT NULL,
    [PURCHCOMMITMENTLINE_PSN]        BIGINT           NOT NULL,
    [TAXWITHHOLDGROUP]               NVARCHAR (10)    NOT NULL,
    [TAXWITHHOLDITEMGROUPHEADINGID]  BIGINT           NOT NULL,
    [VENDDIRECTIVE_PSN]              BIGINT           NOT NULL,
    [BUDGETRESERVATIONLINE_PSN]      BIGINT           NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     NOT NULL,
    [RECVERSION]                     INT              NOT NULL,
    [PARTITION]                      BIGINT           NOT NULL,
    [RECID]                          BIGINT           NOT NULL
);

