CREATE TABLE [dbo].[VENDTABLE] (
    [ACCOUNTNUM]                      NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVOICEACCOUNT]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [VENDGROUP]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMTERMID]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CASHDISC]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CURRENCY]                        NVARCHAR (3)     DEFAULT ('') NOT NULL,
    [LINEDISC]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENTERPRISENUMBER]                NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [BLOCKED]                         INT              DEFAULT ((0)) NOT NULL,
    [ONETIMEVENDOR]                   INT              DEFAULT ((0)) NOT NULL,
    [PRICEGROUP]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MULTILINEDISC]                   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ENDDISC]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMID]                          NVARCHAR (200)   DEFAULT ('') NOT NULL,
    [VATNUM]                          NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [INVENTLOCATION]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [YOURACCOUNTNUM]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [DLVTERM]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DLVMODE]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BANKACCOUNT]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMMODE]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMSPEC]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MARKUPGROUP]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CLEARINGPERIOD]                  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [COMPANYIDSIRET]                  NVARCHAR (14)    DEFAULT ('') NOT NULL,
    [TAXGROUP]                        NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FREIGHTZONE]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MINORITYOWNED]                   INT              DEFAULT ((0)) NOT NULL,
    [FEMALEOWNED]                     INT              DEFAULT ((0)) NOT NULL,
    [CREDITRATING]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CREDITMAX]                       NUMERIC (32, 16) DEFAULT ((0)) NOT NULL,
    [TAX1099REPORTS]                  INT              DEFAULT ((0)) NOT NULL,
    [TAX1099REGNUM]                   NVARCHAR (11)    DEFAULT ('') NOT NULL,
    [PAYMSCHED]                       NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [ITEMBUYERGROUPID]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CONTACTPERSONID]                 NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PURCHPOOLID]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PURCHAMOUNTPURCHASEORDER]        INT              DEFAULT ((0)) NOT NULL,
    [INCLTAX]                         INT              DEFAULT ((0)) NOT NULL,
    [VENDITEMGROUPID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NUMBERSEQUENCEGROUP]             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [PAYMDAYID]                       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DESTINATIONCODEID]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [LINEOFBUSINESSID]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SUPPITEMGROUPID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BANKCENTRALBANKPURPOSETEXT]      NVARCHAR (140)   DEFAULT ('') NOT NULL,
    [BANKCENTRALBANKPURPOSECODE]      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [OFFSETACCOUNTTYPE]               INT              DEFAULT ((0)) NOT NULL,
    [PURCHCALENDARID]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ORGANIZATIONNUMBER]              NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [FISCALCODE]                      NVARCHAR (16)    DEFAULT ('') NOT NULL,
    [TAXWITHHOLDCALCULATE]            INT              DEFAULT ((0)) NOT NULL,
    [TAXWITHHOLDGROUP]                NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BIRTHDATE]                       DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [BIRTHPLACE]                      NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [RESIDENCEFOREIGNCOUNTRYREGIONID] NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NAMECONTROL]                     NVARCHAR (4)     DEFAULT ('') NOT NULL,
    [FOREIGNENTITYINDICATOR]          INT              DEFAULT ((0)) NOT NULL,
    [TAXIDTYPE]                       INT              DEFAULT ((0)) NOT NULL,
    [DBA]                             NVARCHAR (60)    DEFAULT ('') NOT NULL,
    [TAX1099NAMECHOICE]               INT              DEFAULT ((0)) NOT NULL,
    [SECONDTIN]                       INT              DEFAULT ((0)) NOT NULL,
    [INVENTSITEID]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [SEGMENTID]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [SUBSEGMENTID]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [COMPANYCHAINID]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [VENDPRICETOLERANCEGROUPID]       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [MEMO]                            NVARCHAR (MAX)   DEFAULT (NULL) NULL,
    [SMALLBUSINESS]                   INT              DEFAULT ((0)) NOT NULL,
    [LOCALLYOWNED]                    INT              DEFAULT ((0)) NOT NULL,
    [BIDONLY]                         INT              DEFAULT ((0)) NOT NULL,
    [W9]                              INT              DEFAULT ((0)) NOT NULL,
    [ORGID]                           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FACTORINGACCOUNT]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [MATCHINGPOLICY]                  INT              DEFAULT ((0)) NOT NULL,
    [BLOCKEDRELEASEDATE]              DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [BLOCKEDRELEASEDATETZID]          INT              DEFAULT ((37001)) NOT NULL,
    [W9INCLUDED]                      INT              DEFAULT ((0)) NOT NULL,
    [VENDEXCEPTIONGROUP]              BIGINT           DEFAULT ((0)) NOT NULL,
    [PARTY]                           BIGINT           DEFAULT ((0)) NOT NULL,
    [DEFAULTDIMENSION]                BIGINT           DEFAULT ((0)) NOT NULL,
    [OFFSETLEDGERDIMENSION]           BIGINT           DEFAULT ((0)) NOT NULL,
    [BIRTHCOUNTYCODE_IT]              NVARCHAR (2)     DEFAULT ('') NOT NULL,
    [HEIR_IT]                         INT              DEFAULT ((0)) NOT NULL,
    [CHANGEREQUESTENABLED]            INT              DEFAULT ((0)) NOT NULL,
    [CHANGEREQUESTALLOWOVERRIDE]      INT              DEFAULT ((0)) NOT NULL,
    [CHANGEREQUESTOVERRIDE]           INT              DEFAULT ((0)) NOT NULL,
    [COMPANYNAFCODE]                  BIGINT           DEFAULT ((0)) NOT NULL,
    [VENDINVOICEDECLARATION_IS]       BIGINT           DEFAULT ((0)) NOT NULL,
    [TAX1099FIELDS]                   BIGINT           DEFAULT ((0)) NOT NULL,
    [VENDORTYPE_MX]                   INT              DEFAULT ((0)) NOT NULL,
    [FOREIGNTAXREGISTRATION_MX]       NVARCHAR (40)    DEFAULT ('') NOT NULL,
    [NATIONALITY_MX]                  NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [DIOTCOUNTRYCODE_MX]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [OPERATIONTYPE_MX]                INT              DEFAULT ((0)) NOT NULL,
    [MAINCONTACTWORKER]               BIGINT           DEFAULT ((0)) NOT NULL,
    [COMPANYTYPE_MX]                  INT              DEFAULT ((0)) NOT NULL,
    [RFC_MX]                          NVARCHAR (13)    DEFAULT ('') NOT NULL,
    [CURP_MX]                         NVARCHAR (18)    DEFAULT ('') NOT NULL,
    [STATEINSCRIPTION_MX]             NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [CCMNUM_BR]                       NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [IENUM_BR]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [CNPJCPFNUM_BR]                   NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [VENDINCOMECODE_BR]               NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [NONTAXABLE_BR]                   INT              DEFAULT ((0)) NOT NULL,
    [VENDCONSUMPTION_BR]              INT              DEFAULT ((0)) NOT NULL,
    [NIT_BR]                          NVARCHAR (14)    DEFAULT ('') NOT NULL,
    [INSSCEI_BR]                      NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [CNAE_BR]                         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ICMSCONTRIBUTOR_BR]              INT              DEFAULT ((0)) NOT NULL,
    [SERVICECODEONDLVADDRESS_BR]      INT              DEFAULT ((0)) NOT NULL,
    [INTERESTCODE_BR]                 NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [FINECODE_BR]                     NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VATTAXAGENT_RU]                  INT              DEFAULT ((0)) NOT NULL,
    [TAXWITHHOLDVENDORTYPE_TH]        INT              DEFAULT ((0)) NOT NULL,
    [VATOPERATIONCODE_RU]             NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [VATPARTNERKIND_RU]               INT              DEFAULT ((0)) NOT NULL,
    [INVENTPROFILETYPE_RU]            INT              DEFAULT ((0)) NOT NULL,
    [INVENTPROFILEID_RU]              NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [UNITEDVATINVOICE_LT]             INT              DEFAULT ((0)) NOT NULL,
    [CONSDAY_JP]                      INT              DEFAULT ((0)) NOT NULL,
    [STRUCTDEPARTMENT_RU]             NVARCHAR (30)    DEFAULT ('') NOT NULL,
    [BANKCENTRALBANKTRANSTYPECUR_RU]  NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [BANKORDEROFPAYMENT_RU]           NVARCHAR (2)     DEFAULT ('') NOT NULL,
    [ENTERPRISECODE]                  NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [REGNUM_W]                        NVARCHAR (25)    DEFAULT ('') NOT NULL,
    [COMMERCIALREGISTERSECTION]       NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [COMMERCIALREGISTERINSETNUMBER]   NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [COMMERCIALREGISTER]              NVARCHAR (40)    DEFAULT ('') NOT NULL,
    [ISRESIDENT_LV]                   INT              DEFAULT ((0)) NOT NULL,
    [INTBANK_LV]                      NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CISCOMPANYREGNUM]                NVARCHAR (8)     DEFAULT ('') NOT NULL,
    [CISNATIONALINSURANCENUM]         NVARCHAR (9)     DEFAULT ('') NOT NULL,
    [CISSTATUS]                       INT              DEFAULT ((0)) NOT NULL,
    [CISUNIQUETAXPAYERREF]            NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [CISVERIFICATIONDATE]             DATETIME         DEFAULT ('1900-01-01 00:00:00.000') NOT NULL,
    [CISVERIFICATIONNUM]              NVARCHAR (13)    DEFAULT ('') NOT NULL,
    [DEFAULTINVENTSTATUSID]           NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [DISABLEDOWNED]                   INT              DEFAULT ((0)) NOT NULL,
    [ETHNICORIGINID]                  NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [FOREIGNRESIDENT_RU]              INT              DEFAULT ((0)) NOT NULL,
    [HUBZONE]                         INT              DEFAULT ((0)) NOT NULL,
    [ISPAYMFEECOVERED_JP]             INT              DEFAULT ((0)) NOT NULL,
    [LVPAYMTRANSCODES]                BIGINT           DEFAULT ((0)) NOT NULL,
    [MANDATORYVATDATE_PL]             INT              DEFAULT ((0)) NOT NULL,
    [SEPARATEDIVISIONID_RU]           NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [TAMREBATEGROUPID]                NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [TAXPERIODPAYMENTCODE_PL]         NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [USECASHDISC]                     INT              DEFAULT ((0)) NOT NULL,
    [VETERANOWNED]                    INT              DEFAULT ((0)) NOT NULL,
    [FATCAFILINGREQUIREMENT]          INT              DEFAULT ((0)) NOT NULL,
    [FOREIGNERID_BR]                  NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [PRESENCETYPE_BR]                 INT              DEFAULT ((0)) NOT NULL,
    [VENDORPORTALADMINISTRATORRECID]  BIGINT           DEFAULT ((0)) NOT NULL,
    [VENDPAYMFEEGROUP_JP]             NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [MODIFIEDDATETIME]                DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_MODIFIEDTIME]                INT              DEFAULT ((0)) NOT NULL,
    [MODIFIEDBY]                      NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [CREATEDDATETIME]                 DATETIME         DEFAULT (dateadd(millisecond, -datepart(millisecond,getutcdate()),getutcdate())) NOT NULL,
    [DEL_CREATEDTIME]                 INT              DEFAULT ((0)) NOT NULL,
    [CREATEDBY]                       NVARCHAR (8)     DEFAULT ('?') NOT NULL,
    [DATAAREAID]                      NVARCHAR (4)     DEFAULT ('dat') NOT NULL,
    [RECVERSION]                      INT              DEFAULT ((1)) NOT NULL,
    [PARTITION]                       BIGINT           DEFAULT ((5637144576.)) NOT NULL,
    [RECID]                           BIGINT           NOT NULL,
    [VSIRECCOUNT]                     BIGINT           DEFAULT ((0)) NOT NULL,
    [ROLAGENT]                        NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [ROLFCENUMBER]                    NVARCHAR (10)    DEFAULT ('') NOT NULL,
    [ROLFDAREGISTRATION]              NVARCHAR (15)    DEFAULT ('') NOT NULL,
    [ROLMIDNUMBER]                    NVARCHAR (20)    DEFAULT ('') NOT NULL,
    [RFLI_EDIACKNOWLEDGMENT]          INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDICUSTOMSBROKERPO]         INT              DEFAULT ((0)) NOT NULL,
    [RFLI_EDICUSTOMSISF]              INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [I_505ACCOUNTIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [ACCOUNTNUM] ASC),
    CHECK ([RECID]<>(0)),
    CHECK ([RECID]<>(0))
);


GO
CREATE NONCLUSTERED INDEX [VW_INDX_VENDTBL_VG]
    ON [dbo].[VENDTABLE]([VENDGROUP] ASC)
    INCLUDE([ACCOUNTNUM], [PARTY], [DATAAREAID], [PARTITION]);

