CREATE TABLE [dbo].[VENDINVOICEINFOTABLE] (
    [DELIVERYNAME]                   NVARCHAR (100)   NOT NULL,
    [PURCHID]                        NVARCHAR (20)    NOT NULL,
    [ORDERING]                       INT              NOT NULL,
    [BATCHADMINISTRATION]            INT              NOT NULL,
    [TRANSDATE]                      DATETIME         NOT NULL,
    [NUM]                            NVARCHAR (20)    NOT NULL,
    [DOCUMENTDATE]                   DATETIME         NOT NULL,
    [DOCUMENTNUM]                    NVARCHAR (20)    NOT NULL,
    [PAYMID]                         NVARCHAR (200)   NOT NULL,
    [CASHDISC]                       NUMERIC (32, 16) NOT NULL,
    [INVOICEROUNDOFF]                NUMERIC (32, 16) NOT NULL,
    [TAXROUNDOFF]                    NUMERIC (32, 16) NOT NULL,
    [ENDDISC]                        NUMERIC (32, 16) NOT NULL,
    [APPROVED]                       INT              NOT NULL,
    [PURCHNAME]                      NVARCHAR (60)    NOT NULL,
    [ORDERACCOUNT]                   NVARCHAR (20)    NOT NULL,
    [CASHDISCDATE]                   DATETIME         NOT NULL,
    [STORNO]                         INT              NOT NULL,
    [INVOICEACCOUNT]                 NVARCHAR (20)    NOT NULL,
    [DOCUMENTORIGIN]                 INT              NOT NULL,
    [CURRENCYCODE]                   NVARCHAR (3)     NOT NULL,
    [DESCRIPTION]                    NVARCHAR (50)    NOT NULL,
    [LOG]                            NVARCHAR (255)   NOT NULL,
    [PAYMMODE]                       NVARCHAR (10)    NOT NULL,
    [PAYMSPEC]                       NVARCHAR (10)    NOT NULL,
    [RECALCULATE]                    INT              NOT NULL,
    [VENDBANKACCOUNTID]              NVARCHAR (10)    NOT NULL,
    [PAYMENT]                        NVARCHAR (10)    NOT NULL,
    [FIXEDEXCHRATE]                  INT              NOT NULL,
    [EUROTRIANGULATION]              INT              NOT NULL,
    [EXCHRATE]                       NUMERIC (32, 16) NOT NULL,
    [EXCHRATESECONDARY]              NUMERIC (32, 16) NOT NULL,
    [FIXEDDUEDATE]                   DATETIME         NOT NULL,
    [PAYMENTSCHED]                   NVARCHAR (30)    NOT NULL,
    [CASHDISCCODE]                   NVARCHAR (10)    NOT NULL,
    [CASHDISCPERCENT]                NUMERIC (32, 16) NOT NULL,
    [TAXGROUP]                       NVARCHAR (10)    NOT NULL,
    [TABLEREFID]                     NVARCHAR (20)    NOT NULL,
    [VATNUM]                         NVARCHAR (20)    NOT NULL,
    [INCLTAX]                        INT              NOT NULL,
    [HOLD]                           INT              NOT NULL,
    [VENDINVOICESAVESTATUS]          INT              NOT NULL,
    [RELEASEDATECOMMENT]             NVARCHAR (60)    NOT NULL,
    [POOLRECID]                      BIGINT           NOT NULL,
    [PARMJOBSTATUS]                  INT              NOT NULL,
    [VARIANCEAPPROVED]               INT              NOT NULL,
    [VARIANCEAPPROVEDDATETIME]       DATETIME         NOT NULL,
    [VARIANCEAPPROVEDDATETIMETZID]   INT              NOT NULL,
    [VARIANCECOMMENT]                NVARCHAR (255)   NOT NULL,
    [INVOICERELEASEDATE]             DATETIME         NOT NULL,
    [INVOICERELEASEDATETZID]         INT              NOT NULL,
    [ENTERPRISENUMBER]               NVARCHAR (50)    NOT NULL,
    [POSTINGPROFILE]                 NVARCHAR (10)    NOT NULL,
    [NUMBERSEQUENCEGROUP]            NVARCHAR (10)    NOT NULL,
    [SETTLEVOUCHER]                  INT              NOT NULL,
    [TRANSACTIONCODE]                NVARCHAR (10)    NOT NULL,
    [TRANSPORT]                      NVARCHAR (10)    NOT NULL,
    [PORT]                           NVARCHAR (10)    NOT NULL,
    [STATPROCID]                     NVARCHAR (10)    NOT NULL,
    [COUNTYORIGDEST]                 NVARCHAR (10)    NOT NULL,
    [VENDINVOICEGROUP]               NVARCHAR (10)    NOT NULL,
    [VENDPAYMENTGROUP]               NVARCHAR (10)    NOT NULL,
    [DELIVERYPOSTALADDRESS]          BIGINT           NOT NULL,
    [LASTMATCHVARIANCE]              INT              NOT NULL,
    [PARMID]                         NVARCHAR (20)    NOT NULL,
    [ENDDATETIME]                    DATETIME         NOT NULL,
    [ENDDATETIMETZID]                INT              NOT NULL,
    [STARTDATETIME]                  DATETIME         NOT NULL,
    [STARTDATETIMETZID]              INT              NOT NULL,
    [REMITTANCELOCATION]             BIGINT           NOT NULL,
    [IGNORECALCULATEDSALESTAX]       INT              NOT NULL,
    [INVOICETYPE]                    INT              NOT NULL,
    [REQUESTSTATUS]                  INT              NOT NULL,
    [MARKUPGROUP]                    NVARCHAR (10)    NOT NULL,
    [INVENTSITEID]                   NVARCHAR (10)    NOT NULL,
    [INVENTLOCATIONID]               NVARCHAR (10)    NOT NULL,
    [DEFAULTDIMENSION]               BIGINT           NOT NULL,
    [MATCHSTATUS]                    INT              NOT NULL,
    [SOURCEDOCUMENTLINE]             BIGINT           NOT NULL,
    [SOURCEDOCUMENTHEADER]           BIGINT           NOT NULL,
    [VENDORREQUESTEDWORKEREMAIL]     NVARCHAR (80)    NOT NULL,
    [LOGISTICSELECTRONICADDRESS]     BIGINT           NOT NULL,
    [BANKLCIMPORTLINE]               BIGINT           NOT NULL,
    [APPROVER]                       BIGINT           NOT NULL,
    [VARIANCEAPPROVER]               BIGINT           NOT NULL,
    [ACCOUNTINGDISTRIBUTIONTEMPLATE] BIGINT           NOT NULL,
    [PURCHAGREEMENTHEADER_PSN]       BIGINT           NOT NULL,
    [LISTCODE]                       INT              NOT NULL,
    [TRANSPORTATIONDOCUMENT]         BIGINT           NOT NULL,
    [CREATEDDATETIME]                DATETIME         NOT NULL,
    [CREATEDBY]                      NVARCHAR (8)     NOT NULL,
    [DATAAREAID]                     NVARCHAR (4)     NOT NULL,
    [RECVERSION]                     INT              NOT NULL,
    [PARTITION]                      BIGINT           NOT NULL,
    [RECID]                          BIGINT           NOT NULL,
    [ROLBOLDATE]                     DATETIME         NOT NULL,
    [ROLFDADATE]                     DATETIME         NOT NULL,
    [ROLVESSELETADATE]               DATETIME         NOT NULL
);

