CREATE TABLE [dbo].[WMSSTOREZONE] (
    [NAME]             NVARCHAR (60) NOT NULL,
    [STOREZONEID]      NVARCHAR (10) NOT NULL,
    [DATAAREAID]       NVARCHAR (4)  NOT NULL,
    [RECVERSION]       INT           NOT NULL,
    [PARTITION]        BIGINT        NOT NULL,
    [RECID]            BIGINT        NOT NULL,
    [ROLSTOREZONETYPE] INT           NOT NULL,
    CONSTRAINT [I_687ZONEIDX] PRIMARY KEY CLUSTERED ([PARTITION] ASC, [DATAAREAID] ASC, [STOREZONEID] ASC)
);

