-- =============================================
-- Author:		Bryan D. Williams
-- Create date: 2020-02-26
-- Description:	Create Indices for Views 
-- =============================================
CREATE PROCEDURE [dbo].[prCreateDataRepoIndices] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	
CREATE NONCLUSTERED INDEX [VM_INDX_DPL] ON [dbo].[DIRPARTYLOCATION]
(
	[PARTY] ASC,
	[ISPOSTALADDRESS] ASC,
	[ISPRIMARY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
	
CREATE NONCLUSTERED INDEX VW_INDX_VENDTBL_VG
ON [dbo].[VENDTABLE] ([VENDGROUP])
INCLUDE ([ACCOUNTNUM],[PARTY],[DATAAREAID],[PARTITION])
	
CREATE NONCLUSTERED INDEX VW_INDX_IILOC
ON [dbo].[INVENTITEMLOCATION] ([INVENTDIMID])
INCLUDE ([ITEMID],[DATAAREAID])

CREATE NONCLUSTERED INDEX Vw_INDX_INVTBLMOD
ON [dbo].[INVENTTABLEMODULE] ([MODULETYPE])
INCLUDE ([ITEMID],[UNITID],[DATAAREAID])

CREATE NONCLUSTERED INDEX VW_INDX_UOMCON
ON [dbo].[UNITOFMEASURECONVERSION] ([FROMUNITOFMEASURE])
INCLUDE ([TOUNITOFMEASURE],[PRODUCT],[FACTOR],[NUMERATOR],[DENOMINATOR])

CREATE NONCLUSTERED INDEX VW_INDX_INVTRANS_DIM_DA
ON [dbo].[INVENTTRANS] ([INVENTDIMID],[DATAAREAID])
INCLUDE ([ITEMID],[DATEPHYSICAL],[QTY],[DATEINVENT])

CREATE NONCLUSTERED INDEX VW_INDX_INVTRANS_DA
ON [dbo].[INVENTTRANS] ([DATAAREAID])
INCLUDE ([ITEMID],[DATEPHYSICAL],[QTY],[INVENTDIMID],[DATEINVENT])

CREATE NONCLUSTERED INDEX VW_INDX_DIRPARTYLOC
ON [dbo].[DIRPARTYLOCATION] ([ISPOSTALADDRESS],[ISPRIMARY])
INCLUDE ([PARTY],[LOCATION],[PARTITION],[RECID])
	
CREATE NONCLUSTERED INDEX VW_INDX_CUSTINVJOUR_CODE
ON [dbo].[CUSTINVOICEJOUR] ([CURRENCYCODE],[PARTITION])
INCLUDE ([SALESID],[INVOICEDATE],[INVOICEID],[NUMBERSEQUENCEGROUP],[DATAAREAID])

CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[INVENTITEMBARCODE] ([BARCODESETUPID])
INCLUDE ([ITEMBARCODE],[ITEMID],[DATAAREAID],[RECID])

	CREATE NONCLUSTERED INDEX VW_INDX_UOM_TO
ON [dbo].[UNITOFMEASURECONVERSION] ([TOUNITOFMEASURE])
INCLUDE ([FROMUNITOFMEASURE],[PRODUCT],[FACTOR],[NUMERATOR],[DENOMINATOR],[INNEROFFSET],[OUTEROFFSET],[ROUNDING],[MODIFIEDDATETIME],[RECVERSION],[PARTITION],[RECID])

	
CREATE NONCLUSTERED INDEX VW_INDX_CUSTINVTRANS2
ON [dbo].[CUSTINVOICETRANS] ([INVOICEID],[INVOICEDATE],[SALESID],[NUMBERSEQUENCEGROUP],[DATAAREAID],[PARTITION])
INCLUDE ([INVENTTRANSID],[CURRENCYCODE],[QTY],[SALESPRICE],[LINEAMOUNT],[LINEAMOUNTMST])

	CREATE NONCLUSTERED INDEX VW_INDX_CUSTINVTRANS
ON [dbo].[CUSTINVOICETRANS] ([QTY])
INCLUDE ([INVOICEID],[INVOICEDATE],[INVENTTRANSID],[CURRENCYCODE],[SALESPRICE],[LINEAMOUNT],[SALESID],[NUMBERSEQUENCEGROUP],[LINEAMOUNTMST],[DATAAREAID],[PARTITION])

CREATE NONCLUSTERED INDEX VW_INDX_INVENTRANS2
ON [dbo].[INVENTTRANS] ([PACKINGSLIPRETURNED],[INVENTTRANSORIGIN])
INCLUDE ([STATUSISSUE],[DATEPHYSICAL],[QTY],[STATUSRECEIPT],[INVENTDIMID],[DATAAREAID],[PARTITION])

CREATE NONCLUSTERED INDEX VW_INDX_SALESLINE_STATUS
ON [dbo].[SALESLINE] ([ROLWMSRESERVEDSTATUS])
INCLUDE ([SALESID],[ITEMID],[QTYORDERED],[LINEAMOUNT],[INVENTTRANSID],[SALESQTY],[DATAAREAID],[PARTITION])

CREATE NONCLUSTERED INDEX VW_INDX_INVENTRANS
ON [dbo].[INVENTTRANS] ([PACKINGSLIPRETURNED])
INCLUDE ([STATUSISSUE],[DATEPHYSICAL],[QTY],[STATUSRECEIPT],[INVENTDIMID],[INVENTTRANSORIGIN],[DATAAREAID],[PARTITION])

CREATE NONCLUSTERED INDEX VW_INDX_LPA
ON [dbo].[LOGISTICSPOSTALADDRESS] ([LOCATION],[PARTITION])
INCLUDE ([COUNTRYREGIONID],[ZIPCODE],[STATE],[CITY],[STREET],[VALIDTO],[VALIDFROM])

	CREATE NONCLUSTERED INDEX VW_INDX_LLOC
ON [dbo].[LOGISTICSLOCATION] ([PARTITION],[RECID])
INCLUDE ([DESCRIPTION])

	CREATE NONCLUSTERED INDEX VW_INDX_ERPC
ON [dbo].[ECORESPRODUCTCATEGORY] ([CATEGORY])
INCLUDE ([PRODUCT])

    CREATE NONCLUSTERED INDEX VW_INDX_PRICEDISCAT
ON [dbo].[PRICEDISCADMTRANS] ([ACCOUNTRELATION])
INCLUDE ([ACCOUNTCODE],[ITEMRELATION],[FROMDATE],[TODATE],[AMOUNT],[INVENTDIMID],[DATAAREAID])

CREATE NONCLUSTERED INDEX VW_INDX_PRICEDISCAT_DATES
ON [dbo].[PRICEDISCADMTRANS] ([ACCOUNTRELATION],[DATAAREAID],[FROMDATE],[TODATE])
INCLUDE ([ACCOUNTCODE],[ITEMRELATION],[AMOUNT],[CURRENCY],[UNITID],[INVENTDIMID])


CREATE NONCLUSTERED INDEX VW_INDX_INVENTDIM
ON [dbo].[INVENTDIM] ([DATAAREAID])
INCLUDE ([INVENTDIMID],[INVENTLOCATIONID])

CREATE NONCLUSTERED INDEX VW_INDX_CUST
ON [dbo].[CUSTTABLE] ([ACCOUNTNUM])


CREATE NONCLUSTERED INDEX VW_INDX_DIRPARTY
ON [dbo].[DIRPARTYTABLE] ([RECID])

CREATE NONCLUSTERED INDEX VW_INDX_PRICEDISCAT_DATE_RANGE
ON [dbo].[PRICEDISCADMTRANS] ([ITEMRELATION],[ACCOUNTRELATION],[FROMDATE],[TODATE])
INCLUDE ([ACCOUNTCODE],[AMOUNT],[INVENTDIMID],[DATAAREAID])

CREATE NONCLUSTERED INDEX VW_INDX_INVENTDIM_ID
ON [dbo].[INVENTDIM] ([INVENTDIMID],[DATAAREAID])
INCLUDE ([INVENTLOCATIONID])

END
