-- =============================================
-- Author:		Bryan D. Williams
-- Create date: 2020-02-26
-- Description:	Drop Indices for Tables in Views 
-- =============================================
CREATE PROCEDURE [dbo].[prDropDataRepoIndices] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DROP INDEX  VM_INDX_DPL ON [dbo].[DIRPARTYLOCATION] 

	
	DROP INDEX  VW_INDX_IILOC ON [dbo].[INVENTITEMLOCATION] 

	DROP INDEX  VM_INDX_INVTBLMOD ON [dbo].[INVENTTABLEMODULE] 

	DROP INDEX  VW_INDX_UOMCON ON [dbo].[UNITOFMEASURECONVERSION] 

	DROP INDEX  VW_INDX_INVTRANS_DIM_DA ON [dbo].[INVENTTRANS] 

	DROP INDEX  VW_INDX_INVTRANS_DA ON [dbo].[INVENTTRANS] 

	DROP INDEX  VW_INDX_DIRPARTYLOC ON [dbo].[DIRPARTYLOCATION] 
	
	DROP INDEX  VW_INDX_CUSTINVJOUR_CODE ON [dbo].[CUSTINVOICEJOUR] 

	DROP INDEX  VM_INDX_INVENTITEMDARCODE_SETUPID ON [dbo].[INVENTITEMBARCODE]

	DROP INDEX  VW_INDX_UOM_TO ON [dbo].[UNITOFMEASURECONVERSION] 
	
	DROP INDEX  VW_INDX_CUSTINVTRANS2 ON [dbo].[CUSTINVOICETRANS]

	DROP INDEX  VW_INDX_CUSTINVTRANS ON [dbo].[CUSTINVOICETRANS] 

	DROP INDEX  VW_INDX_INVENTRANS2 ON [dbo].[INVENTTRANS] 

	DROP INDEX  VW_INDX_SALESLINE_STATUS ON [dbo].[SALESLINE] 

	DROP INDEX  VW_INDX_INVENTRANS ON [dbo].[INVENTTRANS] 

	DROP INDEX  VW_INDX_LPA ON [dbo].[LOGISTICSPOSTALADDRESS] 

	DROP INDEX  VW_INDX_LLOC ON [dbo].[LOGISTICSLOCATION] 

	DROP INDEX  VW_INDX_ERPC ON [dbo].[ECORESPRODUCTCATEGORY]

	DROP INDEX  VW_INDX_PRICEDISCAT ON [dbo].[PRICEDISCADMTRANS] 

	DROP INDEX  VW_INDX_PRICEDISCAT_DATES ON [dbo].[PRICEDISCADMTRANS] 

	DROP INDEX  VW_INDX_INVENTDIM ON [dbo].[INVENTDIM] 

	DROP INDEX  VW_INDX_CUST ON [dbo].[CUSTTABLE] 

	DROP INDEX  VW_INDX_DIRPARTY ON [dbo].[DIRPARTYTABLE] 

	DROP INDEX  VW_INDX_PRICEDISCAT_DATE_RANGE ON [dbo].[PRICEDISCADMTRANS] 

	DROP INDEX  VW_INDX_INVENTDIM_ID ON [dbo].[INVENTDIM] 

	DROP INDEX VW_INDX_VP_TLE ON dbo.VP_tmpTLESummary

END
