

-- =============================================
-- Author:		Bryan D Williams
-- Create date: <Create Date,,>
-- Description:	Build primary entity for each customer
-- BDW 04/06/2020 - Added Accounts with no sales
-- =============================================
CREATE PROCEDURE [dbo].[prPrimaryCustomerLoad] 
	AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	TRUNCATE TABLE dbo.L2_CUSTOMER_PRIMARY_LEGAL_ENTITY

	INSERT INTO 
		L2_CUSTOMER_PRIMARY_LEGAL_ENTITY(ACCOUNTNUM,DATAAREAID)
	SELECT 
	ALL_LIST.CUSTACCOUNT, ALL_LIST.DATAAREAID 
	FROM (
		SELECT COUNT(SALESID) SALES_CNT,S.CUSTACCOUNT,S.DATAAREAID 
		FROM SALESTABLE S
		GROUP BY S.CUSTACCOUNT,S.DATAAREAID
	) ALL_LIST 
	INNER JOIN (
		SELECT MAX(SALES_CNT) MAX_CNT, BASE.CUSTACCOUNT FROM (
			SELECT COUNT(SALESID) SALES_CNT,S.CUSTACCOUNT,S.DATAAREAID FROM SALESTABLE S
			GROUP BY S.CUSTACCOUNT,S.DATAAREAID
		) BASE
		GROUP BY BASE.CUSTACCOUNT
	) UNIQ 
	ON ALL_LIST.SALES_CNT = UNIQ.MAX_CNT AND  ALL_LIST.CUSTACCOUNT = UNIQ.CUSTACCOUNT
				
	UNION
				
	SELECT NOSD.ACCOUNTNUM, MIN(NOSD.DATAAREAID) 
	FROM (
		SELECT DISTINCT CUS.ACCOUNTNUM, CUS.DATAAREAID
		FROM CUSTTABLE CUS 
		WHERE NOT EXISTS (
			SELECT S.CUSTACCOUNT 
			FROM SALESTABLE S 
			WHERE S.CUSTACCOUNT = CUS.ACCOUNTNUM
		)
	) NOSD --NO SALES DEDUP
	GROUP BY NOSD.ACCOUNTNUM
END

